services:
  networkis:
    environment:
      NUMERIC_ACCELERATOR: ${NUMERIC_ACCELERATOR:-cuda}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
