FROM networkis:candidate-550edfb7d65c
LABEL networkis.development=true
COPY . /app
RUN python /app/scripts/write-build-info.py
RUN cd /app/frontend && node /usr/local/lib/node_modules/npm/bin/npm-cli.js run build
