"""Sercos III own phase/telegram/time-slot profile, not generic Ethernet scheduling."""
PRINCIPLE='https://www.sercos.org/technology/functions-and-features/transmission-principle/'
UCC='https://www.sercos.org/technology/functions-and-features/uc-channel/'
BROCHURE='https://www.sercos.org/downloads/brochures/?cHash=584b637215724278782d4ba6b3f5cfc2&tx_vdsercosdownloads_downloads%5Baction%5D=download&tx_vdsercosdownloads_downloads%5Bcontroller%5D=File&tx_vdsercosdownloads_downloads%5Bfile%5D=Sercos_Sercos_III_Broschuere_2016_EN_US__V02_web.pdf'
API='https://www.hilscher.com/fileadmin/cms_upload/de/Resources/pdf/Sercos_Master_Protocol_API_11_EN.pdf'
SOURCES={PRINCIPLE:'SercosInternational primary transmission principle actualcontent read2026-10-02; public supported cycle series/MDT/AT/CP/UCC.',UCC:'SercosInternational primary UnifiedCommunicationChannel/S-IP description read2026-10-02; independently bound Ethernet protocols.',BROCHURE:'SercosInternational2016brochure original15pagePDF actualprinted4-11; physical100Mfull, cycle/telegram/schedule/topology definitions. Publicoverview not full licensedIEC61158text.',API:'HilscherDOC081103API11EN Rev11 September2013 masterV2.1.x.x source-qualifiedv1.3implementation, actualpp8/47-54/160-162. Device limits notallSercosIII.'}
DECLARATIONS=[]
def d(k,t,meaning,lo=None,hi=None,unit=None,options=None,integer=False,source=BROCHURE):
 DECLARATIONS.append(dict(key='sercos_'+k,type=t,description=meaning,min=lo,max=hi,unit=unit,options=options,integer=integer,source=source,source_revision=SOURCES[source]))
for k,meaning,opts,src in [
 ('profile','Selected public protocol reference versus HilscherV2.1x or independently qualified actual implementation.',['PUBLIC_SERIII_REFERENCE','HILSCHER_V2_1','REGISTERED_ACTUAL'],API),
 ('proposal_mode','Actual commissioned values versus explicitly selected literature minimum-mode proposals.',['ACTUAL_CONFIG','SOURCE_MINIMUM_PROPOSALS'],PRINCIPLE),
 ('phase','Actual NRT/phase CP0..4; CP3zeros/invalidprocessdata mustnotbeaccepted as productionCP4.', ['NRT','CP0','CP1','CP2','CP3','CP4'],API),
 ('topology','Actual line/logicalring versus redundantphysicalring, two-line brokenring or qualifiedextension.',['LINE','RING','BROKEN_RING','REGISTERED_ACTUAL'],BROCHURE),
 ('role','Actual master versus slave, separately bound channel ownership.',['MASTER','SLAVE'],PRINCIPLE),
 ('channel','Actual collision-freeSercosRTC versus separately bound EthernetUCC.',['REAL_TIME','UCC'],UCC),
 ('mechanism','Actual M/S,DCC,SVC,SMP or independent safetycontainer, notautogenerated genericEthernetFIFO.',['M_S','DCC','SVC','SMP','SAFETY','OTHER_ETHERNET'],BROCHURE),
 ('telegram','Actual masterdata(MDT) versus acknowledge(AT), or independentnonSercosUCframe.',['MDT','AT','UCC_FRAME'],PRINCIPLE),
 ('duplex','Actual full-duplex100M PHY under selectedreference.',['FULL','HALF'],BROCHURE),
 ('purpose','Operational data versus explicitly separate commissioning traffic.',['OPERATIONAL','COMMISSIONING'],API),
 ('outcome','Actual channel/phase/cycle/consumer result.',['ACCEPTED','PHASE_NOT_READY','BAD_MAPPING','SYNC_LOST','MISSING','STALE','UNKNOWN'],API),
]:d(k,'select',meaning,options=opts,source=src)
for k,meaning,lo,hi,unit,integer,src in [
 ('link_bps','Actual100MbpsSercosIIIreference PHY, notSercosI/II2..16Mbps or automatic1GbpsEthernet.',0,None,'bit/s',False,BROCHURE),
 ('cycle_ns','ActualS-0-1002buscycle31.25/62.5/125us or250us multiples to65ms; devices mayrequiremore.',1,None,'ns',True,PRINCIPLE),
 ('master_min_ns','Actualselectedmaster minimumcyclecapability; Hilscher250us notgeneric31.25us.',1,None,'ns',True,API),
 ('slave_min_ns','Actualworstparticipatingslave minimumcyclecapability.',1,None,'ns',True,API),
 ('ethertype','Actual0x88CDRTC, UCCusesothertypes. No UDP/TCPRTCfallback.',0,65535,None,True,PRINCIPLE),
 ('slave_count','Actualconfiguredslaves, Hilschermax511 includingphysicalmapping qualification.',1,None,None,True,API),
 ('mdt_count','ActualMDT0..3telegramcount percycle.',1,4,None,True,BROCHURE),
 ('at_count','ActualAT0..3telegramcount percycle.',1,4,None,True,BROCHURE),
 ('telegram_index','ActualMDT/ATtelegramindex0..3, notparticipantaddress.',0,3,None,True,BROCHURE),
 ('data_bytes','Actual full selectedSercosdatafield40..1494includeshotplug/SVC/RTD/padding, not1494appbytesperdevice.',0,None,'byte',True,BROCHURE),
 ('hotplug_bytes','Actualhotplugregionlength.',0,None,'byte',True,BROCHURE),
 ('svc_bytes','Actualaggregateacyclicservicechannelregionlength.',0,None,'byte',True,BROCHURE),
 ('rtd_bytes','ActualaggregatedM/S-DCC-SMP-safetycontainerreal-timeregionlength.',0,None,'byte',True,BROCHURE),
 ('padding_bytes','Actualremainingpadding in the chosenSercosdatafield.',0,None,'byte',True,BROCHURE),
 ('connection_offset_bytes','Actualapprovedperdeviceconnectionbyteoffset withinRTDregion.',0,None,'byte',True,API),
 ('connection_bytes','Actualapproveddirectionalconnectiondata/controlsize.',0,None,'byte',True,API),
 ('occupancy_bytes','Actualselectedtelegram wireoccupation=datafield+44protocolmanagement/preamble/FCS/IFG.',0,None,'byte',True,BROCHURE),
 ('wire_ns','Actualselectedtelegramserializedoccupancy atactualPHY; brochure6.8usroundednotexact6.72us.',0,None,'ns',False,BROCHURE),
 ('mdt_occupancy_sum','Actualsum of allMDTtelegramwireoccupancies perport/cycle, notonepayloadtimesparticipants.',0,None,'byte',True,BROCHURE),
 ('at_occupancy_sum','Actualsum of allATtelegramwireoccupancies perport/cycle.',0,None,'byte',True,BROCHURE),
 ('cycle_wire_ns','ActualaggregateMDT+ATserializedwiretime; separatepath/slavedelay/schedulerguards.',0,None,'ns',False,BROCHURE),
 ('ring_delay_ns','ActualS-0-1015commissionedlogicalroute delay; no zeroasprovenring.',0,None,'ns',False,API),
 ('guard_ns','Actualindependenttime-slotguard/forwardingmargin fromcompiledschedule.',0,None,'ns',False,API),
 ('rt_end_ns','ActualRTCendoffset mustcoverserializedcycle/path/guard beforeUCC.',0,None,'ns',False,API),
 ('t1_ns','ActualATstartS-0-1006afterMST;0..cyclewithinselectedHilscherprofile.',0,None,'ns',True,API),
 ('t3_ns','ActualcommandvaluevalidtimeS-0-1008;0..cycle, distinctapplication deadline.',0,None,'ns',True,API),
 ('process_cycle_ns','ActualapplicationprocessingperiodtPcyc, notautomaticbuscycle.',1,None,'ns',True,API),
 ('sync_time_ns','ActualS-0-1007feedbackcaptureoffset0..tPcyc, referencedtoTSref notMSTabsolute.',0,None,'ns',True,API),
 ('sync_jitter_ns','ActualS-0-1023calculatedmaximumsyncjitter; selectedHilscher<=cycle/2, notobserveddefault0.',0,None,'ns',False,API),
 ('t6_ns','ActualUCCstartS-0-1017;Hilscher0switcheschanneloff.',0,None,'ns',True,API),
 ('t7_ns','ActualUCCendS-0-1017withinbuscycle.',0,None,'ns',True,API),
 ('ucc_window_ns','Actualavailablewindow=t7-t6 whenenabled; excludesRTC.',0,None,'ns',True,API),
 ('ucc_mtu_bytes','ActualrequestedS-0-1027.0.1UCCdataMTU, Hilscher46..1500 andtime-windowlimited; no assumed576default.',0,None,'byte',True,API),
 ('process_output_bytes','ActualmasterMDTprocessimageincludingconnectioncontrol;Hilscher0..5760even.',0,None,'byte',True,API),
 ('process_input_bytes','ActualmasterATprocessimageincludingconnectioncontrol;Hilscher0..5760even.',0,None,'byte',True,API),
 ('cp0_wait_cycles','ActualconsecutiveidenticalCP0framesrequiredbeforephaseup;Hilscher>=100example/factoryproposal.',0,None,'cycle',True,API),
 ('allowed_mst_losses','ActualS-0-1003allowedconsecutiveMST/MDTerrorsbeforephasefallback; dependsonslave.',0,None,'cycle',True,API),
 ('connection_loss_limit','Actualconnectionallowedlossbudget;masterMSTlossthresholdmusthigher.',0,None,'cycle',True,API),
 ('observed_mst_losses','ActualconsecutiveobservedMST/MDTlosses atselectedconsumer.',0,None,'cycle',True,API),
 ('source_bound_ns','Actualsourceapplication/connectionproductionbound.',0,None,'ns',False,API),
 ('network_bound_ns','ActualcompleteSercoschannel/route/schedulebound, distinctoneframewiretime.',0,None,'ns',False,API),
 ('consumer_bound_ns','Actualconnectionvalidate/applicationconsumerbound.',0,None,'ns',False,API),
 ('e2e_bound_ns','Actualsource+network+consumerfunctionalchain.',0,None,'ns',False,API),
 ('e2e_limit_ns','Actualindependentfunctionalacceptancerequirement.',0,None,'ns',False,API),
 ('age_ns','Actualcorrelatedprocessdataage atconsumer.',0,None,'ns',False,API),
 ('freshness_ns','Actualprocessdatafreshnessrequirement.',0,None,'ns',False,API),
]:d(k,'number',meaning,lo,hi,unit,integer=integer,source=src)
for k,meaning in [('ucc_enabled','ActualenabledUCCtimewindow, not allcyclefreeEthernet.'),('mapping_valid','Actualdevice/channel/offset/IDN/controlword/layoutbindingverified.'),('phase_ready','ActualallrequiredprocedurecommandsandCP4slavevalidityobserved.'),('producer_ready','ActualC-CONproducerready inCP4 only.'),('schedule_verified','Actualfullcyclealltelegram/route/UCCcontentionscheduleverified.'),('clock_verified','ActualMST/TSref/syncuncertaintyverified.'),('data_accepted','Actualcompletedownstreamprocessdataconsumeracceptance.'),('safety_verified','Independentqualifiedsafetycontainer/schedule/functionalassuranceverified;ordinarySercoscapacitydoesnotproveSIL.')]:d(k,'boolean',meaning,source=API)
for k,meaning,src in [('device_source','Actualmaster/slavefirmware/edition/SCP/cyclecapabilities.',API),('binding_source','Actualcanonicalnode/port/topology/channel/connectionownership.',BROCHURE),('idn_source','ActualapproveddirectionalIDN/type/controlword/channelmap.',API),('schedule_source','Actualcompiledtiming/MDT-ATlayout/allport/UCCschedulingsource.',API),('clock_source','ActualMST/TSref/source/correlation/uncertainty.',API),('physical_source','ActualPHY/cable/loopback/ringredundancy/hardwareforwardingqualification.',BROCHURE),('acceptance_source','Actualindependentfunctionalapplicationrequirements.',API),('observation_source','Actualcorrelatedframe/phase/producerready/allport/timingtrace.',API),('registered_source','Actualindependentlyqualifiedalternativeedition/physical/pathprofile.',PRINCIPLE),('ucc_protocol_source','ActualindependentEthernet/IP/S-IPprotocol andtypedboundpath.',UCC),('safety_source','Actualindependentsafetyprofile/CRC/redundancy/assurancecase.',BROCHURE)]:d(k,'text',meaning,source=src)
REQUIRED=('profile','proposal_mode','phase','topology','role','channel','mechanism','telegram','device_source','binding_source','idn_source','schedule_source','clock_source','physical_source','acceptance_source')
REMOVED={k:'SercosIII own cycle/MDT-ATphase/RTC-UCCmechanisms replace implicitgenericCAN/Ethernetparameters;NISscenario controls remainindependent.'for k in('bitrate','reserved_bandwidth_percent','sync_method','retransmission_enabled','retransmission_rate','retry_limit','retransmission_delay_ms','gateway_maximum_throughput','gateway_input_buffer','gateway_output_buffer','gateway_maximum_routes','gateway_maximum_messages_s','mtu_bytes','duplex','vlan_id','rate_limit_bit_s')}

def semantics():
 rules=[]
 def r(k,w=None,source=BROCHURE,**kw):rules.append(dict(parameter=k if k=='local_timing_evidence'else'sercos_'+k,when={'sercos_'+a:b for a,b in(w or{}).items()},source=source,source_revision=SOURCES[source],**kw))
 r('local_timing_evidence',allowed=[])
 for k in('profile','topology'):r('registered_source',{k:'REGISTERED_ACTUAL'},required=True)
 cycles=[31250,62500,125000,*range(250000,65000001,250000)]
 for profile in('PUBLIC_SERIII_REFERENCE','HILSCHER_V2_1'):
  w={'profile':profile};r('cycle_ns',w,source=PRINCIPLE,allowed=cycles);r('link_bps',w,allowed=[100000000]);r('duplex',w,allowed=['FULL'])
  r('data_bytes',{**w,'channel':'REAL_TIME'},minimum=40,maximum=1494)
 r('cycle_ns',{'profile':'HILSCHER_V2_1'},source=API,minimum=250000)
 for k in('master_min_ns','slave_min_ns'):r('cycle_ns',minimum_parameter='sercos_'+k)
 r('link_bps',exclusive_minimum=0)
 r('ethertype',{'channel':'REAL_TIME'},source=PRINCIPLE,allowed=[0x88CD]);r('ethertype',{'channel':'UCC'},source=UCC,forbidden=[0x88CD])
 r('ucc_protocol_source',{'channel':'UCC'},source=UCC,required=True)
 r('mechanism',{'channel':'UCC'},allowed=['OTHER_ETHERNET']);r('telegram',{'channel':'UCC'},allowed=['UCC_FRAME'])
 r('mechanism',{'channel':'REAL_TIME'},forbidden=['OTHER_ETHERNET']);r('telegram',{'channel':'REAL_TIME'},forbidden=['UCC_FRAME'])
 r('telegram_index',{'telegram':'MDT'},exclusive_maximum_expression='sercos_mdt_count');r('telegram_index',{'telegram':'AT'},exclusive_maximum_expression='sercos_at_count')
 r('data_bytes',{'channel':'REAL_TIME'},equal_expression={'sum':['sercos_hotplug_bytes','sercos_svc_bytes','sercos_rtd_bytes','sercos_padding_bytes']})
 for k in('hotplug_bytes','svc_bytes','rtd_bytes','padding_bytes'):r(k,{'channel':'REAL_TIME'},when_present=['sercos_data_bytes'],required=True)
 r('connection_bytes',maximum_expression={'subtract':['sercos_rtd_bytes','sercos_connection_offset_bytes']})
 for k in('rtd_bytes','connection_offset_bytes'):r(k,when_present=['sercos_connection_bytes'],required=True)
 r('occupancy_bytes',{'channel':'REAL_TIME'},equal_expression={'sum':['sercos_data_bytes',44]})
 r('data_bytes',{'channel':'REAL_TIME'},when_present=['sercos_occupancy_bytes'],required=True)
 r('wire_ns',equal_ratio={'numerator_parameter':'sercos_occupancy_bytes','factor':8000000000,'denominator_product':['sercos_link_bps'],'denominator_offset':1})
 for k in('occupancy_bytes','link_bps'):r(k,when_present=['sercos_wire_ns'],required=True)
 for k,count in [('mdt_occupancy_sum','mdt_count'),('at_occupancy_sum','at_count')]:
  r(k,minimum_expression={'product':[84,'sercos_'+count]},maximum_expression={'product':[1538,'sercos_'+count]})
  r(count,when_present=['sercos_'+k],required=True)
 r('cycle_wire_ns',equal_ratio={'numerator_sum':['sercos_mdt_occupancy_sum','sercos_at_occupancy_sum'],'factor':8000000000,'denominator_product':['sercos_link_bps'],'denominator_offset':1})
 for k in('mdt_occupancy_sum','at_occupancy_sum','link_bps'):r(k,when_present=['sercos_cycle_wire_ns'],required=True)
 r('rt_end_ns',minimum_expression={'sum':['sercos_cycle_wire_ns','sercos_ring_delay_ns','sercos_guard_ns']},maximum_parameter='sercos_cycle_ns')
 for k in('cycle_wire_ns','ring_delay_ns','guard_ns','cycle_ns'):r(k,when_present=['sercos_rt_end_ns'],required=True)
 w={'profile':'HILSCHER_V2_1'}
 for k in('t1_ns','t3_ns','t6_ns','t7_ns'):r(k,w,source=API,maximum_parameter='sercos_cycle_ns')
 r('sync_time_ns',w,source=API,maximum_parameter='sercos_process_cycle_ns')
 r('sync_jitter_ns',w,source=API,maximum_expression={'product':[.5,'sercos_cycle_ns']})
 r('slave_count',w,source=API,maximum=511);r('cp0_wait_cycles',w,source=API,minimum=100)
 for k in('process_input_bytes','process_output_bytes'):r(k,w,source=API,maximum=5760,multiple_of=2)
 r('allowed_mst_losses',source=API,exclusive_minimum_expression='sercos_connection_loss_limit')
 r('observed_mst_losses',{'data_accepted':True},source=API,maximum_parameter='sercos_allowed_mst_losses')
 r('t6_ns',{'ucc_enabled':False,'profile':'HILSCHER_V2_1'},source=API,allowed=[0])
 r('t6_ns',{'ucc_enabled':True,'profile':'HILSCHER_V2_1'},source=API,exclusive_minimum=0)
 r('t6_ns',{'ucc_enabled':True},minimum_parameter='sercos_rt_end_ns')
 r('ucc_window_ns',{'ucc_enabled':True},source=API,equal_expression={'subtract':['sercos_t7_ns','sercos_t6_ns']},minimum=6720)
 for k in('t6_ns','t7_ns'):r(k,{'ucc_enabled':True},when_present=['sercos_ucc_window_ns'],required=True)
 r('ucc_mtu_bytes',w,source=API,minimum=46,maximum=1500)
 r('ucc_window_ns',{'ucc_enabled':True,'profile':'HILSCHER_V2_1'},source=API,minimum_expression={'product':[80,{'sum':['sercos_ucc_mtu_bytes',38]}]})
 chain=('source_bound_ns','network_bound_ns','consumer_bound_ns')
 r('e2e_bound_ns',source=API,equal_expression={'sum':['sercos_'+k for k in chain]})
 for k in chain:r(k,when_present=['sercos_e2e_bound_ns'],required=True)
 r('e2e_bound_ns',maximum_parameter='sercos_e2e_limit_ns');r('age_ns',maximum_parameter='sercos_freshness_ns')
 w={'data_accepted':True}
 for k,v in [('outcome','ACCEPTED'),('mapping_valid',True),('schedule_verified',True),('clock_verified',True)]:r(k,w,required=True,allowed=[v])
 for k in('cycle_ns','link_bps','duplex','master_min_ns','slave_min_ns','observation_source','purpose','e2e_bound_ns','e2e_limit_ns','age_ns','freshness_ns'):r(k,w,required=True)
 w={'data_accepted':True,'channel':'REAL_TIME','purpose':'OPERATIONAL'}
 for k,v in [('phase','CP4'),('phase_ready',True),('producer_ready',True)]:r(k,w,source=API,required=True,allowed=[v])
 for k in('mdt_count','at_count','telegram_index','data_bytes','connection_offset_bytes','connection_bytes','mdt_occupancy_sum','at_occupancy_sum','cycle_wire_ns','rt_end_ns','allowed_mst_losses','observed_mst_losses','ethertype'):r(k,w,required=True)
 for k in('t6_ns','t7_ns','ucc_window_ns','ucc_mtu_bytes'):r(k,{'data_accepted':True,'ucc_enabled':True},required=True)
 for k in('safety_source','safety_verified'):r(k,{'data_accepted':True,'mechanism':'SAFETY'},required=True,**({'allowed':[True]}if k=='safety_verified'else{}))
 return dict(rate_model={'type':'SERIII_EXPLICIT_CYCLE_RTC_UCC_AND_DEVICE_CAPABILITIES','fields':[]},required_parameters=['sercos_'+k for k in REQUIRED],native_parameter_prefixes=['sercos_'],parameter_constraints=rules,
  parameter_evidence_scope='EXPLICIT_LAYER',physical_layer_profile_id='actual_sercos_iii_full_duplex_link',medium_access_model='MASTER_TIMED_MDT_AT_AND_UCC_WINDOWS',arbitration_model_id='REGISTERED_CYCLE_CHANNEL_LAYOUT',
  mechanisms={'qualification':['SERIII_NOT_SERI_SERII','CP3_ZEROES_NOT_CP4_VALID_DATA','RTC_NOT_GENERIC_ETHERNET_QUEUE','SAFETY_CONTAINER_INDEPENDENT_ASSURANCE'],'transmission':['MDT_AT_AGGREGATE_CHANNELS','DCC_SVC_SMP','INDEPENDENT_UCC_ETHERNET']})
def fields():
 out=[]
 for spec in DECLARATIONS:
  k=spec['key'][7:];v={a:b for a,b in spec.items()if b is not None}
  v.update(label=k.replace('_',' '),category='technology',scope='network',editable=True,required=k in REQUIRED,parameter_origin='DEVICE_CONFIGURATION',default_status='UNKNOWN',validation_relevant=True,simulation_relevant=False)
  defaults=[]
  if k in('cycle_ns','link_bps','duplex'):
   for profile,cycle in [('PUBLIC_SERIII_REFERENCE',31250),('HILSCHER_V2_1',250000)]:
    source=API if profile=='HILSCHER_V2_1'and k=='cycle_ns'else spec['source']
    defaults.append(dict(when={'sercos_profile':profile,'sercos_proposal_mode':'SOURCE_MINIMUM_PROPOSALS'},value={'cycle_ns':cycle,'link_bps':100000000,'duplex':'FULL'}[k],source=source,source_revision=SOURCES[source]))
  if k=='ethertype':defaults.append(dict(when={'sercos_channel':'REAL_TIME'},value=0x88CD,source=PRINCIPLE,source_revision=SOURCES[PRINCIPLE]))
  if k=='cp0_wait_cycles':defaults.append(dict(when={'sercos_profile':'HILSCHER_V2_1','sercos_proposal_mode':'SOURCE_MINIMUM_PROPOSALS'},value=100,source=API,source_revision=SOURCES[API]))
  if defaults:v.update(default_status='PROPOSED_CONDITIONAL',conditional_defaults=defaults)
  out.append(v)
 return out
