"""Shared constants for requirement expansion."""

WORKFLOW_STATUSES = (
    "RECEIVED",
    "ANALYZING",
    "AMBIGUOUS",
    "WAITING_FOR_INPUT",
    "GENERATING",
    "VALIDATING",
    "REPAIRING",
    "INCOMPLETE",
    "READY_FOR_REVIEW",
    "APPROVED",
    "COMPLETED",
    "FAILED",
    "BLOCKED",
)

ASSUMPTION_STATUSES = (
    "PROPOSED",
    "CONFIRMED",
    "REJECTED",
    "MODIFIED",
    "UNKNOWN",
    "REQUIRED_REVIEW",
    "OPTIONAL",
)

PARAMETER_STATUSES = (
    "KNOWN",
    "PROPOSED",
    "UNKNOWN",
    "REQUIRED",
    "OPTIONAL",
    "DEFAULTED",
)

CAN_FD_PAYLOAD_BYTES = (0, 8, 12, 16, 20, 24, 32, 48, 64)
CAN_FD_MAX_BITRATE_MBIT_S = 8.0
AUTOMOTIVE_ETHERNET_MAX_BITRATE_MBIT_S = 100.0
ETHERNET_MAX_BITRATE_MBIT_S = 1000.0
PIXEL_UNITS = ("px", "pixel")

ENGINE_VERSION = "0.2.0"
