// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform">> = Specific
  const handler = {} as typeof import("../../../src/app/platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/simulations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/simulations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/simulations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/agent">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/capacity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/capacity">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/capacity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/engineering/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/engineering">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/engineering/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/intelligence">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/results">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/routing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/routing">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/routing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/simulation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/simulation">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/simulation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/trace-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/trace-analysis">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/trace-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/validation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/validation">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/validation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/trace-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trace-analysis">> = Specific
  const handler = {} as typeof import("../../../src/app/trace-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/trace-projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trace-projects">> = Specific
  const handler = {} as typeof import("../../../src/app/trace-projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/workflow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflow">> = Specific
  const handler = {} as typeof import("../../../src/app/workflow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/diagnostics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/diagnostics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/diagnostics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/feedback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/agent/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/agent/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/program-cache/simulation-jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/program-cache/simulation-jobs">> = Specific
  const handler = {} as typeof import("../../../src/app/api/program-cache/simulation-jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/simulations/[id]/artifacts/[format]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simulations/[id]/artifacts/[format]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/simulations/[id]/artifacts/[format]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/simulations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simulations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/simulations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/simulations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simulations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/simulations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/simulations/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simulations/validate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/simulations/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/technologies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/technologies">> = Specific
  const handler = {} as typeof import("../../../src/app/api/technologies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trace-import/[sessionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trace-import/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trace-import/[sessionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/trace-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trace-import">> = Specific
  const handler = {} as typeof import("../../../src/app/api/trace-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
