"""Industry template choices; reference technology identities only."""
MODEL_TYPES = ({'device_types': ['HardwareNode', 'Gateway', 'Sensor', 'Actuator', 'Switch', 'Router'],
  'id': 'generic_networking',
  'label': 'Generische Kommunikationsarchitektur',
  'recommended_technologies': ['ethernet',
                               'ip',
                               'udp',
                               'tcp',
                               'generic_serial',
                               'generic_can',
                               'generic_ethernet',
                               'custom_udp',
                               'custom_tcp',
                               'custom_binary',
                               'custom_text',
                               'custom_protocol']},
 {'device_types': ['ECU', 'Gateway', 'DomainController', 'ZoneController', 'Sensor', 'Actuator'],
  'id': 'automotive',
  'label': 'Automotive / Vehicle',
  'recommended_technologies': ['can',
                               'can_fd',
                               'can_xl',
                               'lin',
                               'flexray',
                               'automotive_ethernet',
                               'canopen',
                               'j1939',
                               'isobus',
                               'someip',
                               'doip',
                               'uds',
                               'xcp',
                               'obd2',
                               'tsn']},
 {'device_types': ['PLC', 'RemoteIO', 'IndustrialPC', 'Sensor', 'Actuator', 'Gateway'],
  'id': 'industrial_automation',
  'label': 'Industrial Automation / SPS',
  'recommended_technologies': ['profinet',
                               'profibus_dp',
                               'ethercat',
                               'ethernet_ip',
                               'modbus_tcp',
                               'modbus_rtu',
                               'canopen',
                               'opc_ua',
                               'opc_ua_pubsub',
                               'io_link',
                               'generic_serial']},
 {'device_types': ['RobotController', 'IndustrialPC', 'Sensor', 'Actuator', 'Gateway'],
  'id': 'robotics_ros',
  'label': 'Robotics / ROS 2',
  'recommended_technologies': ['ros2',
                               'dds',
                               'ethercat',
                               'profinet',
                               'ethernet_ip',
                               'canopen',
                               'modbus_tcp',
                               'modbus_rtu',
                               'usb',
                               'ethernet']},
 {'device_types': ['FlightComputer', 'RemoteTerminal', 'Sensor', 'Actuator', 'Gateway'],
  'id': 'aerospace',
  'label': 'Aerospace / Avionics'},
 {'device_types': ['TrainControlUnit', 'VehicleControlUnit', 'Gateway', 'Sensor', 'Actuator', 'HMI'],
  'id': 'rail',
  'label': 'Rail',
  'recommended_technologies': ['mvb', 'wtb', 'etb', 'trdp', 'canopen', 'profinet', 'ethernet']},
 {'device_types': ['MarineController', 'Gateway', 'Sensor', 'Actuator', 'Display'],
  'id': 'marine',
  'label': 'Marine / Off-Highway',
  'recommended_technologies': ['nmea0183',
                               'nmea2000',
                               'iec61162',
                               'j1939',
                               'can',
                               'can_fd',
                               'modbus_tcp',
                               'modbus_rtu',
                               'ethernet']},
 {'device_types': ['BuildingController', 'Gateway', 'Sensor', 'Actuator', 'Meter'],
  'id': 'building_automation',
  'label': 'Building Automation'},
 {'device_types': ['EnergyController', 'IED', 'Gateway', 'Meter', 'Sensor', 'Actuator'],
  'id': 'energy',
  'label': 'Energy / Smart Grid'},
 {'device_types': ['PLC', 'DCSController', 'RemoteIO', 'FieldDevice', 'Sensor', 'Actuator'],
  'id': 'process_industry',
  'label': 'Process Industry',
  'recommended_technologies': ['hart',
                               'wirelesshart',
                               'foundation_fieldbus_h1',
                               'profibus_pa',
                               'modbus_tcp',
                               'modbus_rtu',
                               'ethernet_ip',
                               'profinet',
                               'opc_ua']},
 {'device_types': ['EmbeddedController', 'Sensor', 'Actuator', 'Peripheral', 'Gateway'],
  'id': 'embedded_systems',
  'label': 'Embedded / Electronics'},
 {'device_types': ['EdgeComputer', 'IoTDevice', 'Gateway', 'Sensor', 'Actuator'],
  'id': 'iot_wireless',
  'label': 'IoT / Edge / Wireless'},
 {'device_types': ['CustomDevice', 'Gateway', 'Sensor', 'Actuator'],
  'id': 'custom',
  'label': 'Custom / Proprietary'})
