"""UART framing and device-specific clocks; electrical links are separate."""
from backend.nis.communication.services.native_review_support import declaration, fields as build_fields, WIRE_KEYS
PIC='https://ww1.microchip.com/downloads/en/DeviceDoc/70232B.pdf'
LPC='https://www.nxp.com/docs/en/user-guide/UM10237.pdf'
SOURCES={PIC:'Microchip PIC24H DS70232B 2008 chapter17: reset framing,8/9-bit,parity,1/2 stop,16/4 clock,16-bit BRG,FIFO/status/55h autobaud. Device-dependent clock and electrical link, not universal115200.',LPC:'NXP LPC24xx UM10237 Rev04 26August2009 chapters16/17:5..8 bits,1/1.5/2 stop,stick parity,DL divisor and fractional divider constraints,UART1 hardware flow versus UART0/2/3,actual baud and error states.'}
DECLARATIONS=[]
def d(k,t,meaning,source=PIC,**kw):DECLARATIONS.append(declaration('ua_',k,t,meaning,source,SOURCES[source],**kw))
for k,meaning,opts,src in [
 ('review_profile','Source identified UART hardware or independently qualified implementation.',['PIC24H_DS70232B','LPC24XX_UM10237_4','REGISTERED_ACTUAL'],PIC),('proposal_mode','Register reset proposals are not confirmed active device configuration.',['SOURCE_BASELINE','ACTUAL_CONFIG'],PIC),('mode','Actual asynchronous start/stop versus independently qualified synchronous USART or extension.',['ASYNC_UART','SYNC_USART','REGISTERED_ACTUAL'],PIC),('direction','Actual independent Tx/Rx or bound half-duplex direction.',['TX','RX','FULL_DUPLEX','HALF_DUPLEX'],PIC),('parity','Actual parity, stick parity only source supported hardware.',['NONE','EVEN','ODD','MARK','SPACE'],LPC),('peer_parity','Actual remote framing selection, separately verified.',['NONE','EVEN','ODD','MARK','SPACE'],LPC),('bit_order','Actual serialized data order. Reviewed UART profiles LSB first.',['LSB_FIRST','MSB_FIRST','REGISTERED_ACTUAL'],PIC),('flow','Actual CTS/RTS or software blocking, not assumed unlimited bandwidth.',['NONE','RTS_CTS','XON_XOFF','REGISTERED_ACTUAL'],PIC),('autobaud','Actual disabled/armed/complete/failed measurement; examples are not active baud.',['DISABLED','ARMED','COMPLETE','FAILED'],PIC),('polarity','Actual TTL-side idle polarity, not RS232 external voltage sign.',['IDLE_HIGH','IDLE_LOW','REGISTERED_ACTUAL'],PIC),('outcome','Actual correlated decoded character/application result.',['ACCEPTED','PARITY_ERROR','FRAMING_ERROR','OVERRUN','BREAK','FLOW_BLOCKED','UNKNOWN'],PIC),
]:d(k,'select',meaning,source=src,options=opts)
for k,meaning,lo,hi,unit,integer,src in [
 ('baud','Actual wire symbols/s; binary UART one bit/symbol, no universally mandated baud.',0,None,'Bd',False,PIC),('peer_baud','Actual remote wire symbols/s, distinct oscillator/divider.',0,None,'Bd',False,PIC),('target_baud','Actual commissioned target baud for divider error calculation.',0,None,'Bd',False,PIC),('clock_hz','Actual PIC FCY=FOSC/2 or LPC PCLK input, not CPU oscillator substituted.',0,None,'Hz',False,PIC),('oversampling','Actual PIC16 or4 sampling divider; LPC fixed16.',1,None,None,True,PIC),('brg','Actual PIC24H 16-bit UxBRG; zero legal max rate, not0baud.',0,65535,None,True,PIC),('dll','Actual LPC divisor low register.',0,255,None,True,LPC),('dlm','Actual LPC divisor high register.',0,255,None,True,LPC),('divisor','Actual LPC nonzero 16-bit divisor=(DLM*256)+DLL.',1,65535,None,True,LPC),('divaddval','Actual LPC fractional addition numerator.',0,14,None,True,LPC),('mulval','Actual LPC fractional multiplier denominator.',1,15,None,True,LPC),('port','Actual selected UART0/1/2/3, hardware CTS/RTS only UART1 LPC24xx.',0,3,None,True,LPC),
 ('data_bits','Actual payload data bits; parity not included here.',1,None,'bit',True,PIC),('peer_data_bits','Actual peer payload data bits.',1,None,'bit',True,PIC),('start_bits','Actual occupied start periods, reviewed hardware1.',0,None,'bit-period',True,PIC),('stop_bits','Actual occupied stop periods; LPC5-bit long stop1.5, otherwise2.',0,None,'bit-period',False,LPC),('peer_stop_bits','Actual peer framing stop periods.',0,None,'bit-period',False,LPC),('parity_bits','Actual parity overhead0none/1enabled, not another data bit.',0,1,'bit',True,PIC),('character_bits','Actual start+data+parity+stop occupied bit periods.',0,None,'bit-period',False,PIC),('characters','Actual encoded character count, not arbitrary API write chunk octets.',0,None,'character',True,PIC),('wire_bits','Actual encoded characters times occupied character periods.',0,None,'bit-period',False,PIC),('serialization_us','Actual wire bit-periods / actual baud, excluding idle and blocked flow.',0,None,'us',False,PIC),('idle_us','Actual aggregate bounded intercharacter/application gaps.',0,None,'us',False,PIC),('flow_block_us','Actual bounded CTS/software flow stalls; unbounded peer has no guaranteed completion.',0,None,'us',False,PIC),('transfer_us','Actual complete serial transfer bound including gaps and blocking.',0,None,'us',False,PIC),('rx_fifo','Actual available receive characters PIC4/LPC16, not software buffer bytes.',1,None,'character',True,PIC),('tx_fifo','Actual available transmit FIFO characters excluding shift register.',1,None,'character',True,PIC),('rx_occupancy','Actual unread hardware FIFO characters at observation.',0,None,'character',True,PIC),('arrival_characters','Actual additional chars arriving before service.',0,None,'character',True,PIC),('service_capacity','Actual chars removed during service envelope.',0,None,'character',True,PIC),('post_occupancy','Actual post-service FIFO occupancy for specified ordering, not universal schedulability.',0,None,'character',True,PIC),('baud_error_percent','Actual signed (baud-target)/target*100, no universal1.1/10percent tolerance.',None,None,'%',False,PIC),('peer_error_percent','Actual bounded oscillator+divider deviation magnitude of peer.',0,None,'%',False,PIC),('local_error_percent','Actual bounded local oscillator+divider deviation magnitude.',0,None,'%',False,PIC),('combined_error_percent','Actual sum of worst magnitudes under qualified independent error model.',0,None,'%',False,PIC),('receiver_tolerance_percent','Actual device/mode-dependent verified receive sampling tolerance.',0,None,'%',False,PIC),('autobaud_sync','Actual sync character PIC55h versus LPC AT A/a protocol.',0,255,None,True,PIC),
 ('source_ms','Actual producer/encode/host queue bound.',0,None,'ms',False,PIC),('path_ms','Actual PHY/transfer and driver delivery bound.',0,None,'ms',False,PIC),('consumer_ms','Actual decoder/use/service bound.',0,None,'ms',False,PIC),('e2e_ms','Actual complete source+path+consumer bound.',0,None,'ms',False,PIC),('deadline_ms','Actual independent functional deadline.',0,None,'ms',False,PIC),('age_ms','Actual correlated data age at use.',0,None,'ms',False,PIC),('freshness_ms','Actual acceptable application data age.',0,None,'ms',False,PIC),
]:d(k,'number',meaning,source=src,min=lo,max=hi,unit=unit,integer=integer)
for k,meaning in [('enabled','Actual UART and transmitter enabled; reset disabled is not productive interface.'),('rx_enabled','Actual receiver active, separately from Tx.'),('peer_verified','Actual matching baud/framing/polarity/flow and decoder on both endpoints.'),('fifo_verified','Actual worst FIFO service/interrupt/DMA capacity and no lost chars.'),('phy_verified','Actual electrical driver/voltage/cable/termination/ground and direction path.'),('data_accepted','Actual fresh decoded dataset consumed under independent requirement.')]:d(k,'boolean',meaning)
for k,meaning,src in [('revision','Actual hardware/controller/revision/driver edition.',PIC),('configuration_source','Actual both endpoints baud/framing/flow/polarity settings.',PIC),('clock_source','Actual input-clock selection, oscillator and baud-divider register proof.',PIC),('phy_source','Actual TTL/RS232/RS422/RS485/bridge electrical binding, no UART electrical universal.',PIC),('codec_source','Actual application encoding/boundaries/escaping/endianness, not write chunk.',PIC),('acceptance_source','Actual application deadline/freshness/error handling.',PIC),('registered_source','Actual independently qualified controller/USART mode.',PIC),('flow_source','Actual bounded peer flow-control behavior.',PIC),('error_source','Actual receiver oversampling/clock tolerance and worst oscillator uncertainty.',PIC),('fifo_source','Actual interrupt/DMA/service/preempting task envelope.',LPC),('observation_source','Actual correlated character/application trace including error status.',PIC),('autobaud_source','Actual completed sync measurement or qualified startup timeout.',PIC)]:d(k,'text',meaning,source=src)
REQUIRED=('review_profile','revision','mode','configuration_source','clock_source','phy_source','codec_source','acceptance_source')
REMOVED={k:'UART hardware clock/framing and actual electrical path replace foreign fixed115200/CANretry/gateway fields. No universal65535 byte message limit.'for k in WIRE_KEYS}
def semantics():
 rules=[]
 def r(k,w=None,src=PIC,**kw):rules.append(dict(parameter='ua_'+k,when={'ua_'+a:b for a,b in(w or{}).items()},source=src,**kw))
 rules.extend(dict(parameter=k,when={},allowed=[],source=PIC)for k in REMOVED)
 r('registered_source',{'review_profile':'REGISTERED_ACTUAL'},required=True)
 for mode in('SYNC_USART','REGISTERED_ACTUAL'):r('registered_source',{'mode':mode},required=True)
 r('mode',{'review_profile':'PIC24H_DS70232B'},allowed=['ASYNC_UART']);r('mode',{'review_profile':'LPC24XX_UM10237_4'},allowed=['ASYNC_UART'],src=LPC)
 for profile,bits,parity,stop,oversample,src in [('PIC24H_DS70232B',[8,9],['NONE','EVEN','ODD'],[1,2],[4,16],PIC),('LPC24XX_UM10237_4',[5,6,7,8],['NONE','EVEN','ODD','MARK','SPACE'],[1,1.5,2],[16],LPC)]:
  for k,opts in [('data_bits',bits),('parity',parity),('stop_bits',stop),('oversampling',oversample),('start_bits',[1]),('bit_order',['LSB_FIRST'])]:r(k,{'review_profile':profile},allowed=opts,src=src)
  for k in('baud','data_bits','start_bits','stop_bits','parity','direction','flow'):r(k,{'review_profile':profile},required=True,src=src)
  r('baud',{'review_profile':profile},exclusive_minimum=0,src=src)
 r('parity',{'review_profile':'PIC24H_DS70232B','data_bits':9},allowed=['NONE'])
 r('stop_bits',{'review_profile':'LPC24XX_UM10237_4','data_bits':5},allowed=[1,1.5],src=LPC)
 r('stop_bits',{'review_profile':'LPC24XX_UM10237_4'},when_ranges={'ua_data_bits':[6,8]},allowed=[1,2],src=LPC)
 r('baud',{'review_profile':'PIC24H_DS70232B'},equal_ratio={'numerator_parameter':'ua_clock_hz','denominator_sum':['ua_brg'],'denominator_offset':1,'denominator_product':['ua_oversampling']})
 r('divisor',{'review_profile':'LPC24XX_UM10237_4'},equal_expression={'sum':[{'product':[256,'ua_dlm']},'ua_dll']},src=LPC)
 r('divaddval',{'review_profile':'LPC24XX_UM10237_4'},exclusive_maximum_expression='ua_mulval',src=LPC)
 r('dll',{'review_profile':'LPC24XX_UM10237_4','dlm':0},when_greater_than={'ua_divaddval':0},minimum=3,src=LPC)
 r('baud',{'review_profile':'LPC24XX_UM10237_4'},equal_ratio={'numerator_parameter':'ua_clock_hz','numerator_product':['ua_mulval'],'denominator_sum':['ua_mulval','ua_divaddval'],'denominator_product':['ua_divisor'],'factor':1/16},src=LPC)
 r('port',{'review_profile':'LPC24XX_UM10237_4','flow':'RTS_CTS'},required=True,allowed=[1],src=LPC)
 r('rx_fifo',{'review_profile':'PIC24H_DS70232B'},maximum=4);r('tx_fifo',{'review_profile':'PIC24H_DS70232B'},maximum=4)
 r('rx_fifo',{'review_profile':'LPC24XX_UM10237_4'},maximum=16,src=LPC);r('tx_fifo',{'review_profile':'LPC24XX_UM10237_4'},maximum=16,src=LPC)
 r('parity_bits',{'parity':'NONE'},allowed=[0]);r('parity_bits',when_present=['ua_parity'],when_not={'ua_parity':'NONE'},allowed=[1])
 r('character_bits',equal_expression={'sum':['ua_start_bits','ua_data_bits','ua_parity_bits','ua_stop_bits']})
 r('wire_bits',equal_expression={'product':['ua_characters','ua_character_bits']})
 r('serialization_us',equal_ratio={'numerator_parameter':'ua_wire_bits','denominator_parameter':'ua_baud','factor':1000000})
 r('transfer_us',minimum_expression={'sum':['ua_serialization_us','ua_idle_us','ua_flow_block_us']})
 # Signed error identity avoids division/rounding of a nominal register example.
 r('baud',when_present=['ua_baud_error_percent','ua_target_baud'],equal_expression={'product':['ua_target_baud',{'sum':[1,{'product':[.01,'ua_baud_error_percent']}]}]})
 r('combined_error_percent',equal_expression={'sum':['ua_local_error_percent','ua_peer_error_percent']},maximum_parameter='ua_receiver_tolerance_percent')
 r('rx_occupancy',maximum_parameter='ua_rx_fifo');r('post_occupancy',maximum_parameter='ua_rx_fifo',equal_expression={'maximum':[0,{'subtract':[{'sum':['ua_rx_occupancy','ua_arrival_characters']},'ua_service_capacity']}]})
 for k,peer in [('data_bits','peer_data_bits'),('parity','peer_parity'),('stop_bits','peer_stop_bits')]:r(k,{'peer_verified':True},equal_parameter='ua_'+peer);r(peer,{'peer_verified':True},required=True)
 r('error_source',{'peer_verified':True},required=True);r('combined_error_percent',{'peer_verified':True},required=True);r('receiver_tolerance_percent',{'peer_verified':True},required=True)
 for flow in('RTS_CTS','XON_XOFF','REGISTERED_ACTUAL'):
  for k in('flow_source','flow_block_us'):r(k,{'flow':flow},when_present=['ua_transfer_us'],required=True)
 r('autobaud_sync',{'review_profile':'PIC24H_DS70232B','autobaud':'COMPLETE'},required=True,allowed=[85]);r('autobaud_sync',{'review_profile':'LPC24XX_UM10237_4','autobaud':'COMPLETE'},required=True,allowed=[65,97],src=LPC)
 r('autobaud_source',{'autobaud':'COMPLETE'},required=True)
 r('e2e_ms',equal_expression={'sum':['ua_source_ms','ua_path_ms','ua_consumer_ms']},maximum_parameter='ua_deadline_ms');r('age_ms',maximum_parameter='ua_freshness_ms')
 for k in('source_ms','path_ms','consumer_ms'):r(k,when_present=['ua_e2e_ms'],required=True)
 for k in('observation_source','fifo_source','error_source','e2e_ms','deadline_ms','age_ms','freshness_ms'):r(k,{'data_accepted':True},required=True)
 for k,v in [('enabled',True),('peer_verified',True),('fifo_verified',True),('phy_verified',True),('outcome','ACCEPTED')]:r(k,{'data_accepted':True},required=True,allowed=[v])
 return dict(rate_model={'type':'EXPLICIT_UART_DEVICE_CLOCK','fields':[]},parameter_evidence_scope='EXPLICIT_LAYER',required_parameters=['ua_'+k for k in REQUIRED],native_parameter_prefixes=['ua_'],parameter_constraints=rules,medium_access_model='ACTUAL_UART_DIRECTION_AND_FLOW',arbitration_model_id='ACTUAL_UART_PHY_AND_PEER',mechanisms={'network':['UART_START_STOP_NOT_RS232_VOLTAGE','USART_SYNC_REQUIRES_REGISTERED_PATH'],'timing':['DEVICE_DIVIDER_AND_PEER_ERROR','FIFO_FLOW_AND_APPLICATION_ACCEPTANCE']})
def fields():
 proposals={}
 for profile,values,src in [('PIC24H_DS70232B',{'data_bits':8,'start_bits':1,'stop_bits':1,'parity':'NONE','bit_order':'LSB_FIRST','oversampling':16},PIC),('LPC24XX_UM10237_4',{'data_bits':5,'start_bits':1,'stop_bits':1,'parity':'NONE','bit_order':'LSB_FIRST','divaddval':0,'mulval':1,'oversampling':16},LPC)]:
  for k,v in values.items():proposals.setdefault('ua_'+k,[]).append(dict(when={'ua_review_profile':profile,'ua_proposal_mode':'SOURCE_BASELINE'},value=v,source=src,source_revision=SOURCES[src]))
 return build_fields(DECLARATIONS,['ua_'+k for k in REQUIRED],proposals)
