import type { IndustrySensorTemplate, IndustryTemplateProfile } from "./types.ts";

const positionalFamilies = [
  { name: "WheelSpeed", signal: "Raddrehzahl", unit: "rpm", min: 0, max: 2500, factor: 1, cycle: 5 },
  { name: "TirePressure", signal: "Reifendruck", unit: "kPa", min: 0, max: 500, factor: 1, cycle: 100 },
  { name: "TireTemperature", signal: "Reifentemperatur", unit: "degC", min: -40, max: 180, factor: 0.1, cycle: 100 },
  { name: "BrakeTemperature", signal: "Bremstemperatur", unit: "degC", min: -40, max: 900, factor: 0.5, cycle: 50 },
  { name: "SuspensionTravel", signal: "Federweg", unit: "mm", min: -150, max: 150, factor: 0.1, cycle: 10 },
  { name: "WheelLoad", signal: "Radlast", unit: "N", min: 0, max: 15000, factor: 1, cycle: 10 },
  { name: "DamperPosition", signal: "Daempferposition", unit: "%", min: 0, max: 100, factor: 0.1, cycle: 10 },
  { name: "WheelAcceleration", signal: "Radbeschleunigung", unit: "m/s2", min: -100, max: 100, factor: 0.01, cycle: 5 },
  { name: "BrakePressure", signal: "Bremsdruck", unit: "bar", min: 0, max: 250, factor: 0.1, cycle: 5 },
  { name: "WheelTorque", signal: "Raddrehmoment", unit: "Nm", min: -5000, max: 5000, factor: 1, cycle: 5 },
  { name: "WheelAngle", signal: "Radwinkel", unit: "deg", min: -60, max: 60, factor: 0.01, cycle: 10 },
  { name: "TireWear", signal: "Reifenverschleiss", unit: "mm", min: 0, max: 12, factor: 0.01, cycle: 1000 },
] as const;

const positions = [
  ["FrontLeft", "VorneLinks"],
  ["FrontRight", "VorneRechts"],
  ["RearLeft", "HintenLinks"],
  ["RearRight", "HintenRechts"],
] as const;

const positionalSensors: IndustrySensorTemplate[] = positionalFamilies.flatMap((family) => positions.map(([name, signal]) => ({
  cycleMs: family.cycle,
  factor: family.factor,
  hardwareName: `${name}${family.name}Sensor`,
  interfaceType: family.cycle >= 100 ? "LIN" : "CAN_FD",
  maxValue: family.max,
  minValue: family.min,
  signalName: `${family.signal}${signal}`,
  unit: family.unit,
})));

const centralSensors: IndustrySensorTemplate[] = [
  ["CoolantTemperatureSensor", "Kuehlmitteltemperatur", "CAN_FD", "degC", -40, 150, 0.1, 20],
  ["OilTemperatureSensor", "Oeltemperatur", "CAN_FD", "degC", -40, 180, 0.1, 20],
  ["IntakeAirTemperatureSensor", "Ansauglufttemperatur", "CAN_FD", "degC", -40, 120, 0.1, 20],
  ["ExhaustGasTemperatureSensor", "Abgastemperatur", "CAN_FD", "degC", 0, 1100, 1, 10],
  ["CabinTemperatureSensor", "Innenraumtemperatur", "CAN_FD", "degC", -40, 85, 0.1, 100],
  ["AmbientTemperatureSensor", "Aussentemperatur", "LIN", "degC", -50, 85, 0.1, 500],
  ["BatteryTemperatureSensor", "Batterietemperatur", "CAN_FD", "degC", -40, 100, 0.1, 50],
  ["InverterTemperatureSensor", "Invertertemperatur", "CAN_FD", "degC", -40, 180, 0.1, 20],
  ["MotorTemperatureSensor", "Motortemperatur", "CAN_FD", "degC", -40, 200, 0.1, 20],
  ["TransmissionOilTemperatureSensor", "Getriebeoeltemperatur", "CAN_FD", "degC", -40, 180, 0.1, 50],
  ["EngineSpeedSensor", "Motordrehzahl", "CAN_FD", "rpm", 0, 9000, 1, 5],
  ["MotorSpeedSensor", "Elektromotordrehzahl", "CAN_FD", "rpm", -20000, 20000, 1, 5],
  ["TransmissionInputSpeedSensor", "Getriebeeingangsdrehzahl", "CAN_FD", "rpm", 0, 12000, 1, 5],
  ["TransmissionOutputSpeedSensor", "Getriebeausgangsdrehzahl", "CAN_FD", "rpm", 0, 12000, 1, 5],
  ["TurboSpeedSensor", "Turboladerdrehzahl", "CAN_FD", "rpm", 0, 250000, 10, 10],
  ["EngineOilPressureSensor", "Motoroeldruck", "CAN_FD", "bar", 0, 12, 0.01, 10],
  ["FuelPressureSensor", "Kraftstoffdruck", "CAN_FD", "bar", 0, 2500, 0.1, 10],
  ["BoostPressureSensor", "Ladedruck", "CAN_FD", "kPa", 0, 400, 0.1, 10],
  ["RefrigerantPressureSensor", "Kaeltemitteldruck", "LIN", "bar", 0, 40, 0.01, 100],
  ["BatteryCoolantPressureSensor", "Batteriekuehldruck", "LIN", "bar", 0, 10, 0.01, 100],
  ["BatteryCurrentSensor", "Batteriestrom", "CAN_FD", "A", -1000, 1000, 0.1, 10],
  ["MotorCurrentSensor", "Motorstrom", "CAN_FD", "A", -1500, 1500, 0.1, 5],
  ["AlternatorCurrentSensor", "Generatorstrom", "CAN_FD", "A", -300, 300, 0.1, 50],
  ["AccessoryCurrentSensor", "Nebenverbraucherstrom", "LIN", "A", 0, 300, 0.1, 100],
  ["BatteryVoltageSensor", "Batteriespannung", "CAN_FD", "V", 0, 1000, 0.1, 10],
  ["DCLinkVoltageSensor", "Zwischenkreisspannung", "CAN_FD", "V", 0, 1200, 0.1, 5],
  ["LowVoltageSupplySensor", "Bordnetzspannung", "LIN", "V", 0, 32, 0.01, 100],
  ["CellVoltageMinSensor", "MinimaleZellspannung", "CAN_FD", "V", 0, 5, 0.001, 50],
  ["CellVoltageMaxSensor", "MaximaleZellspannung", "CAN_FD", "V", 0, 5, 0.001, 50],
  ["SteeringAngleSensor", "Lenkwinkel", "CAN_FD", "deg", -720, 720, 0.1, 5],
  ["SteeringTorqueSensor", "Lenkmoment", "CAN_FD", "Nm", -30, 30, 0.01, 5],
  ["AcceleratorPositionSensor", "Fahrpedalstellung", "CAN_FD", "%", 0, 100, 0.1, 10],
  ["BrakePedalPositionSensor", "Bremspedalstellung", "CAN_FD", "%", 0, 100, 0.1, 10],
  ["ClutchPositionSensor", "Kupplungsstellung", "CAN_FD", "%", 0, 100, 0.1, 20],
  ["GearSelectorPositionSensor", "Gangwahlstellung", "CAN_FD", "code", 0, 15, 1, 50],
  ["ThrottlePositionSensor", "Drosselklappenstellung", "CAN_FD", "%", 0, 100, 0.1, 10],
  ["EGRValvePositionSensor", "AGRVentilstellung", "CAN_FD", "%", 0, 100, 0.1, 20],
  ["LongitudinalAccelerationSensor", "Laengsbeschleunigung", "CAN_FD", "m/s2", -30, 30, 0.01, 5],
  ["LateralAccelerationSensor", "Querbeschleunigung", "CAN_FD", "m/s2", -30, 30, 0.01, 5],
  ["VerticalAccelerationSensor", "Vertikalbeschleunigung", "CAN_FD", "m/s2", -30, 30, 0.01, 5],
  ["YawRateSensor", "Gierrate", "CAN_FD", "deg/s", -300, 300, 0.01, 5],
  ["PitchRateSensor", "Nickrate", "CAN_FD", "deg/s", -300, 300, 0.01, 5],
  ["RollRateSensor", "Rollrate", "CAN_FD", "deg/s", -300, 300, 0.01, 5],
  ["FuelLevelSensor", "Kraftstofffuellstand", "LIN", "%", 0, 100, 0.1, 500],
  ["UreaLevelSensor", "Harnstofffuellstand", "LIN", "%", 0, 100, 0.1, 500],
  ["WasherFluidLevelSensor", "Waschwasserfuellstand", "LIN", "%", 0, 100, 0.1, 1000],
  ["CoolantLevelSensor", "Kuehlmittelfuellstand", "LIN", "%", 0, 100, 0.1, 500],
  ["OilLevelSensor", "Oelfuellstand", "LIN", "%", 0, 100, 0.1, 500],
  ["FrontRadarDistanceSensor", "Frontabstand", "Ethernet", "m", 0, 300, 0.1, 20],
  ["RearRadarDistanceSensor", "Heckabstand", "Ethernet", "m", 0, 200, 0.1, 20],
  ["RainSensor", "Regenintensitaet", "LIN", "%", 0, 100, 0.1, 100],
  ["AmbientLightSensor", "Umgebungshelligkeit", "LIN", "lx", 0, 150000, 1, 200],
].map(([hardwareName, signalName, interfaceType, unit, minValue, maxValue, factor, cycleMs]) => ({
  cycleMs: Number(cycleMs),
  factor: Number(factor),
  hardwareName: String(hardwareName),
  interfaceType: String(interfaceType),
  maxValue: Number(maxValue),
  minValue: Number(minValue),
  signalName: String(signalName),
  unit: String(unit),
}));

export const automotiveTemplateProfile: IndustryTemplateProfile = {
  gatewayName: "System-Gateway",
  id: "automotive",
  ignoredSystemNames: ["Funktion", "Funktions", "Funktions-ECU", "Funktions-ECUs"],
  label: "Automotive",
  sensorTemplates: [...positionalSensors, ...centralSensors],
  systemAliases: {
    "Motion": "Motorsteuerung",
    "Antrieb": "Motorsteuerung",
    "Antriebs": "Motorsteuerung",
    "Motion Antriebs": "Motorsteuerung",
    "Motor": "Motorsteuerung",
    "Getriebe": "Getriebesteuerung",
    "Lenkungs": "Lenkung",
    "Klima": "Klimatisierung",
    "Thermal": "Thermomanagement",
  },
  systemVariants: [
    "Kuehlkreislaufsteuerung",
    "Drehmomentkoordination",
    "Batteriemanagement",
    "Motorsteuerung",
    "Getriebesteuerung",
    "Bremsregelung",
    "Lenkung",
    "Fahrwerk",
    "Klimatisierung",
    "BodyControl",
    "Fahrertuer",
    "Beifahrertuer",
    "FondtuerLinks",
    "FondtuerRechts",
    "Fahrersitz",
    "Beifahrersitz",
    "Aussenlicht",
    "Innenlicht",
    "Airbag",
    "Kombiinstrument",
    "Infotainment",
    "Telematik",
    "Diagnose",
    "Fahrerassistenz",
    "Energieversorgung",
    "Ladesteuerung",
    "Invertersteuerung",
    "Elektromotorsteuerung",
    "Thermomanagement",
    "Kraftstoffsystem",
    "Abgasnachbehandlung",
    "Daempferregelung",
    "Stabilitaetsregelung",
    "Reifendruckkontrolle",
    "Parkassistenz",
    "Radarverarbeitung",
    "Kameraverarbeitung",
    "Ultraschallverarbeitung",
    "Bordnetzmanagement",
    "Konnektivitaet",
    "Wegfahrsperre",
    "KeylessEntry",
    "Wischersteuerung",
    "Schiebedach",
    "Heckklappe",
    "Anhaengersteuerung",
    "Hinterachslenkung",
    "Allradsteuerung",
    "Soundsystem",
    "HeadUpDisplay",
  ],
};
