#!/usr/bin/env python3
"""Generate all dependency-free sample formats in one run."""

from __future__ import annotations

import argparse
from pathlib import Path

from can_format_writers import (
    write_arxml,
    write_asc,
    write_csv_trace,
    write_dbc,
    write_fibex,
    write_json_trace,
    write_log,
    write_trc,
    write_txt,
    write_xml_trace,
    write_yaml_trace,
)
from common_trace import build_can_trace, build_ethernet_trace, load_routing_table, write_routing_template
from eth_format_writers import write_pcap, write_pcapng


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate all dependency-free CAN and Ethernet demo formats")
    parser.add_argument("--out-dir", default="generated_formats")
    parser.add_argument("--duration", type=float, default=1.0)
    parser.add_argument("--messages", type=int, default=10)
    parser.add_argument("--channels", type=int, choices=range(1, 17), default=2, metavar="1-16")
    parser.add_argument("--routing-table", type=Path, default=None)
    parser.add_argument("--write-routing-template", type=Path, default=None)
    parser.add_argument("--bus", choices=["classic", "fd", "xl"], default="fd")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--nominal-bitrate", type=int, default=500_000)
    parser.add_argument("--data-bitrate", type=int, default=500_000)
    args = parser.parse_args()
    if args.write_routing_template:
        write_routing_template(args.write_routing_template)
        print(f"Wrote routing template to {args.write_routing_template}")
        return

    out_dir = Path(args.out_dir)
    routing_rows = load_routing_table(args.routing_table, args.channels) if args.routing_table else None
    message_count = len(routing_rows) if routing_rows is not None and args.messages == 10 else args.messages
    messages, frames = build_can_trace(args.duration, message_count, args.channels, args.bus, args.seed, routing_rows=routing_rows)
    eth_frames = build_ethernet_trace(args.duration, args.messages, args.seed)

    write_dbc(out_dir / "network.dbc", messages, args.nominal_bitrate, args.data_bitrate)
    write_asc(out_dir / "trace.asc", frames)
    write_trc(out_dir / "trace.trc", frames)
    write_csv_trace(out_dir / "trace.csv", frames)
    write_json_trace(out_dir / "trace.json", frames)
    write_log(out_dir / "trace.log", frames)
    write_txt(out_dir / "trace.txt", frames)
    write_xml_trace(out_dir / "trace.xml", frames)
    write_yaml_trace(out_dir / "trace.yaml", frames)
    write_yaml_trace(out_dir / "trace.yml", frames)
    write_arxml(out_dir / "system.arxml", messages)
    write_fibex(out_dir / "system.fibex.xml", messages)
    write_pcap(out_dir / "someip.pcap", eth_frames)
    write_pcapng(out_dir / "someip.pcapng", eth_frames)

    print(f"Wrote dependency-free generated formats to {out_dir.resolve()}")
    print("BLF is generated by generate_can_blf.py; MDF/MF4 require asammdf and use generate_can_mdf.py/generate_can_mf4.py.")


if __name__ == "__main__":
    main()
