"""FSoE base declarations, qualified sources, and explicit review limits."""
import json
from pathlib import Path
SOURCE='https://www.beckhoff.com/media/downloads/information-media/pc-control/pcc_0107_e.pdf'
REVISION='Beckhoff PC-Control01/2007 pages24-26; HMS public FSoE PDU/state tutorial July23/24 2026 interpreted for base ETG5100v1.2.0, not licensed full text'
declarations=[
 ('fsoe_profile','select',None,['BASE_5100_1_2','ENHANCEMENTS_5120','DEVICE_SPECIFIC'],None,None,'BASE_5100_1_2','Source-qualified base declaration proposal; ETG5120 enhancements require independent matched edition/implementation bounds.'),
 ('fsoe_role','select',None,['MASTER','SLAVE'],None,None,None,'Actual safety protocol instance role; EtherCAT main-device/subdevice roles are independent.'),
 ('fsoe_transport_binding','text',None,None,None,None,None,'Required actual black-channel link/process-data/buffer mapping reference; no implicit EtherCAT100M/Ethernet inherited rate.'),
 ('fsoe_implementation_source','text',None,None,None,None,None,'Required matched actual safety device/firmware/protocol edition and supported data limits reference, unknown.'),
 ('fsoe_connection_source','text',None,None,None,None,None,'Required actual unique connection ID/slave address/parameter/configuration reference, unknown.'),
 ('fsoe_timing_source','text',None,None,None,None,None,'Required actual direction-dependent watchdog/whole exchange/transport mapping bounds and endpoint timing reference, unknown.'),
 ('fsoe_direction','select',None,['MASTER_TO_SLAVE','SLAVE_TO_MASTER'],None,None,None,'Actual safe-data direction. Configured input/output lengths may differ; never duplicate one length into both.'),
 ('fsoe_master_safe_bytes','number','Byte',None,1,None,None,'Actual master-to-slave safe-data capacity, unknown. One byte or even count; bounded by actual device/process-data mapping.'),
 ('fsoe_slave_safe_bytes','number','Byte',None,1,None,None,'Actual slave-to-master safe-data capacity, unknown, independent of master direction. No universal1486-byte maximum.'),
 ('fsoe_crc_count','number',None,None,1,None,None,'Actual CRC word count=ceil(selected safe bytes/2). One-byte exception uses virtual zero in CRC calculation, not an extra wire payload byte.'),
 ('fsoe_crc_word_bytes','number','Byte',None,2,2,2,'Baseline two-octet CRC field per block; not a single checksum overhead for all safe data.'),
 ('fsoe_command_bytes','number','Byte',None,1,1,1,'Baseline one command octet; not an EtherCAT datagram header.'),
 ('fsoe_connection_bytes','number','Byte',None,2,2,2,'Baseline two ConnID octets at end of PDU; connection identifier differs from safety slave address.'),
 ('fsoe_frame_bytes','number','Byte',None,6,None,None,'Actual safety container CMD+safe data+2*CRCcount+ConnID. Six-byte minimum corresponds to one safe byte; excludes black-channel framing.'),
 ('fsoe_pdo_capacity_bytes','number','Byte',None,6,None,None,'Actual mapped black-channel process-data container capacity; full FSoE frame must fit, not just safe payload.'),
 ('fsoe_state','select',None,['RESET','SESSION','CONNECTION','PARAMETER','DATA'],None,None,None,'Actual protocol state, unknown. Saved state declaration does not execute handshake or release safe outputs.'),
 ('fsoe_data_command','select',None,['PROCESS_DATA','FAILSAFE_DATA'],None,None,None,'Actual outgoing data-state command, unknown. Independent peer command is not inferred; no auto ProcessData release.'),
 ('fsoe_command','number',None,None,0,255,None,'Actual wire command octet. Public base Reset0x2A/Data Process0x36/FailSafe0x08 constraints; remaining startup command encoding requires source.'),
 ('fsoe_conn_id','number',None,None,0,65535,None,'Actual16-bit ConnID unknown. Zero before connection allocation/reset; Data requires nonzero. Uniqueness requires actual network configuration.'),
 ('fsoe_slave_address','number',None,None,1,65535,None,'Actual configured16-bit safety slave address, unknown; must match endpoint setting. Distinct from EtherCAT address and ConnID.'),
 ('fsoe_peer_address','number',None,None,1,65535,None,'Actual peer accepted/configured safety slave address, unknown, must equal selected endpoint address; scalar equality is not commissioning evidence.'),
 ('fsoe_session_id','number',None,None,0,65535,None,'Actual locally generated16-bit session ID, unknown. Not default0, not an on-wire field in every Data PDU.'),
 ('fsoe_peer_session_id','number',None,None,0,65535,None,'Actual independently generated peer session ID, unknown. Not forced equal to local session or copied from it.'),
 ('fsoe_sequence','number',None,None,0,65535,None,'Actual internal virtual sequence, unknown; base Data1..65535, absent as a standalone wire field. Increment/rollover/CRC-change mechanism needs executor.'),
 ('fsoe_crc0','number',None,None,0,65535,None,'Actual current16-bit CRC0, unknown. Scalar bounds do not recompute CRC chain/virtual sequence/session/ConnID/block index.'),
 ('fsoe_previous_crc0','number',None,None,0,65535,None,'Actual previous received CRC0 in inherited chain, unknown. Not default0 outside actual reset.'),
 ('fsoe_crc_source','text',None,None,None,None,None,'Actual encoded/container/chain/sequence/session/block-index integrity evidence, unknown. Safety CRC is not cryptographic authentication.'),
 ('fsoe_master_watchdog_ms','number','ms',None,1,65535,None,'Actual base communication watchdog1..65535ms from matched configuration; no universal shortest1ms or sampled1000ms default.'),
 ('fsoe_slave_watchdog_ms','number','ms',None,1,65535,None,'Actual peer accepted same connection communication watchdog, independently sourced; setting alone is not a live watchdog or safety-response certificate.'),
 ('fsoe_exchange_bound_ms','number','ms',None,0.001,None,None,'Actual complete bidirectional exchange bound, unknown, must be below both configured watchdogs. Not a single EtherCAT frame cycle.'),
 ('fsoe_parameter_bytes','number','Byte',None,0,None,None,'Actual complete parameter-transfer stream bytes, unknown. Fragmented across frames if needed; not restricted to one frame or copied safe-data length.'),
 ('fsoe_parameter_remaining_bytes','number','Byte',None,0,None,None,'Actual remaining parameter stream count0..actual total, unknown. Counter alone does not certify accepted safety application parameters.'),
 ('fsoe_parameters_accepted','boolean',None,None,None,None,None,'Actual peer parameter acceptance unknown; Data requires true declaration, but protocol/runtime acceptance remains unexecuted.'),
 ('fsoe_mapping_source','text',None,None,None,None,None,'Actual ESI/PDO/black-channel buffering and direction/mapping version evidence, unknown; require verification after parameter changes.'),
 ('fsoe_safe_output_source','text',None,None,None,None,None,'Actual defined failure/output response and safety application configuration, unknown. Do not infer all-zero application safe state universally.'),
 ('fsoe_safety_requirement','select',None,['SIL1','SIL2','SIL3','PL_A','PL_B','PL_C','PL_D','PL_E','DEVICE_SPECIFIC'],None,None,None,'Actual project safety-integrity requirement, unknown. Protocol capability alone does not certify device/system SIL or PL.'),
 ('fsoe_assurance_source','text',None,None,None,None,None,'Actual matched safety-device/system validation/response/certificate reference, unknown. NIS declaration checks are not a safety certification.'),
]
removed={
 'bitrate':'Safety application protocol has no own physical rate; explicit registered black-channel binding supplies independent rate.',
 'qos_priority':'No universal priority3; safety transaction/black channel mechanism differ.',
 'reserved_bandwidth_percent':'Actual transport scheduling/resources rather than reservation0 guarantee.',
 'sync_method':'FSoE watchdog/CRC/sequence is distinct from Ethernet PTP/NTP/DC synchronization.',
 'retransmission_enabled':'No universal retry switch; state-specific Session retry cannot be generalized to Data.',
 'retransmission_rate':'No universal packet retry probability0.', 'retry_limit':'No universal Data retry0.',
 'retransmission_delay_ms':'No universal retry0ms; protocol state and actual watchdog govern exchange.',
 'gateway_maximum_throughput':'No universal100M safety gateway capacity; actual black-channel transport/queues require own profile.',
 'gateway_input_buffer':'No universal256-entry gateway buffer.','gateway_output_buffer':'No universal256-entry gateway buffer.',
 'gateway_maximum_routes':'No universal10000 gateway route capacity.','gateway_maximum_messages_s':'No universal100000 safety messages/s.',
 'queue_policy':'No generic FIFO certification; master/slave exchange and actual black-channel buffering are separately evidenced.',
 'queue_size':'No universal256 FSoE safety queue.',
 'mtu_bytes':'FSoE frame is a mapped safety container, not Ethernet MTU1500.',
 'duplex':'Black channel selected independently; no universal FULL Ethernet mode for FSoE.',
 'vlan_id':'No own Ethernet VLAN0; actual lower link has its own VLAN.',
 'rate_limit_bit_s':'No own network policer0; actual lower transport resources have their own fields.'}
native={key:meaning for key,_,_,_,_,_,_,meaning in declarations}
native['payload_bytes']='Actual selected-direction safe-data octets; base one byte or even positive count. No8-byte proposal or1486 universal maximum. PDO complete container capacity is separately checked.'
spec={'technology':'fsoe','native':native,'removed':removed,
 'sources':[SOURCE,'https://infosys.beckhoff.com/content/1033/tctwinsafe/11939173515.html',
 'https://www.hms-networks.cn/tech-blog/blogpost/hms-blog/2026/07/24/deep-dive-into-fsoe-part-4-how-the-6-byte-safety-pdu-achieves-sil3',
 'https://www.hms-networks.cn/tech-blog/blogpost/hms-blog/2026/07/24/deep-dive-into-fsoe-part-2-the-five-step-handshake-from-reset-to-data',
 'https://www.ethercat.org/en/downloads/downloads_E42C804F25A140149603A793EA42297E.htm'],
 'revisions':[REVISION,'Beckhoff TwinSAFE ST_FSoE_xxBytes copyright2022 API read2026-10-01',
 'ETG metadata ETG5100v1.2.0 March10 2011/ETG7100.2-2v1.5.0 Jan31 2025/ETG5120v1.4.0 August21 2026; member-only specifications not read'],
 'scope':'Every original field independently reviewed. Own explicit black-channel binding, qualified base container/CRC block/command/state/address/sequence/directional size/watchdog/parameter declarations typed and cross-checked; enhancements receive no foreign base-bound verification.',
 'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters + physical_profiles','passed':0},
 'not_certified':['Full licensed ETG5100/5101/5120/7100 and IEC61784-3-12 text/errata/conformance remain unavailable; public tutorial/API representation only',
 'CRC/sequence/session rollover/freshness, command handshake, per-direction parameter segmentation/acceptance and live watchdog executor missing',
 'Actual registered black-channel mapping/lower transport physical frame/schedule capacity/endpoint task and safety function response model; no SIL/PL/device certification inferred; MODEL_MISSING remains']}
(Path(__file__).parent/'fsoe-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
