"""Explicit CC-Link source decisions, separate from CC-Link IE and device proof."""
import json
from pathlib import Path

folder=Path(__file__).resolve().parent
ble=json.loads((folder/'bluetooth_le-review-decisions.json').read_text(encoding='utf-8'))
native={
 'bitrate':'CLPA listed156k/625k/2.5M/5M/10M.156000bit/s lowest listed proposal, not10M peak default or156250 inferred clock. Actual common speed and hardware support unknown.',
 'payload_bytes':'Actual logical application length unknown, no universal256byte cap. RX/RY bits and16bit registers are separate cyclic areas; not one HDLC frame or Ethernet MTU.',
 'ccl_protocol_version':'Registered1.10 baseline proposal versus2.00 with expanded cyclic areas. Actual installed stations/mode need confirmation; mixed devices must use compatible manager areas.',
 'ccl_cable_version':'Dedicated cable1.10 proposal or explicit1.00_STANDARD wiring rules. Three cores DA/DB/DG plus shield. Legacy1.00 high-performance130Ohm cable not this baseline, must remain separately unresolved.',
 'ccl_topology':'LINE baseline proposal or nonpowered T_BRANCH. No Ethernet star. Actual branches, end termination and station classes need confirmation.',
 'ccl_station_role':'Actual manager/local/intelligent/remoteIO/remoteDevice/standby manager unknown. Manager0 vsdevice start1..64. Role determines usablecyclicarea and fault/refresh behavior.',
 'ccl_station_number':'Actual configured startstation0..64 unknown. Manager0, otherroles>=1; start+occupied-1<=64. Scalarbound doesnot prove unique identities or nonoverlapping device spans.',
 'ccl_occupied_stations':'Actual device occupation1..4 station slots unknown, notautomatic1. Consumes slotnumbers and determinescyclicarea; manager not treatedasdeviceoccupation.',
 'ccl_total_occupied_stations':'Actual network slots0..64 unknown, at leastdevicecount. Actual per-device sum/overlap mustbechecked against topology; count alone notcapacity.',
 'ccl_device_count':'Actual configured devicestations0..64 unknown. Notfactory64 fromQJ61; excludesmanager. 10+device means11+total includingmanager for2024cablerevision.',
 'ccl_extended_cycle':'Single1 proposal.2/4/8 onlyprotocol2.00; actualdevice andmanager matching required. Multiplier not one hostcycle_ms or automatic transmissionperiod.',
 'ccl_rx_bits':'Actual device remote input linkpoints0..896 unknown. Occupation/cycle table ceilings32*occ single;16*(2occ-1)*cycle extended. Reserved localstationstatus bits reduce userusablearea, not allbitsare application.',
 'ccl_ry_bits':'Actual device remote output linkpoints0..896 unknown with occupation/cycle table ceilings. Directionsmanager->device. No copyingRX signal functions or Ethernetpayload.',
 'ccl_rwr_words':'Actual device->manager remote registers0..128 in16bitwords unknown. Bound4*occupation*extendedcycle; bytes2*words. NotCAN DLC or logicalframepayload.',
 'ccl_rww_words':'Actual manager->device remote registers0..128 in16bitwords unknown, bound4*occupation*extendedcycle. Not inputregistercount inherited silently.',
 'ccl_total_rx_bits':'Actual network remoteinputpoints unknown.1.10<=2048 versus2.00<=8192. Perdevice counts/sum/unusedstatusallocation must beprovided.',
 'ccl_total_ry_bits':'Actual network remoteoutputpoints unknown.1.10<=2048 versus2.00<=8192. Notbidirectional combined bytes.',
 'ccl_total_rwr_words':'Actual network inputregisters16bitwords unknown.1.10<=256 versus2.00<=2048. Not onewireframe maximum.',
 'ccl_total_rww_words':'Actual network outputregisters16bitwords unknown.1.10<=256 versus2.00<=2048. SeparatefromRWr andtransientbuffers.',
 'ccl_main_length_m':'Actual nonnegativefinite trunk length unknown.1.10 linearmax1200/900/400/160/100m at156k..10M;10M>80m has2024consecutiveten restrictions. Legacy1.00limits dependrate/shortestremote spacing. Tbranch500/100m at156k/625k only.',
 'ccl_consecutive_ten_span_m':'Actual minimumspan ofninecables across EVERY consecutive group oftenphysicalstations unknown.10M1.10linear>80m and>=11totalstations requires>=10m. Mustderivefromactualorderedtopology, notassumeddefault10. SourceCLPA Notice2404_e24April2024.',
 'ccl_remote_spacing_m':'Actual shortest remote-to-remote cable unknown.1.10linear>=0.2m;legacy1.00>=0.3m controls50/80/100m at10M and110/150m at5M. Tbranch>0.3m. Half-open thresholds checked withoutfloatgaps.',
 'ccl_special_spacing_m':'Actual shortest cable adjacent to manager/local/intelligentstation unknown.1.10linear>=0.2m, legacy>=1m remote-only /2m withlocalintelligent;Tbranch strictly>1/>2m. Actual adjacentstationclasses required.',
 'ccl_special_nodes_present':'Actual presence oflocal/intelligentnodes unknownboolean, notfalse default. Controls stricter specialadjacent spacing; manageralone doesnot implytrue.',
 'ccl_branch_length_m':'Actual longest nonpoweredbranch length unknownfinite>=0, Tbranch<=8m. Notadded automaticallyto mainlineor electricalcertification.',
 'ccl_branch_total_m':'Actual sum ofallbranch lengths unknown>=longestbranch, Tbranch<=200m at156k /50m at625k. Explicit sumproofrequired.',
 'ccl_branch_devices':'Actual maximum deviceson onebranch unknown nonnegativeinteger,Tbranch<=6. Overall64station/occupiedlimits stillapply.',
 'ccl_termination_ohms':'110Ohm proposal fordedicated1.10/standard1.00 cable, bothlineends betweenDA/DB. Highperformance130Ohm andoldA-seriesTbranch4terminator exceptions notsilentlyequivalent;actualdevice/Cable proof required.',
 'ccl_encoding':'NRZI fixed registered proposal CLPA nativeencoding. Not8N1UART/CAN arbitration/Ethernet Manchester.',
 'ccl_crc_bits':'16bitHDLC CRC fixed registered proposal, polynomialx16+x12+x5+1. NotCAN CRC15/CANXL FCRC32 orapplicationSafetyCCLinkSafetyCRC32.',
 'ccl_controller_profile':'Actual DEVICE_SPECIFIC orQJ61BT11N manager unknown. Vendor-only configuration rejected whenDEVICE_SPECIFIC explicitlychosen; unknown hardware doesnotbecomeQJ61 byusingvendorparameter.',
 'ccl_link_scan_bound_ms':'Actual measured/calculated device/systemlinkscan bound unknown finite>=0ms. Dependsstationtypes/occupiedareas/extcycles/CPUtransient/retries/reconnections; notgeneric100msapplicationcycle orserialization-only proof.',
 'ccl_q_mode':'Actual QJ61BT11N VER1/VER2/ADDITIONAL/REMOTE_IO/OFFLINE unknown. RemoteIO hasdifferent applicability ofretry/reconnection/refresh, noallmodes universaldefault inferred.',
 'ccl_q_retry_count':'QJ61BT11N linkscanretry1..7, factory3 conditionalproposal onlynamedcontroller. Notdedicated instructionSW000B retry count, notCAN automaticretry orprobability.',
 'ccl_q_reconnection_count':'QJ61BT11N1..10 returningstations perlinkscan,factory1 conditionalproposal onlynamedcontroller. Actualreturns affectlinkscanbound.',
 'ccl_q_scan_mode':'QJ61BT11N ASYNCHRONOUS conditionalfactoryproposal orSYNCHRONOUS. ActualCPU/endprocess scheduleunknown;notPTP/GPTP/frameclock.',
 'ccl_q_plc_down':'QJ61BT11N STOP conditionalfactoryproposal versusCONTINUE actualfailurepolicy. NotfunctionalSafetyassurance oruserautomaticdeploymentdecision.',
 'ccl_q_fault_input':'QJ61BT11N CLEAR conditionalfactoryproposal versusHOLD actualfaultystationinputpolicy. Neitherprovesfreshnessorreliability.',
 'ccl_q_cpu_stop_output':'QJ61BT11N REFRESH conditionalfactoryproposal versusCLEAR actualCPUSTOPpolicy. Distinctfromfaultystationinputpolicy.',
 'ccl_q_block_assurance':'QJ61BT11N false conditionalfactoryproposal forstationblockdataassurance. Actualunknownboolean; doesnotequate toatomicapplicationE2E/safetyproof.',
 'ccl_q_transient_send_words':'Actual QJ61BT11N Sendbuffer0or64..4096 in16bitwords. Conditionalfactory64namedcontroller. SumallSend+Receive<=4096;per-scalar checkpartial, actualallstationssumrequired.',
 'ccl_q_transient_receive_words':'Actual QJ61BT11N Receivebuffer0or64..4096 in16bitwords. Conditionalfactory64namedcontroller. Send+Receive<=4096;actualallstationssumrequired.',
 'ccl_q_transient_auto_words':'Actual QJ61BT11N Autoupdatebuffer0or128..4096 in16bitwords. Conditionalfactory128namedcontroller. Sumallstationautoareas<=4096 requiresactualtopology;independentsinglefieldrangeonly.'
}
spec={'technology':'cc_link','native':native,'removed':ble['removed'],
 'sources':['https://www.cc-link.org/en/networktechnology/spec.html',
            'https://www.cc-link.org/en/news/pdf/Notice2404_e.pdf',
            'https://www.mitsubishielectric.com/dl/fa/document/manual/plc/sh080394e/sh080394es.pdf',
            'https://www.mitsubishielectric.com/fa/id_en/products/cnt/plcq/pmerit/network/cclink.html'],
 'revisions':['CLPA V1.10/V2 tables accessed2026-10-01','CLPA BAP-C2001ENG-001 cable revision24April2024',
              'Mitsubishi SH(NA)-080394E-S June2024 sections3.6/6.2/7.2/7.3.2/Appendix4.1'],
 'scope':'Every registeredCC-Link field, rates,cableversion/physical access, occupation/linkarea/native vendorconfiguration, dependencies andisolatedSQL preservation. NoCC-LinkIE/Ethernet/CAN defaults.',
 'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters','passed':0},
 'not_certified':['ExecutableCC-LinkHDLCframe/linkscan/fault/schedule model remainsMODEL_MISSING',
                  'Actualdeviceidentity/role/slotoccupationandsupportedrate/cableproof',
                  'Actualperstationusableuserdata/reservedstatusallocation/areasums/nooverlaps',
                  'Orderedphysicalsegments neededtoderiveeveryconsecutivetenspan andspecialadjacentspacing',
                  'QJ61BT11Ncompleteconditionalmodeapplicability/allstationtransientbufferaggregate',
                  'Highperformancelegacy1.00cable, poweredrepeaters, oldA-series4terminatorTbranch exceptions',
                  'CC-LinkSafety,CC-LinkLT andCC-LinkIE requireseparateprofiles; noSafetyevidence']}
(folder/'cc_link-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
