"""ETB source decisions: own backbone PHY, actual topology and state boundaries."""
import json
from pathlib import Path

folder=Path(__file__).resolve().parent
native={
    'bitrate':'ETB own physical port rate positive finite bit/s; source-qualified100Mb baseline proposal, selected100BASE_TX=100M/1000BASE_T=1G conditional proposals. No CAN rate, aggregate redundancy sum or unknown device confirmation.',
    'payload_bytes':'Actual MAC-client data unknown nonnegative integer octets excluding Ethernet header/FCS/pad. BASIC_MAC<=1500 and <=knownselectedMACpayloadlimit. Not completeTRDP/IPmessage or actual8B default.',
    'mtu_bytes':'Selected MAC-client payload limit positive integer octets; BASIC_MAC proposal1500 from IEEE existingbasicframe figure, not IPMTU/fullframe/applicationbytes. DEVICE_SPECIFIC exactsupportedmaximum unknown, no universal65535 jumbo.',
    'duplex':'Actual FULL/HALF selection unknown; supportedreviewed100BASE_TX/1000BASE_T backbone configurations full-only with conditionalFULLproposals. Notgenerichalf-duplexCANarbitration.',
    'vlan_id':'ActualconfiguredbackboneVLANunknowninteger1..4094, notdefault0, notautomaticallyTTDPtopologyVLAN492 or localECNVLAN1/vlan2example.',
    'rate_limit_bit_s':'Actual configuredportpolicerunknownnonnegativeintegerbit/s<=knownlinkrate. Explicit0 meansdisabled onlyifdeclared, no fabricatedactual0 limit or gatewaythroughput.',
    'etb_edition':'Required actualIEC61375-2-5:2014/DEVICE_SPECIFIC matchededitionunknown. IECpublisheredition1.0published2014-08-25; futuredraftPHYextensionsnotclaimedreleasedconformance.',
    'etb_phy':'Required selected100BASE_TX/1000BASE_T/DEVICE_SPECIFIC PHY; source-qualified100BASE_TXbaselineproposal, Gbitactualportconfigurationdistinct. PublishedmanufacturerGbitsupportdoesnotcertifyeveryIECedition.',
    'etb_node_role':'Required actualETBN/END_DEVICE/DEVICE_SPECIFIC roleunknown; backbone topologyrouterdiffersfromECNcontroller/device, no automaticindustryarchitecture fallback.',
    'etb_configuration_source':'Required actualmatchededition/device/firmware/configuration sourceunknownreference. WeOSmanufacturersettingsareimplementation-qualified, notfullIECnormativeconformance.',
    'etb_physical_binding':'Required actualbackboneport/cable/crossover/bypass/PHYprofileunknownreference; stringnotproofregisteredvalidphysicalpath or electricalbudget.',
    'etb_implementation':'ActualWEOS_5/DEVICE_SPECIFIC implementationunknown; selectedWeOSallowsitslocalID/ECN/port/backboneconstraints and conditionalproposals, no automaticallyinstalledvendor.',
    'etb_frame_profile':'SelectedBASIC_MAC/DEVICE_SPECIFIC encoding; baselineBASIC_MACproposal, onlyBASICimposes1500data ceiling. Tagged/envelopeheader/padding/IFG exactwiremodelnotexecuted.',
    'etb_local_id':'ActualstaticrelativeETBNpositioninconsistunknownpositiveinteger; WeOS1..32. DistinctdynamictrainwideETBNID; wholeorderedsequence/no-gaps/uniqueness requiresactualtopology.',
    'etb_ecn_id':'ActualattachedconsistnetworkIDunknownpositiveinteger; WeOS1..4. No default1, actualuniquecontiguousECNsetandmapping unknown.',
    'etb_backbone_id':'ActualbackbonepurposeIDunknownnonnegativeinteger; WeOSonly0TCMS/1multimedia with0conditionalmanufacturerdefault. IDs2/3notsupportedWeOSnotgenericallimplementationclaim.',
    'etb_dir1_ports':'Actualdirection1redundantportcountunknownnonnegativeinteger; WeOSmax2. Portidentities/bypass/crossover/rotation requireactualorderedmapping, notdefault2.',
    'etb_dir2_ports':'Actualdirection2redundantportcountunknownnonnegativeinteger; WeOSmax2. A0declarationisnotproofoperationalconnectedETBN, directiontopologyvalidationremainsunknown.',
    'etb_aggregation':'ActualTTDP_ACTIVE_STANDBY/DEVICE_SPECIFIC linkmechanismunknown; primaryTTDPdescriptiononeactivedatalinkuntilHELLOtimeout, no LACPloadsharing/doublecapacity inference.',
    'etb_active_links_per_direction':'Actual simultaneouslyactivedatalinkcountunknownnonnegativeinteger;TTDP<=1, <=knowndirportcounts.0possiblepending/failure; redundancy2physicalportsdoesnotmean2activedata paths.',
    'etb_topology_vlan':'ActualTTDPTOPOLOGYsignallingVLANunknowninteger1..4094;WeOS492conditionalproposal/constraint. DistinctconfiguredbackboneinterfaceVLAN and ECN-over-ETB tags.',
    'etb_igmp_snooping':'ActualbackboneIGMPsnoopingunknownboolean;WeOSrequiresdisabledFalse, no precheckedFalse or globalECNIGMPassumption.',
    'etb_consist_uuid':'ActualRFC4122shapedconsistUUIDunknown, rejectsall-zero unresolvedconfiguration. SameconsistsharedUUID/differentconsistuniqueness cannotprovefromoneformattedstring; no auto-MACrandomUUID.',
    'etb_etbn_mac':'ActualETBNMACunknownsixcolon-separatedhexoctets; notconsistUUID, slaveaddress, uniqueverifiednode or autoNICselection. Fullunicast/installedinterfaceidentitynotcertified.',
    'etb_topology_counter':'ActualcurrentetbTopoCntunknowntextvalue; primarycallsCRCoforderedtopology. ScalarisnotrecalculatedCRC proof; exactencoding/width/matchededitionneedactualmapping.',
    'etb_message_topology_counter':'ActualmessageetbTopoCntunknowntextvalue. INTER_CONSISTenabledtrafficmustmatchknowncurrentvalue;INTRA_CONSISTmay0 perprimarysource. No invented0/currentcounter default or wireCRCcertificate.',
    'etb_inauguration':'ActualPENDING/INAUGURATED/FAILEDstateunknown;PENDING/FAILEDrejectexplicitenabledapplicationtraffic. SelectingINAUGURATEDdoesnotproveallnodesagreedcurrenttopology.',
    'etb_inhibition':'Actualinaugurationinhibitionunknownboolean; inhibitsnewtopologyjoin/change, cancoexistwithtrafficonthealreadyinauguratedtopology. Neverblanketassumeinhibitionstopsalltraffic.',
    'etb_traffic_enabled':'Actualapplicationtrafficenabledunknownboolean; rejectedknownpending/failedinauguration, currentINTER_CONSISTcountermustmatch. No defaultTrue or automaticverifiedruntime state.',
    'etb_traffic_scope':'ActualINTRA_CONSIST/INTER_CONSISTscopeunknown; zerointra-consistcounterexceptionnotappliedinter-consist. Scopedcounterrules do not substitute actualrouting.',
    'etb_state_source':'Actualcorrelatedinauguration/inhibition/topology/trafficobservationsourceunknownreference; stringnotcertificateactualexecutedstate/timestamps/failover.',
    'etb_topology_source':'ActualorderedconsistUUID/ETBNMAC/relativeIDs/ECNconnections/bypassorientationsunknownreference. Fullgraphuniqueness/no-gaps/agreementchecksnotcertifiedfromscalar.',
    'etb_hello_period_ms':'ActualTTDPHELLOperiodunknownpositivefinite ms; no universalNIS100ms or arbitraryliteratureguess, exactmatchededition/implementationrequired.',
    'etb_hello_timeout_ms':'ActualHELLOneighbourlosstimeoutunknownpositivefinite ms>=knownperiod; no inferredrecoverybound or universal3xretry rule.',
    'etb_topology_period_ms':'ActualTTDPTOPOLOGYexchangeperiodunknownpositivefinite ms; notTRDPdata cycle or genericsyncinterval, no fabricateddefault.',
    'etb_link_recovery_bound_ms':'Actualboundedport/bypass/HELLO/failoverrecoveryunknownnonnegativefinite ms. Manufacturerfastlinkfeatureisnotverifieduniversal20ms capacity bound.',
    'etb_ip_address':'ActualtopologyassignedIPv4/IPv6unknownvalidatedIPstring; primary10.128.x and ECN10.0.0 examplesnotactualdefault/range-conformance. FullIECaddressscheme/multicast/mDNS/NAT independent.',
    'etb_address_mapping_source':'ActualTTDPdynamicETBN/ECN/virtualIP/NAT/multicastmappingunknownreference; no implicitEthernet/NMEA2000comparison, wholemapping/sourceconstraintsnotcertified.',
    'etb_mdix_mode':'ActualMDI/MDIX/AUTOportconfigurationunknown; manufacturerrecommendationconsistentMDI/crossover requiresactualcable/bypass mapping. No automaticphysicalcrossoverproof.',
    'etb_autonegotiation':'Actualportautonegotiationunknownboolean; fixedmanufacturerconfigrecommendsdisabled but ordinaryEthernetdefaultmayenabled. No globalFalse proposal that misstatesinstalledlink.',
    'etb_clock_role':'ActualGbitcopperMASTER/FOLLOWER/AUTOunknown; rejected100BASE_TXwhereclockroleinapplicable. KnownfixedGbitpeeroppositeroleorAUTO; linkrotation/bypasspairingsneedactualgraph.',
    'etb_peer_clock_role':'ActualconnectedpeerGbitroleunknown; knownMASTERmustoppositeFOLLOWER/AUTO andviceversa, no samefixedroles. ScalarAUTOdoesnotprovePHYnegotiatedclock.',
    'etb_queue_source':'Actualswitching/TTDPcontrolpriority/queuecapacity/schedule evidenceunknownreference; no genericPCP3/TAS/CBS support or full-duplexqueue-delayguarantee.',
    'etb_peer_limit_source':'ActualpeerMACpayload/frameprofilebufferlimitunknownreference; BASIC1500proposalnotactualreceivebuffer/fragmentation/TRDP/applicationacceptance proof.'
}
removed={
    'qos_priority':'No universalPCP3 forETB/TTDP control/data; actualcontrolclass/queue/scheduling separate.',
    'reserved_bandwidth_percent':'No universalETBreservation0percent or automaticallyguaranteedcontrolbandwidth.',
    'sync_method':'TTDPtopologyagreementisnotclockPTP/gPTPsynchronization;actualclockservice independent.',
    'retransmission_enabled':'GenericFalse doesnotrepresentHELLOneighbourdetection/TRDPrecovery/actualupperTCPconnection.',
    'retransmission_rate':'GenericprobabilisticretryrateisnotTTDPstateor actualtransport/redundancy.',
    'retry_limit':'No universalETBretry0/3;HELLO/TOPOLOGY/payloadreliability separate.',
    'retransmission_delay_ms':'No universalETB0msretrydelay; exactmatchedcontrol/applicationtimerrequired.',
    'gateway_maximum_throughput':'No universal100Mbit/sETBNroutingthroughput;physicalrateandactualswitchingcapacitydistinct.',
    'gateway_input_buffer':'No universal256frameETBNinputbuffer.',
    'gateway_output_buffer':'No universal256frameETBNoutputbuffer.',
    'gateway_maximum_routes':'No universal10000ETBNroutes;actualdynamicNAT/ECNmappingdistinct.',
    'gateway_maximum_messages_s':'No universal100000ETBNmessage/s capacity.'
}
spec={'technology':'etb','native':native,'removed':removed,
      'sources':['https://webstore.iec.ch/en/publication/5400',
                 'https://docs.westermo.com/weos/5/Train/ttdp/',
                 'https://docs.westermo.com/weos/weos-5/HowTo/iec61375-port-setting-backbone-ports.html',
                 'https://www.ieee802.org/3/frame_study/0409/daines_3_0409.pdf'],
      'revisions':['IEC61375-2-5:2014edition1.0published2014-08-25publishermetadata; full257page licensednormativebody notread',
                   'WestermoWeOS5.29TTDP/ETBNportconfiguration accessed2026-10-01;100Mb/Gbitmanufacturerprofiles notglobalall-editionIECclaims',
                   'IEEE802.3FESGKevinDaines30September2004pages3/5/6 existingbasicframe observations; proposedextensionsnotadoptedrules'],
      'scope':'EveryoriginalETBfield separately reviewed; source-qualifiedbaseline100Mb, ownPHY/consist/topology/inauguration/active-standbycounter declarations and actualtimingunknowns. Rejected-editSQLretention.',
      'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters','passed':0},
      'not_certified':['FulllicensedIEC61375-2-5editionnormativebody/TTDPwireframingtimers/fault-stateconformance notverified; currentdraftextensionsnotclaimedstandard',
                       'ActualorderedtopologyUUID/MAC/ETBN/ECNuniqueness/no-gaps, directionrotation/crossover/bypass/PHYtiming and inauguratedstate needexecutedcorrelatedmodel',
                       'ActualTTDPCRC/inhibition/failover/queue/controlpriority/IPNAT/multicastmapping and exactruntimepacketadmission notcertifiedbydeclarations',
                       'No registeredETBcompletephysical/schedule/capacitymodel;MODEL_MISSINGpreserved.100Mb or redundantportcountdoesnotcertifycapacity']}
(folder/'etb-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
