"""Individually sourced classic EtherCAT fields; declarations are not E2E evidence."""
import json
from pathlib import Path

folder=Path(__file__).resolve().parent
native={
    'bitrate':'Classic registered EtherCAT fixed100Mbit/s, source SectionI2.5 chapters1/5; Gbit PHY must advertise100M for this ESC family. Not EtherCATG/G10, CAN bitrate or double bandwidth from full-duplex marketing examples. Proposal never actual confirmation.',
    'payload_bytes':'Actual selected datagram data unknown integer0..1486 octets; reviewedUDP/IPv4 limit1458. Not complete MAC frame, sum across datagrams, PDO image or mailbox transfer. Remove actual8B default.',
    'mtu_bytes':'Classic MAC-client limit1500 octets source-qualified proposal and fixed scalar bound. Distinct TwinCAT cyclic-frame MTU28..1514 including14-byteMAC header but noFCS, EtherCAT area2+datagrams, and selected datagram1486.',
    'duplex':'Registered classic EtherCAT full-duplex only, FULL literature proposal; HALF invalid. Sole active MainDevice generates segment frames; no Ethernet shared collision/CAN arbitration fallback.',
    'vlan_id':'Actual optional VLAN ID unknown integer1..4094; no default0. ESC accepts tags but does not evaluate contents; does not prove office-switch reachability or ETB topology VLAN492.',
    'distributed_clock_cycle_ms':'Actual SYNC0 period unknown nonnegative finite ms; DC mode equals known ns register/1e6. Zero selects single-shot. No universal1ms device period or automatic DC capability; FREE_RUN/SM_EVENT inapplicable.',
    'ecat_transport':'Required actual NATIVE_ETHERNET/UDP_IPV4 selection; native baseline proposal. Selected UDP has20-byteIPv4+8UDP and port34980, not generic IPv6/options/checksum behavior.',
    'ecat_phy':'Required actual100BASE_TX/100BASE_FX/EBUS/ETHERCAT_P unknown; classic100M operation, medium-specific loss detection and wire evidence separate. No fabricated installed transceiver.',
    'ecat_esi_source':'Required actual ESI/SII/ESC hardware revision/features/configuration source unknown. SectionI covers several variants and explicitly says not every feature exists on every ESC.',
    'ecat_topology_source':'Required actual ordered MainDevice/SubDevice port/loop/cabling reference unknown; string does not resolve physical graph, uniqueness, link direction or delays.',
    'ecat_main_device':'Actual sole active MainDevice identity unknown text reference; number/ownership/schedule execution must follow actual topology, no default master node.',
    'ecat_frame_type':'Classic supported EtherCAT header type1, fixed proposal1. Reserved/vendor types not accepted under reviewed ESC profile; not CAN identifier.',
    'ecat_header_reserved':'One reserved header bit0, fixed source proposal0, not actual observed packet assertion.',
    'ecat_header_length':'Actual datagram area length unknown integer12..1498, excluding2-byteEtherCAT header/FCS/pad; equals known complete datagram bytes.11-bit raw field is wider but classic selected frame budget limits it; ESC ignores header length and relies on individual lengths.',
    'ecat_datagram_count':'Actual frame datagram count unknown integer1..124 arithmetic ceiling floor1498/12; <=known device limit. Primary product docs differ15/16; no invented universal ESC processing-count limit.',
    'ecat_device_datagram_limit':'Actual ESI/MainDevice/ESC supported count unknown1..124; theoretical byte ceiling is not hardware proof. Device15 or16 remains explicit actual configuration.',
    'ecat_sum_data_bytes':'Actual aggregate data across all frame datagrams unknown integer0..1486, >=selected payload, equals it for one datagram. Header overhead12bytes each reduces usable aggregate; no uniform payload-size multiplication.',
    'ecat_datagram_bytes':'Actual complete area unknown integer12..1498 equals dataSum+12*count. Native<=1498/UDPIPv4<=1470.10-byte header+2-byteWKC per datagram separate from application bytes.',
    'ecat_padding_bytes':'Actual MAC padding integer0..32, unknown; minimum64-byte frame requires max(0,44-extraIPUDP-4tags-datagramArea). Native/UDP/tagged cases checked separately; no generic8B overhead.',
    'ecat_vlan_tags':'Actual reviewed classic tag count unknown0..1 integer; no invented tagged/untagged default. Additional stacked/envelope layouts require a separate profile.',
    'ecat_mac_frame_bytes':'Actual MAC frame unknown integer64..1522 includingFCS excludingpreamble/IFG. Equals20+datagramArea+4tags for native, plus28UDPIPv4, plus actual required pad. Native basicmax1518/tagged1522.',
    'ecat_wire_slot_bytes':'Ethernet wire occupation unknown integer84..1542 includes MAC frame+8preamble/SFD+12IFG; rejected EBUS where this Ethernet slot model is inapplicable. Serialization does not prove loop/forwarding/queue/E2E timing.',
    'ecat_udp_port':'Actual selected UDP destination unknown1..65535; UDP_IPV4 exact34980(0x88A4) conditional proposal. Native transport inapplicable; EtherType and port happen to share numeric value but have different fields.',
    'ecat_ipv4_header_bytes':'Reviewed classic UDP detector requires20-byte IPv4 header, actual field unknown until declared. IPv6/options are not silently accepted; native transport inapplicable.',
    'ecat_command':'Actual NOP/AP/FP/broadcast/logical/read-multiple-write command unknown; source table6 commands0..14, others reserved. Selected command must match selected addressing; no invented LRW operation.',
    'ecat_index':'Actual datagram index unknown8-bit integer0..255, MainDevice uses for loss/duplicate detection, SubDevice shall not change it. Not unique node/sequence proof.',
    'ecat_datagram_length':'Actual selected data-length field integer0..1486 unknown, equals known payload.11-bit raw LEN cannot exceed actual classic frame budget; UDPselected data<=1458.',
    'ecat_datagram_reserved':'Three reserved bits0 fixed proposal0; no fake actual observed reserved field.',
    'ecat_circulating':'Actual circulating-frame bit unknown boolean; true indicates one circulation, not automatic redundancy enabled or valid repeat.',
    'ecat_more':'Actual more-datagrams flag unknown boolean; single-datagram frame requires false. Exact flag chain across a multi-datagram packet remains unexecuted without ordered datagram model.',
    'ecat_irq':'Actual combined event-request integer0..65535 unknown, logical OR of ESC registers. Not E2E interrupt acceptance or diagnosed hardware observation.',
    'ecat_addressing':'Actual AUTO_INCREMENT/CONFIGURED/BROADCAST/LOGICAL mode unknown. AP/ARMW, FP/FRMW, BR and L commands have separate mode constraints. No CAN station/network assignment.',
    'ecat_station_address':'Actual16-bit encoded position/configured address field integer0..65535 unknown; auto-increment position is wire-encoded and increments at each ESC. Actual configured address/alias uniqueness/support remains mapping-dependent.',
    'ecat_register_offset':'Actual local register/memory offset integer0..65535 unknown; logical addressing inapplicable. Registers0..0FFF/process memory1000..FFFF do not prove implemented/accessible device buffer.',
    'ecat_logical_address':'Actual32-bit logical process-image address integer0..4294967295 unknown; only LOGICAL mode, not physical station address. FMMU bit mapping and full addressed extent remain actual contract.',
    'ecat_mapping_source':'Actual station/alias/FMMU/SyncManager/PDO mapping reference unknown; bounds, buffer alignment/allocation and command-specific read/write WKC increments need actual ordered participant model.',
    'ecat_expected_wkc':'Actual expected16-bit working counter0..65535 unknown, computed by MainDevice for addressed operations. Read/write increments differ; no assumed number-of-nodes or automatic expected3.',
    'ecat_received_wkc':'Actual observed16-bit WKC0..65535 unknown; response accepted requires equality with known expected. Rejected response may mismatch. WKC cannot show every byte succeeded and does not certify functional timing.',
    'ecat_response_accepted':'Actual response acceptance unknown boolean; no defaultTrue. When explicitlyTrue, knownWKC values must match; missing observed/expected values remain capacity evidence unknown.',
    'ecat_sync_mode':'Actual FREE_RUN/SM_EVENT/DC synchronization unknown; DC requires known support notFalse and separate reference/calibration. GenericNISsync fields do not choose a clock mechanism.',
    'ecat_dc_supported':'Actual ESC DC capability unknown boolean; explicitFalse excludes DC width/reference/signal periods. Source hardware optional feature bit/SII actual evidence required.',
    'ecat_dc_width':'Actual supported DC32/64 bit width unknown; lower32 bits wrap about4.2s, distinct32-bit cycle register. No default64-bit clock or timestamp guarantee.',
    'ecat_dc_reference':'Actual reference clock node unknown text reference; typical first supportedDC node in propagation order, not necessarily first network node. No fabricated clock identity.',
    'ecat_dc_source':'Actual supported width/reference/offset/drift/propagation calibration source unknown; sub-microsecond marketing performance is not actual measured synchronization guarantee.',
    'ecat_sync_generation':'Actual CYCLIC_PULSE/SINGLE_SHOT/CYCLIC_ACK/SINGLE_SHOT_ACK mode unknown; zero/nonzeroSYNC0 and pulse length combinations checked independently. State activation/start/ack execution missing.',
    'ecat_sync0_cycle_ns':'Actual unsigned32-bit SYNC0 register integer0..4294967295ns unknown. Cyclic>0, single-shot0; ms alias knownvalue conversion checked, no1ms default or10ns-quantum rejection inferred from internal tick.',
    'ecat_sync1_delay_ns':'Actual unsigned32-bit SYNC1 delay fromSYNC0 integer0..4294967295ns unknown. Zero can reflectSYNC0, values greater thanSYNC0 can be supported; not a blindly constrained second cycle period.',
    'ecat_sync_pulse_ns':'Actual pulse width unknown integer0..655350ns and multiple10ns, matches known16-bit10ns register. Zero selects acknowledged modes, pulses need>0. Source register3.0table111; SII-dependent reset not universal default.',
    'ecat_sync_pulse_register':'Actual16-bit pulse-width register unknown0..65535 counts10ns. Not raw ns; multiplying10 gives pulse_ns. No actual power-on/SII value assumed.',
    'ecat_watchdog_divider':'Actual shared16-bit WD_DIV unknown0..65535; one tick approximately(divider+2)*40ns.2498conditionalreset proposal only matchedBECKHOFF_3_0 profile, not universal EtherCAT device setting.',
    'ecat_register_profile':'Actual matchingBECKHOFF_3_0/DEVICE_SPECIFIC register profile unknown;3.0 dated2020-09-10 coversESC20/ET1100/ET1200/FPGAcores. Selecting doesnot verifyinstalledvariant or all optional registers.',
    'ecat_pd_watchdog_ticks':'Actual16-bit process-dataWD register unknown0..65535;0meansdisabled, no finite timeout allowed.1000conditionalreset proposal for matched3.0 gives about100ms with divider2498, actualSyncManagertrigger configuration separate.',
    'ecat_pdi_watchdog_ticks':'Actual16-bit PDI WD register unknown0..65535; independenttimer sharing divider,0disabled.1000conditionalmatched3.0reset proposal, not applicationE2Edeadline/PDperiod.',
    'ecat_pd_watchdog_min_ns':'Approximate earliest timeout unknown nonnegative integer ns=(divider+2)*40*ticks onlypositivePDticks. DisabledWD hasno finite timeout, reject supplied value including0; estimate explicitlynot exactnanosecondbound.',
    'ecat_pd_watchdog_max_ns':'Approximate latest timeout unknown nonnegative integer ns=(divider+2)*40*(ticks+1) onlypositivePDticks. DisabledWD hasno finite timeout, no fabricatedsafe reaction proof.',
    'ecat_watchdog_source':'Actual PD/PDI watchdog support/divider/SyncManager trigger/reset/safe-output reaction evidence unknownreference; reset defaults do not prove activewatchdog or safe/E2Eacceptance.',
    'ecat_state':'Actual INIT/PREOP/SAFEOP/OP/optionalBOOTSTRAP stateunknown; observedstate source/acknowledgedtransitions separate. Functional process outputs cannot be declaredactive outsideOP; failsafephysical outputs distinct.',
    'ecat_outputs_active':'Actual functional process outputs active unknownboolean; INIT/PREOP/SAFEOP/BOOTSTRAPrejectTrue. OP selection alone doesnot confirm actuation/timing/safety or bypass modelapproval.',
    'ecat_al_status_code':'Actual16-bit AL status/errorcode unknown0..65535; fullcode membership and matchedvariant semantics unknown, no default0 means healthy.',
    'ecat_state_source':'Actual acknowledged AL/state/output/error observations source unknownreference; scalar source not runtime correlated proof.',
    'ecat_mailbox_protocol':'Actual COE/FOE/EOE/SOE/AOE/VOE/DEVICE_SPECIFIC protocol unknown; supportedfeatures/SII actual, not allprofiles alwayssupported and no CAN bitratereuse through CoEname.',
    'ecat_mailbox_bytes':'Actual configured mailbox buffer unknowninteger6..65535 octets including6-byteheader; <=actualaccessibleSyncManagerRAM unknown. Not 1486 single-datagram fixed cap or universal256buffer.',
    'ecat_mailbox_data_bytes':'Actual mailbox command payload unknowninteger0..65529 excluding6-byteheader; <=knownbuffer−6. Upper16-bit field/address space doesnot proveallocation or fragmentedmailboxactualsizes.',
    'ecat_mailbox_source':'Actual supportedprotocol/SyncManager buffer/address/timeout/repeat contract unknownreference; completeETG.1000.6application wire/state/segmentation notread or certified.',
    'ecat_link_detection':'Actual STANDARD/ENHANCED link-loss mechanismunknown; medium/ESC feature-dependent. No defaultSTANDARD or enhancedfeature automaticallypresent.',
    'ecat_link_loss_bound_us':'Actual finite nonnegativePHYreaction bound unknownµs, decimalsallowed. EthernetPHY STANDARD requiresstrictly<15µs; EBUS not compared to thatEthernetrequirement. Enhanced linkdetect requiresactualRX_ERR/feature evidence.',
    'ecat_link_source':'Actual PHY/cable/port/forwarding/reset/enhancedlinkbounds source unknownreference;100Mrate/full-duplex alone notcapacityschedule/physicalconformance proof.'
}
removed={
    'qos_priority':'No universalPCP3 for classic EtherCAT; ESC doesnot evaluate VLANpriority contents and MainDevice determines frame schedule.',
    'reserved_bandwidth_percent':'No universal genericEtherCATreservation percentage or switchQoS guarantee.',
    'sync_method':'GenericNTP/PTP/gPTP dropdown doesnot model actual DC/free-run/SM-event/reference/calibration.',
    'retransmission_enabled':'GenericFalse isnot a supportedframe-repeat/ESI/mailboxcounter/ack mechanism.',
    'retransmission_rate':'Probabilisticgenericretryrate doesnot represent working-counter rejection or configuredsupportedframe repetition.',
    'retry_limit':'No universal retry0/3; exact actual MainDevice/SubDevice repeat/mailbox profile remains required.',
    'retransmission_delay_ms':'No universal0ms EtherCAT retrydelay or validatedframe scheduling.',
    'gateway_maximum_throughput':'No universal100Mbit/s gateway forwardingcapacity; EtherCATon-the-fly processing differs from ordinary IProuter/switch.',
    'gateway_input_buffer':'No universal256frame gateway inputbuffer.',
    'gateway_output_buffer':'No universal256frame gateway outputbuffer.',
    'gateway_maximum_routes':'No universal10000IProute or station/FMMU mapping table size.',
    'gateway_maximum_messages_s':'No universal100000message/s EtherCAT gatewaycapacity.',
    'rate_limit_bit_s':'Generic Ethernetpolicer isnot classic on-the-fly segment schedule and cannot throttle unchanged frames through ESC. Actual MainDevice pacing/ESI budget separate.'
}
spec={'technology':'ethercat','native':native,'removed':removed,
      'sources':['https://download.beckhoff.com/download/document/io/ethercat-development-products/ethercat_esc_datasheet_sec1_technology_v2.5.pdf',
                 'https://download.beckhoff.com/download/Document/io/ethercat-development-products/ethercat_esc_datasheet_sec2_registers_3i0.pdf',
                 'https://infosys.beckhoff.com/content/1033/tc3_io_intro/1446515467.html',
                 'https://infosys.beckhoff.com/content/1033/tc3_io_intro/1446569867.html',
                 'https://infosys.beckhoff.com/content/1033/ethercatsystem/2477875083.html'],
      'revisions':['BeckhoffESCSectionI Technology2.5 2025-07-28 162pages chapters1/2/5/8/9/10/13 readrelevantsections',
                   'BeckhoffESCSectionII Registers3.0 2020-09-10 107pages tables57..59 and111 reset/units; actualvariantSII separate',
                   'BeckhoffTwinCAT3cyclicframes/sizeexample and olderdefaultsettings accessed2026-10-01;15/16datagram hardwarecounts not generalized'],
      'scope':'Eachoriginal EtherCATfield independently reviewed; classicframe/datagram/UDP layers, actualcommands/addressing/WKC/DC/state/mailbox/PHY/watchdog declarations and qualifiedreset proposals. Rejected-editSQLretention.',
      'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters','passed':0},
      'not_certified':['FullmatchedETG.1000/IEC61158Type12wire/application/ESIdeviceconformance notcertified; EtherCATG/G10 aredistinct andnot silentlysupported',
                       'ActualorderedESI/PDO/FMMU/SyncManager/registerRAM/mailboxmaps and percommandperdeviceWKC are not executed; partialWKCsuccess cannotproveallbytes orfunctionalresult',
                       'ActualinaugurationnotanEtherCATmechanism; ALtransition/DCcalibration/latch/startack/WDtrigger/failure/redundancy/PHYreset/link budgets requirecorrelatedexecution',
                       'No registeredcompleteEtherCATphysical/schedule/capacitymodel;MODEL_MISSINGpreserved, sourcequalified100M/rangevaliditynotE2Esafetyacceptance']}
(folder/'ethercat-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
