"""Source-qualified FOUNDATION H1 declaration and individual parameter decisions."""
import json
from pathlib import Path

SOURCE='https://www.yokogawa.com/pdf/provide/E/GW/TI/0000001497/0/TI38K02A01-01E.pdf'
REVISION='Yokogawa TI38K02A01-01E third edition April2012 sections2.1.2/2.2/2.3/2.4/2.5/3.5.2; manufacturer tutorial, not full normative specification'
# key, kind, unit, options, minimum, maximum, proposed baseline, individual meaning
declarations=[
 ('ff_profile','select',None,['H1_VOLTAGE_MODE','DEVICE_SPECIFIC'],None,None,'H1_VOLTAGE_MODE','Reviewed two-wire voltage-mode H1 baseline proposal. Optical/media extensions require their own physical evidence; HSE Ethernet is a different transport.'),
 ('ff_configuration_source','text',None,None,None,None,None,'Required matched specification/firmware/network configuration reference, unknown.'),
 ('ff_cff_source','text',None,None,None,None,None,'Required matched device CFF capability file/version, unknown. Capacity, timer and block constraints are not universal defaults.'),
 ('ff_physical_source','text',None,None,None,None,None,'Required actual segment cable/power/terminator/repeater/signal/intrinsic-safety evidence, unknown.'),
 ('ff_schedule_source','text',None,None,None,None,None,'Required actual LAS/VCR/block execution/communication schedule evidence, unknown. Schedule feasibility is not implied by bitrate.'),
 ('ff_layout','select',None,['YOKOGAWA_FMS_DIAGRAM','DEVICE_SPECIFIC'],None,None,'YOKOGAWA_FMS_DIAGRAM','Qualified FMS/FAS/data-transfer diagram layout. Control PDUs and fragmented logical domains need their own definition.'),
 ('ff_pdu','select',None,['DT','CD','PT','RT','EC','DC','RI','PN','PR','TD','CT','RQ','RR','CL','TL','IDLE'],None,None,None,'Actual link PDU, unknown. Native control traffic is not an FMS data-transfer packet.'),
 ('ff_fms_pci_bytes','number','Byte',None,0,255,4,'Four-octet FMS PCI proposal only for reviewed FMS DT layout.'),
 ('ff_fas_pci_bytes','number','Byte',None,0,255,1,'One-octet FAS PCI proposal only for reviewed FMS DT layout.'),
 ('ff_dl_sdu_bytes','number','Byte',None,0,256,None,'Actual data-link SDU, equals FMS encoded payload plus FMS/FAS PCI in reviewed DT layout. Priority ceiling applies to DLSDU, not payload.'),
 ('ff_dl_pci_bytes','number','Byte',None,0,255,None,'Actual data-link PCI, unknown; reviewed DT diagram range5..15 octets. Not a universal overhead8.'),
 ('ff_fcs_bytes','number','Byte',None,0,255,2,'Two-octet frame-check sequence baseline proposal. A declared size does not recompute or verify integrity.'),
 ('ff_ph_sdu_bytes','number','Byte',None,0,None,None,'Actual complete DL PDU/physical SDU, including DL PCI/SDU/FCS. Reviewed FMS diagram range8..273; excludes physical delimiters/preamble.'),
 ('ff_preamble_bytes','number','Byte',None,1,None,1,'Baseline one-octet preamble proposal; actual repeaters may require extension. Lower baseline does not prove physical synchronization.'),
 ('ff_start_bytes','number','Byte',None,1,1,1,'One-octet-equivalent physical start delimiter proposal, includes non-data symbols; not an Ethernet preamble.'),
 ('ff_end_bytes','number','Byte',None,1,1,1,'One-octet-equivalent physical end delimiter proposal; not an Ethernet interframe gap.'),
 ('ff_wire_octets','number','octet-equivalents',None,0,None,None,'Actual physical telegram sum including preamble/start/end. Excludes idle/response/token exchanges and block execution; not whole transaction latency.'),
 ('ff_priority','select',None,['URGENT','NORMAL','TIME_AVAILABLE'],None,None,None,'Actual native DLL urgency, unknown. Qualified DLSDU ceilings64/128/256 bytes respectively; no CAN ID or Ethernet PCP conversion.'),
 ('ff_vcr','select',None,['PUBLISHER_SUBSCRIBER','CLIENT_SERVER','SOURCE_SINK'],None,None,None,'Actual VCR model. Buffered scheduled publication differs from queued client/server or source/sink token traffic.'),
 ('ff_access','select',None,['SCHEDULED_CD','UNSCHEDULED_PT'],None,None,None,'Actual native access mechanism. CD scheduled publication; PT unscheduled token passing. Not generic FIFO arbitration.'),
 ('ff_buffering','select',None,['BUFFERED','QUEUED'],None,None,None,'Actual VCR storage semantics; buffered publisher/subscriber is not a queue. Queue capacity remains actual CFF configuration.'),
 ('ff_device_class','select',None,['BASIC','LINK_MASTER','BRIDGE'],None,None,None,'Actual device class, unknown. BASIC cannot become LAS; link master and bridge have capability, not automatic active status.'),
 ('ff_las_active','boolean',None,None,None,None,None,'Actual LAS active state, unknown. Exactly one active LAS per link requires topology/runtime evidence; not auto true.'),
 ('ff_las_owner','text',None,None,None,None,None,'Actual LAS node identity, unknown. LAS service address4 differs from configured physical node address.'),
 ('ff_las_service_address','number',None,None,4,4,4,'Reserved LAS service address4 baseline; does not allocate node address4 to an ordinary device.'),
 ('ff_node_address','number',None,None,16,255,None,'Actual8-bit node address, unknown. Operational range16..247 differs from cleared248..251 and temporary252..255; LM/BASIC allocation uses actual FUN/NUN.'),
 ('ff_address_state','select',None,['OPERATIONAL','CLEARED','TEMPORARY'],None,None,None,'Actual address allocation category, unknown. A random commissioning address is not a persisted operational default.'),
 ('ff_fun','number',None,None,16,247,None,'Actual boundary of link-master address pool, unknown. Not hard-coded16 or vendor sample20.'),
 ('ff_nun','number',None,None,0,231,None,'Actual unused address count, unknown. BASIC start=FUN+NUN; actual address availability must be checked.'),
 ('ff_link_address','number',None,None,0,65535,None,'Actual logical link16-bit identifier, unknown; may be omitted within a link, needed across bridge.'),
 ('ff_selector','number',None,None,0,255,None,'Actual8-bit selector, unknown. DLCEP and DLSAP reserved allocation depends on VCR and device CFF, not just scalar range.'),
 ('ff_vcr_index','number',None,None,0,None,None,'Actual device-local VCR index, unknown; device-specific capacity and supported index allocation require CFF.'),
 ('ff_pd_tag','text',None,None,None,None,None,'Actual physical-device readable tag, unknown. Tag identity differs from numeric network address.'),
 ('ff_sm_state','select',None,['UNINITIALIZED','INITIALIZED','SM_OPERATIONAL'],None,None,None,'Actual system-management state, unknown. SM_OPERATIONAL is not inferred from address or selected profile.'),
 ('ff_macrocycle_us','number','us',None,0.001,None,None,'Actual configured communication/block macrocycle microseconds, unknown. No universal100ms CAN/application-cycle default.'),
 ('ff_scheduled_us','number','us',None,0,None,None,'Actual total scheduled communication occupied window microseconds. Complete CD/DT/response gaps and other scheduled traffic must be included by schedule source.'),
 ('ff_unscheduled_us','number','us',None,0,None,None,'Actual available unscheduled budget microseconds, unknown; cannot be treated as zero merely because schedule is absent.'),
 ('ff_maintenance_us','number','us',None,0,None,None,'Actual maintenance/synchronization/probing and remaining reserved macrocycle budget microseconds. Budget partition must sum to declared macrocycle.'),
 ('ff_publish_offset_us','number','us',None,0,None,None,'Actual publication offset within macrocycle microseconds, unknown; not block execution completion proof.'),
 ('ff_exchange_bound_us','number','us',None,0.001,None,None,'Actual bounded complete scheduled transaction duration microseconds including CD/DT/gaps/response. Wire telegram duration alone is insufficient.'),
 ('ff_token_hold_us','number','us',None,0.001,None,None,'Actual granted PT token holding interval microseconds, unknown. Different from scheduled DT and NIS request timeout.'),
 ('ff_response_bound_us','number','us',None,0,None,None,'Actual matched CFF/device response bound normalized to microseconds, unknown. Native timer units require source conversion; no sample-device value copied.'),
 ('ff_cable_type','select',None,['TYPE_A','TYPE_B','TYPE_C','TYPE_D','DEVICE_SPECIFIC'],None,None,'TYPE_A','Source-recommended Type A shielded twisted-pair baseline proposal. B/C/D are source reference wiring profiles, not automatically accepted installation designs.'),
 ('ff_trunk_m','number','m',None,0,None,None,'Actual trunk length, unknown. Total segment includes all spurs; nominal1900m Type A is an upper reference limit, not a default length.'),
 ('ff_spurs_total_m','number','m',None,0,None,None,'Actual summed spur lengths, unknown. Per-spur/device-count/reference limits and IS constraints require actual topology source.'),
 ('ff_segment_total_m','number','m',None,0,None,None,'Actual trunk plus summed spurs. Qualified reference limits A1900/B1200/C400/D200m; DEVICE_SPECIFIC requires own verified bounds.'),
 ('ff_terminators','number',None,None,0,None,2,'Baseline two end terminators proposal, not evidence that wiring has two. Different media require their own realization.'),
 ('ff_termination_ohm','number','ohm',None,0.001,None,100,'Nominal100ohm end termination proposal. Actual impedance/tolerance and capacitive coupling require source.'),
 ('ff_terminal_v','number','V',None,0,None,None,'Actual received device voltage, unknown. Reviewed voltage-mode envelope9..32V does not certify selected device/IS barrier operating limits.'),
 ('ff_supply_ma','number','mA',None,0,None,None,'Actual available power-conditioner/barrier current budget, unknown. Not inferred from32-node illustration.'),
 ('ff_devices_ma','number','mA',None,0,None,None,'Actual total device current including limits/reserves, unknown; must fit available current. Individual voltage drops still require evidence.'),
 ('ff_power_source','text',None,None,None,None,None,'Actual voltage-drop/current-budget/power-conditioner/isolator calculation source, unknown.'),
 ('ff_is_required','boolean',None,None,None,None,None,'Actual intrinsic-safety requirement, unknown. It does not claim SIL/safety communication or explosion protection.'),
 ('ff_is_source','text',None,None,None,None,None,'Actual matched intrinsic-safety barrier/device/cable certificate and entity/FISCO design evidence, unknown; required when IS selected.'),
]
removed={key:meaning for key,meaning in (
 ('qos_priority','Native URGENT/NORMAL/TIME_AVAILABLE and SDU limits replace unrelated default3.'),
 ('reserved_bandwidth_percent','Actual LAS schedule/time partitions replace generic reservation0.'),
 ('sync_method','Native LS/application-time synchronization differs from generic NONE/NTP/PTP.'),
 ('retransmission_enabled','VCR flow control, event acknowledgments and token scheduling are distinct; no universal retry switch.'),
 ('retransmission_rate','No universal H1 retry probability0.'),('retry_limit','No universal H1 packet retry0.'),
 ('retransmission_delay_ms','No universal H1 packet retry delay0ms.'),
 ('gateway_maximum_throughput','No universal100M H1 gateway capacity; HSE is a separate transport.'),
 ('gateway_input_buffer','No universal256 gateway buffer.'),('gateway_output_buffer','No universal256 gateway buffer.'),
 ('gateway_maximum_routes','No universal10000 gateway routes.'),('gateway_maximum_messages_s','No universal100000 H1 gateway messages/s.'),
 ('queue_policy','Native VCR BUFFERED/QUEUED declaration replaces generic FIFO policy, not a capacity executor.'),
 ('queue_size','Actual VCR queue resources depend on matched CFF, no fabricated256-entry default.'),
)}
native={k:meaning for k,_,_,_,_,_,_,meaning in declarations}
native.update(bitrate='Fixed nominal31250 bit/s H1 baseline, not configurable CAN rate or100M HSE link.',
              payload_bytes='Actual FMS encoded data0..251 integer octets in qualified DT layout; no8-byte proposal. Full logical domain may require segmentation; lower-frame and priority limits separate.')
spec={'technology':'foundation_fieldbus_h1','native':native,'removed':removed,'sources':[SOURCE,
 'https://www.fieldcommgroup.org/foundation-fieldbus-technical-specifications'],
 'revisions':[REVISION,'FieldComm publisher metadata FF-816FS2.0/FF-821/FF-822 and AG-140/AG-181; licensed normative contents unavailable, not claimed read'],
 'scope':'Every original H1 field independently reviewed. Fixed rate, native FMS/FAS/DLL/physical boundaries, urgency, VCR/LAS roles, addresses and actual schedule/power/wiring declarations typed and checked. Qualified literature baseline proposals remain unconfirmed.',
 'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters + physical_profiles','passed':0},
 'not_certified':['Full licensed FF/IEC normative text and device-specific CFF/firmware limits; declaration bounds do not prove complete protocol conformance',
 'Control-PDU frame layouts, FMS service encoding/segmentation, CRC computation, CFF/DD parsing and native LAS/live-list/token/synchronization executors',
 'Aggregate LAS/VCR/block schedule occupancy, block execution order/E2E functional acceptance, device-count spur constraints, PHY waveform/repeaters/voltage drop and intrinsic-safety certificates; MODEL_MISSING remains']}
(Path(__file__).parent/'foundation-h1-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
