"""Individual CIP Safety decisions; protocol defaults never establish safety proof."""
import json
from pathlib import Path
folder=Path(__file__).resolve().parent
ble=json.loads((folder/'bluetooth_le-review-decisions.json').read_text(encoding='utf-8'))
native={
 'payload_bytes':'Actualsafetyuserdata0..250integerunknown, short<=2/long3..250. Distinctfrom CRC/time/inverteddata andlowertransportframe/fragmentation. Retire1400Ethernetcap/default8. Actualcertifiedassemblycanhavelowerlimits.',
 'cips_transport':'ActualEtherNetIP/DeviceNet/SercosIII requiredunknown,domainneutral. Ownprofilehasnophysicalrate/defaultstackself topreventimplicitCAN/Ethernetborrowing. Actualunderlyingbindings/profilesmustbeexplicitreviewedseparately.',
 'cips_baseline':'MODERN_EXTENDEDproposalversusexplicitCERTIFIED_LEGACY. ODVA2.20..2.22changesdeprecatedBasefornewDOCsince2022;actuallegacyinstalledcertificationrequiresreference. LatestODVApubliccatalogVolume5v2.28April2026, notfullspecread.',
 'cips_format':'EXTENDEDstandardbaselineproposal;BASEpermittedonlyexplicitactualcertifiedlegacybaseline. No automaticconversion/deletionofoldverifieddeviceconfiguration.',
 'cips_max_fault_number':'Actualmaximumfaultnumberunknownnonnegativeinteger. MODERN_EXTENDEDfixed2conditionalproposal/harddeclaredruleperODVA2022; historical5wasdefaultnotuniversalmaximum. No5inmodernprofileorautoconfirmed2.',
 'cips_data_size':'ActualSHORT/LONGsafetydataunknown. Shortupto2bytes usesredundantCRC;long3..250inverteddata+CRC16/24. NotEthernetMTU orCANFDwireDLC.',
 'cips_connection':'ActualUNICAST/MULTICASTunknown. Timecorrectiononlymulticast, coordinationappliesactualendpoints. No oneTCPreliability queue substituted.',
 'cips_consumers':'ActualconnectedSafetyValidatorServercountunknownpositiveinteger. Unicastone; multicast<=15sameproducer. Notwholeplantstationcount or15defaultconsumers.',
 'cips_direction':'ActualINPUT/OUTPUT/PEERunknown. Vendorinput/outputreactionformula/taskdependence differs; do notinferredfromSensor/Actuatorlabelalone.',
 'cips_snn':'Actual48bitsix-bytehexSafetyNetworkNumberunknown, accepts12hexor3groups4. Networkpath+actualnode/portaddress jointlyunique. No generated1/dateauto-confirm; syntacticvaliditydoesnotverifyroutedidentity.',
 'cips_node_reference':'Actuallocalnode/portaddressreferenceunknowntext. DeviceNetMAC/IP/Sercosconfiguredidentityisactualtransport-specific,neverNMEAaddressorCANidentifier.',
 'cips_ip_address':'ActualEtherNetIPaddressunknowntextvalidatedasIP; familyandactualcertifiedprofile/revisionneedverification. RejectedDeviceNet/Sercos, no privateIPdefault orprovenreachablehost.',
 'cips_devicenet_node':'ActualDeviceNetMACID0..63unknown. RejectedEtherNetIP/Sercos; actualduplicateMACcheck/topologyproofrequired. NoCANidentifierorcontrollerdefault0.',
 'cips_production_id':'ActualPIDidentityreferenceunknowntext fromelectronickey/deviceserial/CIPconnectionserial. No arbitraryzero orassumedCANpriority. Completewireencodingandend-to-endidentityproofrequiresfullspec.',
 'cips_configuration_signature':'Actualdeviceconfiguration-signatureunknownreference. Mustmatchactualconfiguration/hardware/firmware/revision; nonemptytextdoesnotcertifySCIDorfunctionaltest.',
 'cips_configuration_owner':'ActualSNCT/originatorownershipunknownreference; notautomaticglobaluser orselfconfigurationauthority.',
 'cips_configuration_locked':'Actualobservedlockingunknownboolean, noTrueproposal orautoFalse. Confirmedparametersdonotperformdeviceconfiguration/lockingorproveSafetyValidatorbehavior.',
 'cips_safety_connection_established':'ActualobservedSafety_Openunknownboolean. NoconnectedTrueproposal. Requiresactualconnectionidentity/timestamps/validatedstate, notworkflowcompletioncard.',
 'cips_device_profile':'ActualDEVICE_SPECIFIC/GUARDLOGIX_SAFETY_IOunknown. Vendorfactory2/200proposals onlyexplicitGuardLogixprofile; deviceRPIlimits/revision/certificationneedactualmanual.',
 'cips_rpi_ms':'Actualrequestedpacketintervalunknownpositivefinite milliseconds. No universal6msencoderor100msNISscenario. GuardLogixOUTPUTequalsactualsafetytaskperiodwhenknown; lowertransportcapacityseparate.',
 'cips_safety_task_ms':'Actualsafetycontroller taskperiodunknownpositivefinite ms. Notdefault10msorCPUprocessing0.1ms; requiredcorrelatedinput/logic/outputreactionbudget.',
 'cips_timeout_multiplier':'ActualpositiveintegerRPImultiplierunknown. GuardLogixnamedprofile1..4withconditionalfactory2proposal. DEVICE_SPECIFICactualhardwarelimitsunknown, notuniversalCANretrycount.',
 'cips_network_delay_percent':'Actualdelaymultiplierpercentunknown>=0finite. GuardLogix10..600withconditionalfactory200proposal. Formulausespercentage/100—not200asfactor; no universalstandard200applicationbound.',
 'cips_crtl_ms':'ActualroundedConnectionReactionTimeLimitunknownpositivefinite ms. Vendorrounding128us anddirectiondependentRPI/taskformula requireactualconfiguredproof; scalarchecksactualage<=limit<=allocatedbudget. No invented40.1default.',
 'cips_data_age_bound_ms':'Actualworst-caseageunknownfinite>=0ms fromproducer toconsumer, includesarbitration/queues/retries/routing/timecoordinationuncertainty. MustfitknownCRTL. Frequencyalonecannotproveage.',
 'cips_application_reaction_limit_ms':'Actualallocatedsafetycommunicationreactionbudgetunknownpositivefinite ms, distinctfromfullmachine/processsafetyreactiontime includingI/O/logic/actuator. NotSIL3orperformancecertification.',
 'cips_time_coordination_bound_ms':'Actualpingcoordinationdelayboundunknownfinite>=0ms. NoNTP/PTPdefault; clockoffset/driftobservations/endpoints neededforCIPtimeexpectation.',
 'cips_time_correction_bound_ms':'Actualmulticasttimecorrectionboundunknownfinite>=0ms; rejectedunicast. Owncontrolpacket withnativeCRC/time,notcopiedEthernetpropagationdelay.',
 'cips_nte_ticks':'ActualNetworkTimeExpectationunknownpositiveinteger128uscounts perODVA2022definition. Fullwidth/connectionvariants/applicabilityneedlicensedcurrentVolume5 andactualdevice,notassumed16bitmaximum.',
 'cips_safety_manual_source':'Actualdevicesafetymanual/model/firmwarerevisionunknowntext. Publicprotocolliterature isnotactualproductcertificateorcapacityprovenance.',
 'cips_conformance_source':'ActualODVADOC/certificationrevisionunknowntext. NoSIL/PLguaranteefromselectedtechnology; fullTADI/PFH/PFD/functionalsafetyengineering separate.'}
spec={'technology':'cip_safety','native':native,'removed':ble['removed'],
 'sources':['https://www.odva.org/technology-standards/distinct-cip-services/cip-safety/',
            'https://www.odva.org/publication_download/cip-safety-safety-networking-for-today-and-beyond-pub-110/',
            'https://www.odva.org/subscriptions-services/specifications/',
            'https://www.odva.org/wp-content/uploads/2022/03/2022-ODVA-Conference_CIP_Safety_Embracing_IEC61784-3_Edition_4_Peng-Seidlitz-Crane-Guru_FINAL.pdf',
            'https://www.rockwellautomation.com/en-pl/docs/add-on-profiles/common/8/pvdnsafetyio2-ditamap/reaction-time-limit-config-dialog/reaction-time-limit-config-dialog-params.html',
            'https://www.rockwellautomation.com/en-gb/docs/technical/logix5000/_online/1756-rm012/guardlogix-5580-and-compact-guardlogix-5580-safety/cip-safety-systems-and-safety-network-numbers/snn-formats.html',
            'https://www.odva.org/technology-standards/key-technologies/devicenet/'],
 'revisions':['ODVApublicprotocolPub110 accessed2026-10-01',
              'ODVA2022IndustryConferenceMarch9 Peng/Seidlitz/Crane/Guru:Volume5v2.22changes/modernExtendedMaxFault2',
              'LatestODVApubliccatalogVolume5v2.28April2026; licensedfullspecnotread',
              'RockwellcurrentAOP8 andGuardLogix safetyreferencedocumentation accessed2026-10-01'],
 'scope':'EveryregisteredCIPSafetyfield, ownextended/legacy baseline, sizes/identities/actualage/vendorconditionaltiming, stricttransportforeignfieldrejection andSQLretention. Safety/capacitycertificationexplicitlyremaining.',
 'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters','passed':0},
 'not_certified':['CurrentlicensedVolume5completeSafety_Open/CRC/PID/SCID/NTEwirefields/variants/optionalparametersnotfullyverifiedfrompublicoverviews',
                  'ActuallowerEtherNetIP/DeviceNet/Sercosbindingstack/rate/PHY/fragmentation andschedulemodel',
                  'Actualdevicesafetycertification/manual/firmware/capability/observedconnection/configurationlocking',
                  'Correlatedactualage/timecoordination/drift/nativeCRC andTADI/PFH/PFD/fullfunctionalreactionproof',
                  'VendorCRTL128usrounding/formulaexecution andcompleteEDSdeviceRPI/timeoutbounds remainunimplemented']}
(folder/'cip_safety-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
