import json
from pathlib import Path
SOURCE='https://www.ti.com/lit/an/slaaeh0/slaaeh0.pdf'
TIMERS='https://support.fieldcommgroup.org/support/solutions/articles/8000040648-how-is-character-time-calculated-'
REVISION='TI SLAAEH0 November2023 sections1.1-1.5 pp2-9; FieldComm character-time support article modified2016-11-11; full licensed HART specifications not read'
declarations=[
 ('hart_profile','select',None,['PUBLIC_FSK_2023','FCG_FSK_2016','DEVICE_SPECIFIC'],None,None,'Actual selected implementation/revision scope. Public FSK rules do not certify C8PSK, WirelessHART or HART-IP.'),
 ('hart_phy','select',None,['FSK','C8PSK'],None,None,'Actual wired modulation. FSK standard baseline1200bit/s; C8PSK9600bit/s is a different mode requiring actual matched modem. HART-IP/WirelessHART need separate transport paths.'),
 ('hart_revision','select',None,['REV5_OR_EARLIER','REV6','REV7','DEVICE_SPECIFIC'],None,None,'Actual peer universal-command revision, unknown. Polling range and command capability must match it; not automatically latest7.'),
 ('hart_role','select',None,['HOST','FIELD_DEVICE'],None,None,'Actual sending endpoint role, unknown. Requests originate at host; response/burst at field device.'),
 ('hart_host_role','select',None,['PRIMARY','SECONDARY'],None,None,'Actual interacting host identity, unknown. Primary/secondary arbitration and quiet times differ; not universal primary master.'),
 ('hart_binding_source','text',None,None,None,None,'Required actual registered modem/port/current-loop binding and both endpoint capabilities, unknown.'),
 ('hart_device_source','text',None,None,None,None,'Required actual device description/revision/commands/preamble and response behavior, unknown.'),
 ('hart_physical_source','text',None,None,None,None,'Required actual impedance/cable/power/coupling/modem/IS/filtering evidence, unknown; nominal FSK rate does not prove installation.'),
 ('hart_schedule_source','text',None,None,None,None,'Required actual host arbitration, command turnaround, retry/burst and complete transaction schedule evidence, unknown.'),
 ('hart_mode','select',None,['REQUEST_RESPONSE','BURST'],None,None,'Actual request/response or device-supported enabled burst mode, unknown. Generic multicast is not wired HART burst.'),
 ('hart_frame_kind','select',None,['REQUEST','RESPONSE','BURST'],None,None,'Actual frame direction/category; status and delimiter differ between request and field response/burst.'),
 ('hart_address_format','select',None,['SHORT','LONG'],None,None,'Actual encoded short1-byte or long5-byte address; long unique identity is distinct from polling number.'),
 ('hart_address_bytes','number','Byte',None,1,5,'Actual address field octets: short1, long5. No arbitrary2/3/4-byte encoding.'),
 ('hart_poll_address','number',None,None,0,63,'Actual device polling number, unknown: rev5-or-earlier0..15, rev6+0..63. Point-to-point0 is a proposal, not a real device assignment.'),
 ('hart_topology','select',None,['POINT_TO_POINT','MULTIDROP'],None,None,'Actual current-loop topology, unknown. Multidrop analog fixed-current behavior requires actual revision/device configuration.'),
 ('hart_expanded_device_type','number',None,None,0,16383,'Actual14-bit expanded device type in qualified long-address layout, unknown; not an automatically generated device identifier.'),
 ('hart_device_id','number',None,None,0,16777215,'Actual24-bit device ID in qualified long-address layout, unknown; host and burst flags are separate.'),
 ('hart_preamble_bytes','number','Byte',None,5,20,'Actual transmitted0xFF preamble octets in public FSK profile. Peer-specific required length and detection loss matter;5 is not a safe default for every unknown peer.'),
 ('hart_peer_preamble_bytes','number','Byte',None,5,20,'Actual required preamble length learned from matching field device, unknown. Configured transmit preamble must be at least this.'),
 ('hart_delimiter','number',None,None,0,255,'Actual delimiter octet; qualified FSK encodes address length, expansion count and frame category. C8PSK delimiter rules not inferred from asynchronous FSK.'),
 ('hart_expansion_bytes','number','Byte',None,0,3,'Actual encoded expansion bytes matching delimiter. Normal0 proposal belongs to qualified public FSK layout; future extensions need revision evidence.'),
 ('hart_command','number',None,None,0,255,'Actual wire command octet, unknown. Command31 carries extended16-bit command in data; command support and response semantics remain device-specific.'),
 ('hart_extended_command','number',None,None,0,65535,'Actual16-bit extended command when wire command31, unknown; its two bytes must be included in transmitted data length, not extra hidden overhead.'),
 ('hart_command_source','text',None,None,None,None,'Actual supported command, request/response data layout, units and encoding source, unknown. Generic data length does not prove functional command compatibility.'),
 ('hart_status_bytes','number','Byte',None,0,2,'Actual status length: request0, field response/burst2 in qualified FSK layout.'),
 ('hart_data_bytes','number','Byte',None,0,255,'Actual encoded data octets excluding response status, including extended-command bytes when present. Request/response layouts differ; no8-byte default.'),
 ('hart_byte_count','number','Byte',None,0,255,'Actual byte-count field = data plus status octets, excluding checksum. Response data at most253 when status2; not a universal complete255-byte frame limit.'),
 ('hart_checksum_bytes','number','Byte',None,1,1,'One transmitted XOR checksum octet in qualified public FSK layout; checksum covers delimiter through data, excluding preamble. Numeric length is not executed integrity evidence.'),
 ('hart_checksum_source','text',None,None,None,None,'Actual XOR calculation and observed parity/byte stream evidence, unknown; no auto-confirmed checksum or authentication.'),
 ('hart_wire_octets','number','Byte',None,0,None,'Actual whole frame incl preamble/delimiter/address/expansion/command/count/status/data/checksum. Separate from data and byte count.'),
 ('hart_char_bits','number','bit',None,11,11,'FSK asynchronous character:1start+8dataLSB-first+odd parity+1stop=11bits. These bounds apply only to selected qualified FSK profile; not generic8N1.'),
 ('hart_wire_bits','number','bit',None,0,None,'Actual serialization bits including all qualified FSK characters, not payload×8. C8PSK encoded stream needs actual physical evidence.'),
 ('hart_serialization_ms','number','ms',None,0,None,'Actual frame serialization time from complete encoded bits and selected physical rate, excluding turnaround/gaps/arbitration; not whole transaction latency.'),
 ('hart_gap_us','number','us',None,0,None,'Actual worst inter-character gap; qualified FCG FSK rule requires less than one11-bit character time. No universal gap0 default.'),
 ('hart_slave_timeout_chars','number','character',None,28,28,'Qualified FieldComm2016 FSK slave timeout28character times; timeout is not actual device processing latency or application deadline.'),
 ('hart_hold_chars','number','character',None,2,2,'Qualified FieldComm2016 FSK HOLD2character times, separate from frame serialization and actual modem turnaround.'),
 ('hart_link_grant_chars','number','character',None,8,8,'Qualified FieldComm2016 FSK link grant RT2=8character times.'),
 ('hart_quiet_chars','number','character',None,0,None,'Qualified FieldComm2016 FSK RT1 primary33/secondary41character times. Master identity must be explicit.'),
 ('hart_response_start_ms','number','ms',None,0,None,'Actual request-end to response-start upper bound incl device and modem, unknown; qualified FCG timeout relation applies. Does not include response duration.'),
 ('hart_retry_limit','number','attempts',None,0,None,'Actual host/device retry budget, unknown; no inherited CAN0 or Siemens client-specific universal value.'),
 ('hart_retry_bound_ms','number','ms',None,0,None,'Actual total additional retry/arbitration recovery bound, unknown. Per-message or transport-independent timeout cannot substitute.'),
 ('hart_burst_supported','boolean',None,None,None,None,'Actual endpoint burst capability confirmed by device source, unknown; enabling mode must not fabricate support.'),
 ('hart_burst_period_ms','number','ms',None,0,None,'Actual device/revision configured burst schedule, unknown. Tutorial3-4updates/s is illustrative, not a universal standard period.'),
 ('hart_loop_load_ohms','number','Ohm',None,230,600,'Actual loop receiver resistor/communication load for qualified TI FSK example230..600Ohm, typically250. Bounds are not universal total loop impedance; device-specific topology requires actual source.'),
 ('hart_loop_supply_v','number','V',None,0,None,'Actual loop supply and device compliance budget, unknown; not a universal24V supply.'),
 ('hart_loop_current_ma','number','mA',None,0,None,'Actual operating analog loop current, unknown;4..20mA measurement range and multidrop fixed current are not arbitrary digital defaults.'),
 ('hart_signal_pp_ma','number','mA',None,0,None,'Actual FSK signal amplitude at matched load, unknown.1mApp is nominal tutorial value, not measured endpoint evidence.'),
 ('hart_cable_cap_pf','number','pF',None,0,None,'Actual cable/receiver capacitance and length/loading bound, unknown; not I2C400pF or an inferred universal cable length.'),
 ('hart_is_required','boolean',None,None,None,None,'Actual hazardous-area/intrinsic-safety requirement, unknown; HART name does not imply certified safe installation.'),
 ('hart_is_source','text',None,None,None,None,'Actual matched barriers/entities/cable/loop intrinsically-safe certification evidence, unknown; separate from message checksum.'),
]
removed={key:meaning for key,meaning in {
 'queue_size':'No universal HART256-frame queue; actual host modem/stack buffer evidence is required.',
 'queue_policy':'No universal HART FIFO schedule; half-duplex dual-host access and burst rules govern actual arbitration.',
 'qos_priority':'HART FSK has no CAN priority3 or Ethernet PCP; primary/secondary host identity is separate.',
 'reserved_bandwidth_percent':'No universal HART reserved bandwidth0%; actual host/burst transaction schedule is required.',
 'sync_method':'No NTP/PTP time-sync fallback for wired HART; FSK preamble character synchronization differs.',
 'retransmission_enabled':'Actual HART retry capability and policy require matched endpoint source; no generic network retransmission switch.',
 'retransmission_rate':'No universal HART retry probability0; actual retry bound and budget are separate.',
 'retry_limit':'Use actual native HART host retry budget; inherited generic0 is unsourced.',
 'retransmission_delay_ms':'Use actual native retry/arbitration bound, not generic0ms.',
 'gateway_maximum_throughput':'No100Mbit/s HART gateway default; modem loop capacity and actual upstream binding are separate.',
 'gateway_input_buffer':'No universal256-frame HART gateway input buffer.',
 'gateway_output_buffer':'No universal256-frame HART gateway output buffer.',
 'gateway_maximum_routes':'No universal10000 HART gateway routes.',
 'gateway_maximum_messages_s':'No universal100000message/s HART gateway capacity.'}.items()}
native={key:meaning for key,_,_,_,_,_,meaning in declarations}
native.update({'bitrate':'Actual selected wired HART rate: FSK1200 vs C8PSK9600bit/s; baselineFSK1200 source-backed proposal, no Ethernet/WirelessHART fallback.',
 'payload_bytes':'Actual encoded HART data length excluding response status, equal hart_data_bytes when both supplied; wire/count/status/extended-command framing reviewed separately; no universal8-byte default.'})
spec={'technology':'hart','native':native,'removed':removed,
 'sources':[SOURCE,TIMERS,'https://www.fieldcommgroup.org/hart-specifications','https://www.analog.com/en/resources/app-notes/an-534.html'],
 'revisions':[REVISION,'Public primary references; licensed full FCG TS200xx editions and actual device command descriptions not available'],
 'scope':'Every original HART field and every new modulation/revision/role/frame/address/physical/transaction field individually reviewed. Explicit wired FSK baseline vs actual C8PSK, qualified public framing/timers, no foreign CAN/Ethernet defaults.',
 'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters + physical_profiles','passed':0},
 'not_certified':['Full licensed HART revision conformance, actual command payload codec, XOR/parity execution and C8PSK encoded symbols',
 'Actual dual-master/burst/retry transaction timing, loop loading/power/cable/modem/IS hardware and measurements',
 'HART-IP/WirelessHART and RS485/vendor encapsulations are separate actual transport paths; no automatic wired-FSK capacity for them']}
(Path(__file__).parent/'hart-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
