import json
from pathlib import Path
SOURCE='https://www.rfc-editor.org/rfc/rfc9110.html'
REVISION='RFC9110/9112/9113/9114 June2022; RFC9204 June2022; RFC9931 March2026 updates RFC9112 optimistic transition handling'
declarations=[
 ('http_version','select',None,['HTTP_1_1','HTTP_2','HTTP_3'],None,None,'Actual protocol version, unknown. Different text/binary/QUIC framing and flow control; no latest-version default.'),
 ('http_transport','select',None,['TCP','QUIC_V1','DEVICE_SPECIFIC'],None,None,'Actual selected transport, unknown. HTTP2TCP and HTTP3QUIC differ; HTTP1 custom reliable transport needs matched implementation source.'),
 ('http_binding_source','text',None,None,None,None,'Required actual registered TCP/TLS or QUIC/IP/physical path and peer endpoints, unknown; no automatic Ethernet100M or TCP mapping for all versions.'),
 ('http_implementation_source','text',None,None,None,None,'Required actual client/server/proxy version, supported negotiated protocol and resource limits, unknown.'),
 ('http_schedule_source','text',None,None,None,None,'Required actual handshake/application/flow-control/transport recovery/concurrency schedule evidence, unknown; HTTP defines no universal deadline.'),
 ('http_role','select',None,['CLIENT','SERVER','PROXY'],None,None,'Actual endpoint role, unknown. Response, push and settings direction depend on role; proxy requires each actual leg.'),
 ('http_message_kind','select',None,['REQUEST','RESPONSE'],None,None,'Actual message direction; method/status/body semantics differ.'),
 ('http_scheme','select',None,['http','https'],None,None,'Actual origin scheme, unknown. Default ports80/443 are proposals only when origin has no explicit port, not all endpoints.'),
 ('http_port_explicit','boolean',None,None,None,None,'Whether actual origin contains explicit port, unknown; false permits scheme-default proposal, never overwrites explicit13500 etc.'),
 ('http_port','number',None,None,1,65535,'Actual endpoint port, unknown; scheme-default80/443 proposal only when port elided.'),
 ('http_origin','text',None,None,None,None,'Actual http(s) origin/resource URI, unknown; nonempty host, no embedded credentials or fragment. Request-target forms are separate.'),
 ('http_method','text',None,None,None,None,'Actual case-sensitive method token, unknown; extension tokens allowed, no universal GET command.'),
 ('http_status','number',None,None,100,599,'Actual response status100..599; unknown/reserved3-digit statuses retain class semantics. Not mandatory for requests.'),
 ('http_target_form','select',None,['ORIGIN','ABSOLUTE','AUTHORITY','ASTERISK'],None,None,'Actual HTTP1 request-target form. CONNECT authority, OPTIONS asterisk and proxy absolute target differ from HTTP2/3 pseudoheaders.'),
 ('http_target_source','text',None,None,None,None,'Actual URI/Host/:authority/:scheme/:path and target normalization/route evidence, unknown; no automatic URL constructed from device name.'),
 ('http_tls_version','select',None,['TLS_1_2','TLS_1_3','DEVICE_SPECIFIC'],None,None,'Actual negotiated security version, unknown. HTTP3 QUICv1 TLS1.3; HTTP2TLS at least1.2; actual certificate/ALPN acceptance separate.'),
 ('http_security_source','text',None,None,None,None,'Actual negotiated TLS/QUIC certificate/origin authentication/ALPN/cipher/0RTT policy evidence, unknown.'),
 ('http_framing','select',None,['NONE','CONTENT_LENGTH','CHUNKED','CLOSE_DELIMITED','TUNNEL','MULTIPLEXED'],None,None,'Actual selected message framing. HTTP1 chunk/close differ from HTTP2/3 stream framing; successful CONNECT becomes tunnel.'),
 ('http_transfer_encoding','select',None,['NONE','CHUNKED','OTHER'],None,None,'Actual HTTP1 Transfer-Encoding final coding; not content compression. HTTP2/3 forbid Transfer-Encoding, though TE:trailers differs.'),
 ('http_transfer_source','text',None,None,None,None,'Actual transfer coding chain/chunk extensions/final terminator/trailers source, unknown; raw byte parsing not proven by counters.'),
 ('http_content_length_present','boolean',None,None,None,None,'Actual presence of Content-Length, unknown. Sender must not combine with Transfer-Encoding; HEAD/304 may report selected-representation length.'),
 ('http_content_length','text','Byte',None,None,None,'Actual nonnegative decimal Content-Length with no protocol-wide upper bound; text preserves arbitrary exact digits without JS precision loss.'),
 ('http_length_semantics','select',None,['MESSAGE_BODY','SELECTED_REPRESENTATION'],None,None,'Actual Content-Length semantic target, unknown; HEAD/304 metadata can differ from transmitted empty content.'),
 ('http_body_bytes','text','Byte',None,None,None,'Actual transmitted content octets as exact decimal text. No65535 maximum or8-byte default; excludes chunk framing and HTTP2 padding.'),
 ('http_wire_message_bytes','text','Byte',None,None,None,'Actual whole encoded HTTP message/stream octets as exact decimal text, unknown. Compression/headers/chunks/frame boundaries are not inferred from content.'),
 ('http_encoding_source','text',None,None,None,None,'Actual encoded content/header/trailer/chunk/HPACK/QPACK representation and whole message evidence, unknown.'),
 ('http_acceptance_source','text',None,None,None,None,'Actual application acceptance/units/idempotence/retries/cache/proxy/response correlation evidence, unknown; transport delivery is not functional acceptance.'),
 ('http_request_timeout_ms','number','ms',None,0,None,'Actual implementation/application request deadline, unknown; no universal HTTP100/500ms standard.'),
 ('http_retry_limit','number','attempts',None,0,None,'Actual application retry policy and idempotence/source evidence, unknown; HTTP retries differ from TCP/QUIC retransmission.'),
 ('http_retry_source','text',None,None,None,None,'Actual method idempotence/replay/partial-processing and retry acceptance evidence, unknown. A lost response does not prove request was not applied.'),
 ('http_transition_optimistic','boolean',None,None,None,None,'Actual optimistic HTTP1 Upgrade/CONNECT behavior, unknown; RFC9931 requires explicit safety relative to possible HTTP misinterpretation.'),
 ('http_transition_source','text',None,None,None,None,'Actual negotiated transition/confirmation and harmless-prefix/smuggling risk evidence per RFC9931, unknown; tunnel is not auto-safe.'),
 ('http2_frame_type','select',None,['DATA','HEADERS','PRIORITY','RST_STREAM','SETTINGS','PUSH_PROMISE','PING','GOAWAY','WINDOW_UPDATE','CONTINUATION','EXTENSION'],None,None,'Actual HTTP2 frame type, unknown; fixed-type payloads and stream scope differ.'),
 ('http2_stream_id','number',None,None,0,2147483647,'Actual31-bit HTTP2 stream ID; DATA/HEADERS on nonzero streams; connection frames stream0. No defaultassigned stream1.'),
 ('http2_frame_header_bytes','number','Byte',None,9,9,'HTTP2 fixed9-octet header proposal only for actual HTTP2. Excluded from SETTINGS_MAX_FRAME_SIZE.'),
 ('http2_frame_payload_bytes','number','Byte',None,0,16777215,'Actual24-bit HTTP2 frame payload, incl padding/pad length if used; at most actual receiver-advertised max, distinct from content/message.'),
 ('http2_frame_bytes','number','Byte',None,9,16777224,'Actual HTTP2 frame9+payload octets; not TCP segment or Ethernet frame length.'),
 ('http2_settings_phase','select',None,['INITIAL_DEFAULTS','PEER_ADVERTISED'],None,None,'Actual settings state. Normative initial values can be proposed only before peer values are supplied; never overwrite peer advertisements.'),
 ('http2_max_frame_size','number','Byte',None,16384,16777215,'Actual peer SETTINGS_MAX_FRAME_SIZE range16384..16777215; initial16384 proposal. Not message-body maximum.'),
 ('http2_header_table_size','number','Byte',None,0,4294967295,'Actual HPACK SETTINGS_HEADER_TABLE_SIZE uint32, initial4096 proposal; negotiated decoder context differs from uncompressed field size.'),
 ('http2_initial_window_size','number','Byte',None,0,2147483647,'Actual SETTINGS_INITIAL_WINDOW_SIZE stream limit, initial65535 proposal; current stream/connection windows change independently.'),
 ('http2_current_stream_window','number','Byte',None,None,2147483647,'Actual remaining stream flow-control window. Can be negative after SETTINGS decrease; negative window permits no DATA, no unsigned fallback.'),
 ('http2_current_connection_window','number','Byte',None,0,2147483647,'Actual remaining connection DATA window; initial65535, WINDOW_UPDATE changes it. Not changed by stream SETTINGS.'),
 ('http2_enable_push','number',None,None,0,1,'Actual SETTINGS_ENABLE_PUSH0/1; initialclient1, serverinitial value has no effect equivalent0. Actual support/state required.'),
 ('http2_max_concurrent_streams','number',None,None,0,4294967295,'Actual advertised uint32 limit, initially unlimited if absent; no fabricated100/256-stream maximum.'),
 ('http2_max_header_list_bytes','number','Byte',None,0,4294967295,'Actual advisory uncompressed field-list limit incl32bytes per field; initially unlimited if absent, not a zero-byte default.'),
 ('http2_pad_length_present','boolean',None,None,None,None,'Actual PADDED flag and one-byte PadLength presence for DATA/HEADERS/PUSH_PROMISE, unknown.'),
 ('http2_padding_bytes','number','Byte',None,0,255,'Actual padding octets0..255 when PADDED, excluding1-byte PadLength; all are part of frame payload and DATA flow-control cost.'),
 ('http2_data_bytes','number','Byte',None,0,16777215,'Actual content inside DATA frame excluding padding/PadLength; distinct from complete message content and receiver window cost.'),
 ('http3_frame_type','text',None,None,None,None,'Actual QUIC-varint HTTP3 frame type0..2^62-1 as exact decimal text. Separate registry from HTTP2.'),
 ('http3_frame_length','text','Byte',None,None,None,'Actual QUIC-varint HTTP3 frame payload length0..2^62-1 as exact decimal text; no9-byte header or16384 maximum inherited from HTTP2.'),
 ('http3_stream_kind','select',None,['REQUEST','CONTROL','PUSH','QPACK_ENCODER','QPACK_DECODER','EXTENSION'],None,None,'Actual QUIC stream kind: DATA/HEADERS request or push; SETTINGS control. QPACK streams are independent byte streams.'),
 ('http3_qpack_max_table','text','Byte',None,None,None,'Actual SETTINGS_QPACK_MAX_TABLE_CAPACITY uint62 as exact decimal text, initial0; not HTTP2 HPACK4096 default.'),
 ('http3_qpack_blocked_streams','text',None,None,None,None,'Actual SETTINGS_QPACK_BLOCKED_STREAMS uint62 as exact decimal text, initial0; blocking/recovery remains actual QUIC/QPACK schedule.'),
 ('http3_max_field_section_bytes','text','Byte',None,None,None,'Actual advertised uint62 maximum field-section size as exact decimal text; absent means unlimited, not0 or HTTP2 frame-size limit.'),
 ('http3_settings_phase','select',None,['INITIAL_1RTT','PEER_ADVERTISED','RESUMED_0RTT'],None,None,'Actual HTTP3 settings state.1RTT initial defaults differ from remembered0RTT peer values; do not overwrite remembered settings.'),
 ('http3_quic_source','text',None,None,None,None,'Actual QUIC version, varint widths, stream limits, flow control, recovery and congestion/pacing source, unknown; no assumed TCP schedule.'),
]
declarations.extend([('http_transition_token',
  'select',
  None,
  ['TLS', 'WEBSOCKET', 'CONNECT_UDP', 'CONNECT_IP', 'CONNECT_TCP', 'DEVICE_SPECIFIC'],
  None,
  None,
  'Actual upgrade/CONNECT protocol, unknown. RFC9931 distinguishes TLS, WebSocket, UDP/IP tunneling and '
  'untrusted TCP CONNECT; source alone does not override prohibited optimistic sending.'),
 ('http_connect_untrusted',
  'boolean',
  None,
  None,
  None,
  None,
  'Actual CONNECT forwarding on behalf of untrusted TCP client, unknown. Do not assume trusted false; '
  'wait-success or Connection:close required for HTTP1.'),
 ('http_wait_success',
  'boolean',
  None,
  None,
  None,
  None,
  'Actual proxy waits for successful2xx before forwarding TCP payload, unknown. Distinct from application '
  'deadline and declared source text.'),
 ('http_connection_close',
  'boolean',
  None,
  None,
  None,
  None,
  'Actual Connection:close request/rejection connection behavior. HTTP1 untrusted CONNECT requires close or '
  'wait; rejecting proxy must close underlying connection under RFC9931.'),
 ('http_transition_rejected',
  'boolean',
  None,
  None,
  None,
  None,
  'Actual CONNECT transition rejection state, unknown. Underlying connection must be closed by HTTP1 '
  'rejecting proxy without processing further requests.')])
removed={
 'rate_limit_bit_s':'Removed inherited network rate limiter: HTTP has no universal link bitrate or shaping rule; any actual shaping belongs to its explicit transport/path evidence.',
 'mtu_bytes':'HTTP has no universal65535 application MTU; actual TCP/QUIC path, body length, HTTP2 frame and HTTP3 varints are distinct.',
 'vlan_id':'No HTTP-specific VLAN0; any actual L2 link/tag requires an independently bound physical profile.',
 'duplex':'No HTTP-specific Ethernet full-duplex default; actual lower-layer link owns it.',
 'qos_priority':'No HTTP-specific CAN3/Ethernet PCP default; actual scheduling/priority extension differs.',
 'reserved_bandwidth_percent':'No universal HTTP reserved-bandwidth0 guarantee.',
 'sync_method':'HTTP does not universally require NTP/PTP timing synchronization.',
 'queue_size':'No universal HTTP256-frame queue; actual HTTP streams/implementation buffers differ.',
 'queue_policy':'No universal HTTP FIFO schedule; multiplexing and actual implementation priorities differ.',
 'retransmission_enabled':'HTTP application replay is separate from actual TCP/QUIC transport retransmission.',
 'retransmission_rate':'No universal HTTP transport retry probability0.',
 'retry_limit':'Native HTTP application retry policy/source is actual; no inherited CAN retry0.',
 'retransmission_delay_ms':'No universal HTTP retransmission0ms; actual bound transport recovery must be verified.',
 'gateway_maximum_throughput':'No100Mbit/s HTTP proxy/gateway default; each actual leg needs its own transport rate/evidence.',
 'gateway_input_buffer':'No universal256-frame HTTP proxy input buffer.',
 'gateway_output_buffer':'No universal256-frame HTTP proxy output buffer.',
 'gateway_maximum_routes':'No universal10000 HTTP proxy routes.',
 'gateway_maximum_messages_s':'No universal100000 HTTP transaction/s capacity.'}
# Original HTTP inherited Ethernet bitrate is removed along with the implicit physical stack.
removed['bitrate']='HTTP has no physical bitrate. Select actual TCP/QUIC and physical bindings; no inherited10M Ethernet fallback or CAN500k.'
native={key:meaning for key,_,_,_,_,_,meaning in declarations}
native['payload_bytes']='Actual NIS application-chunk octets, no8-byte default or65535 maximum. Full exact HTTP content/message lengths are decimal-text native fields; transport/frame capacities separately verified.'
spec={'technology':'http','native':native,'removed':removed,
 'sources':[SOURCE,'https://www.rfc-editor.org/rfc/rfc9112.html','https://www.rfc-editor.org/rfc/rfc9113.html',
            'https://www.rfc-editor.org/rfc/rfc9114.html','https://www.rfc-editor.org/rfc/rfc9204.html','https://www.rfc-editor.org/rfc/rfc9931.html'],
 'revisions':[REVISION],
 'scope':'Every original and new HTTP message/version/transport/body/frame/settings/role/timing parameter individually reviewed. Own HTTP1, HTTP2 and HTTP3 rules, exact decimal lengths and normative conditional initial settings; no universal physical stack/rate/MTU.',
 'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters + physical_profiles','passed':0},
 'not_certified':['Complete executed HTTP1 parser/chunking/HPACK/QPACK/QUIC stream and state machine, custom version/transport/extensions and RFC9931 transition safety',
 'Actual TCP/TLS/QUIC and physical path capacity, stateful advertised windows, concurrency, recovery/cache/proxy and request-to-response timing',
 'Actual functional acceptance, authentication/trust, retry idempotence and capacity execution; supplied source references alone do not prove conformance']}
(Path(__file__).parent/'http-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
