"""Explicit DNP3 layered sizes, actual peer facts and implementation-qualified defaults."""
import json
from pathlib import Path

folder=Path(__file__).resolve().parent
native={
    'payload_bytes':'Actual complete encoded application message including headers unknown nonnegative integer octets; can span multiple application fragments. Retire2048 universal message cap and fabricated8B actual payload.',
    'dnp_role':'Required actual MASTER/OUTSTATION role unknown; applies independently per endpoint/association, no automatic master or electrical industry inference.',
    'dnp_transport':'Required actual SERIAL/TCP/UDP/TLS/SCTP/DEVICE_SPECIFIC transport unknown. DNP3 does not define ownbaud/rate; actual lower profile provides physical facts.',
    'dnp_transport_binding':'Required actual selected lower TechnologyProfile/path reference unknown; reference validity and real transport execution not certified by string.',
    'dnp_configuration_source':'Required actual matched IEEE1815 edition/subset/device-profile/configuration source unknown; primer2005 expressly informal and not formal full specification. No inferred supported edition.',
    'dnp_implementation':'Actual STEPFunction1.6 or other implementation unknown; selecting version allows its source-qualified defaults, no claimed installed version or generic standard timings.',
    'dnp_master_address':'Actual individual master link address unknown integer0..65519; distinct from knownoutstation address, no default0/1 and no broadcast/source reserved address.',
    'dnp_outstation_address':'Actual individual outstation link address unknown integer0..65519; distinct from knownmaster, no automatic1 or physical CANnode address.',
    'dnp_destination_mode':'Actual unicast/self/threebroadcast confirmation modes unknown. SELF65532 and broadcasts65533/4/5 distinct from reserved65520..65531.',
    'dnp_destination_address':'Actual16-bit destination unknown; rejects reserved65520..65531 even withoutmode. Unicast<=65519; selected self/broadcast requires exactmatched address. Device support/operationalbroadcast security unknown.',
    'dnp_port':'ActualIP service port unknown integer1..65535; IANA20000 proposal onlyTCP/UDP/SCTP. RejectedforSERIAL; secureTLSactualport remainsunknown, IANA19999 secureassignment alone not universallyTLS configuration.',
    'dnp_link_user_bytes':'Actual linkuserdata unknown0..250 octets excludingCRC and including transportheader whenpresent; not entireapplicationmessage.',
    'dnp_link_length_field':'Actuallengthfield unknown5..255 integer; equals5+knownlinkuseroctets and excludes sync,length itself,andCRCs. Not totalwireframe length.',
    'dnp_link_frame_bytes':'Actualcompletewireframe unknown10..292 octets; equals10+userdata+2ceil(userdata/16), includingCRC on finalpartialblock; emptylinkcontrol frame10.',
    'dnp_transport_data_bytes':'Actualapplication octets in selectedtransportsegment unknown0..249; equalsknownpositive linkuserdata minus1header. Absentforzero-user linkcontrol frame.',
    'dnp_fragment_limit_bytes':'Typical2048B initial proposal perDNPUGprimer2005/Openlibrary2048default, not normativeminimum or complete-messagecap. Positiveinteger adjustable; <=known actualpeerRXbuffer.',
    'dnp_peer_rx_buffer_bytes':'Actualmatchedreceivingpeer transport reassemblybuffer unknown positiveinteger octets.4096typicalexample notmax; no installedmemory/capacity inferred.',
    'dnp_application_fragment_bytes':'Actualencodedapplicationfragment unknowninteger>=2; <=knownproposedfragmentlimit/peerbuffer/completeencodedmessage. RESPONSE/UNSOL minimum4; objectheaders and dataformats separate.',
    'dnp_application_kind':'Actual REQUEST/RESPONSE/UNSOLICITED_RESPONSE unknown; unsolicited not allowedifoutstationreporting explicitlyfalse. Zeroobject initialunsolicited response may leaveclassabsent.',
    'dnp_link_confirm':'Actualoptional link-layer confirmation unknownboolean; no defaultFalse or universal serialTrue. Distinct fromapplicationconfirm and TCP ACK.',
    'dnp_link_confirm_timeout_ms':'Actualpositivefinite linkconfirmation timeout unknownms; rejectedwhenlinkconfirmationFalse. Vendor3s/1s examples notuniversal.',
    'dnp_link_retries':'Actualnonnegativeinteger linkconfirmation retries unknown; rejectedwhenlinkconfirmFalse. Not genericprobabilistic retry3.',
    'dnp_response_timeout_ms':'Actualmaster association response timeout unknownpositivefinite ms; OUTSTATIONinapplicable. DoesnotreuseNIS500ms or unsupportedgenericdefault.',
    'dnp_app_confirm_timeout_ms':'Actualoutstation applicationconfirm timeout unknownpositivefinite ms; conditionalSTEPFUNC1.6/OUTSTATIONproposal5000. SeparatelinkACK/middlewareblocking and functionaldeadline.',
    'dnp_select_timeout_ms':'Actualoutstation select-before-operate expiry unknownpositivefinite ms; conditionalSTEPFUNC1.6/OUTSTATIONproposal5000. No executedmatchingSELECT/OPERATEstateproof.',
    'dnp_unsolicited_enabled':'Actualoutstation unsolicitedenabled unknownboolean; source-qualifiedSTEPFUNC1.6featureTrueproposal onlyoutstation. Realpeer supportedfeature/enablehandshake/medium contention stillunknown.',
    'dnp_unsolicited_retry_mode':'Actualoutstation FINITE/UNLIMITED limitmode unknown; STEPFUNC1.6None default givesconditionalUNLIMITED proposal, notfinite0.',
    'dnp_max_unsolicited_retries':'Actualfinite non-regenerated unsolicited retries unknownnonnegativeinteger. RejectedunderUNLIMITED; regeneration/series timing/state implementation remainsunverified.',
    'dnp_unsolicited_retry_delay_ms':'Actualoutstation delay betweenretryseries unknownfinite>=0ms; STEPFUNC1.6/OUTSTATIONconditional5000. Not confirmationtimeout or CANprobabilisticretry.',
    'dnp_keepalive_enabled':'Actuallink inactivity REQUEST_LINK_STATUS enabled unknownboolean; STEP1.6MASTERFalse/OUTSTATIONTrue conditionalproposals. Disabled differsfromtimer0.',
    'dnp_keepalive_ms':'Actualpositivefinite inactivityduration unknownms; conditionalSTEP1.6OUTSTATIONenabled60000, rejectedwhenexplicitlydisabled. Notperiodicpoll or applicationdeadline.',
    'dnp_auto_retry_min_ms':'Actualmaster automatic-task backoffminimum unknown>=0ms; no genericretrydelay. Mustfitknownmax; exactexponentialpolicy source required.',
    'dnp_auto_retry_max_ms':'Actualmaster automatic-task backoffmaximum unknown>=0ms and>=knownminimum; no universally5sdefault.',
    'dnp_data_class':'Actual staticCLASS0/eventCLASS1/2/3 unknown. Objectclass assignedbyapplication; not automaticallynumericpriority or EthernetQoS. Explicitunsolicitedevent classcannotCLASS0.',
    'dnp_group':'Actualencodedobjectgroup unknown8-bitinteger0..255. Scalarwidthchecknotvalidgroup membership; actualedition/devicegroupvariation combination requiresmapping.',
    'dnp_variation':'Actualencodedobjectvariation unknown8-bitinteger0..255. Samevariationnumbermeansdifferentformatacrossgroups; node support/defaultvariation selection notinferred.',
    'dnp_object_mapping_source':'Actualgroup/variation/index/qualifier/flag/time/encoding contract unknownreference; no inventedanalog16-bitrepresentation or completeobjectlibraryconformance.',
    'dnp_point_index_start':'Actualfirstzero-basedpointindex unknown16-bitinteger0..65535, qualifier/source mapping mustmatch. No fabricatedactualpoint0.',
    'dnp_point_index_end':'Actuallastpointindex unknown16-bitinteger>=knownfirst;8-bitqualifierrestrictions and registeredactualpoints requirematchedmapping.',
    'dnp_event_buffer_source':'Actualper-objecttype eventcapacities/overflow/discard/classscan source unknown; a fixed256gatewaybuffer cannot standfor eventdatabase.',
    'dnp_medium_access_source':'Actualunsolicitedshared-medium access/turnaround/arbitration policy unknownreference; DNPUG leavesalgorithmtoimplementer. No automaticCANbitwisearbitration.',
    'dnp_time_sync':'ActualDISABLED/LAN/NON_LAN/DEVICE_SPECIFIC procedure unknown; conditionalSTEP1.6MASTERDISABLED fromauto_time_syncNone. NotPTP/NTP/gPTP or observedaccuracy.',
    'dnp_time_sync_source':'Actualclock/time/delay/NEED_TIME/timestamp/acceptance contract unknownreference;procedurechoicealone no verifiedclockprecision.',
    'dnp_control_mode':'ActualSELECT_BEFORE_OPERATE/DIRECT_OPERATE/DIRECT_OPERATE_NO_ACK unknown; no automaticallyverifiedactuatorcommand or functionalresponseacceptance.',
    'dnp_security_mode':'ActualNONE/TLS_ONLY/SA_ONLY/TLS_AND_SA/DEVICE_SPECIFIC unknown. SelectedTLS requirescompatibleTLSmode; SA authenticatesapplication, not automaticallyTLS encryption.',
    'dnp_security_source':'ActualTLSpeercredentials/ciphers/certificates/SAedition/keys/userroles/source unknownreference. No claimed securetransport or installedtrust fromenum.'
}
removed={
    'qos_priority':'No universalPCP3 maps DNP3 eventclass or pollingpriority.',
    'sync_method':'DNP3LAN/nonLAN NEED_TIME procedure is separatefromEthernetPTP/gPTP/NTP.',
    'reserved_bandwidth_percent':'No universalDNP3 reservationpercentage; actuallowertransport budget separate.',
    'retransmission_enabled':'Replace genericFalse with distinct actualoptional linkconfirm and applicationunsolicited retry policies.',
    'retransmission_rate':'No universalDNP3probabilistic retryrate; explicitlink/appstate and actual lowertransport retries differ.',
    'retry_limit':'Generic0 retry countdoesnotrepresent optionallink or unlimited/finiteunsolicited policies.',
    'retransmission_delay_ms':'Generic0ms delaydoesnotrepresent link/appconfirm/backoff/seriesdelay.',
    'gateway_maximum_throughput':'No universal100Mbit/s DNP3gateway capability; actual selectedlowertransport/processorbudget unknown.',
    'gateway_input_buffer':'No universal256frame DNP3gatewayinputbuffer or pertypeeventbuffer.',
    'gateway_output_buffer':'No universal256frame DNP3gatewayoutputbuffer.',
    'gateway_maximum_routes':'No universal10000route DNP3gatewaytable.',
    'gateway_maximum_messages_s':'No universal100000message/s DNP3gatewaythroughput.'
}
spec={'technology':'dnp3','native':native,'removed':removed,
      'sources':['https://www.dnp.org/Portals/0/AboutUs/DNP3%20Primer%20Rev%20A.pdf',
                 'https://www.dnp.org/About/Overview-of-DNP3-Protocol',
                 'https://docs.stepfunc.io/dnp3/1.6.0/rust/src/dnp3/outstation/config.rs.html',
                 'https://docs.stepfunc.io/dnp3/1.6.0/rust/src/dnp3/master/association.rs.html',
                 'https://raw.githubusercontent.com/stepfunc/dnp3/1.6.0/dnp3/src/link/header.rs',
                 'https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt'],
      'revisions':['DNPUGPrimerRevisionA20March2005, informal publicprimary overview pages5..7; full IEEE1815/deviceprofile not supplied',
                   'StepFunctionDNP31.6.0 June24 2024 source/config/link headers read2026-10-01, implementation-defaults explicitlyqualified',
                   'IANA dnp TCP/UDP/SCTP20000 and dnp-sec19999 registry accessed2026-10-01; secureassignment not assumeduniversalTLSconfiguration'],
      'scope':'Each registered original DNP3 parameter, separate link/CRC/transport/fragment/peer-buffer/role/address/object-class/time/security declarations and implementation-qualified proposals; SQL rejected-edit retention.',
      'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters','passed':0},
      'not_certified':['Full formal matched IEEE1815/deviceprofile/subset/objectlibrary/qualifier membership and actual peer support remainunverified; primer expresslynotnormativeformalrules',
                       'Actualresolvedlowertransport/serialbaud/wirebudget/CRCserializer/reassembly/appfragmentsequence/linkconfirm/appconfirm/retry/command execution missing',
                       'Actualeventdatabase/pertypeoverflow/priority/timestamps/mediumaccess/securityconformance remainsunverified',
                       'Scalarwidth/dependency validity doesnotprove endpointaddressuniquenessacrosswholebus or capacity; MODEL_MISSING retained']}
(folder/'dnp3-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
