import json
from pathlib import Path
SOURCE='https://www.st.com.cn/resource/en/reference_manual/rm0312-stm8tl5xxx-microcontroller-family-stmicroelectronics.pdf'
REVISION='ST RM0312 DocID022352 Rev3 October2013 chapter10 pp75-82; ST AN2710 Rev1 February2008 safe transition tables'
declarations=[
 ('gpio_profile','select',None,['STM8TL5_RM0312_3','DEVICE_SPECIFIC'],None,None,'Actual GPIO device profile, unknown; digital pin is not a packet bus and has no universal baud or voltage.'),
 ('gpio_pin','text',None,None,None,None,'Required actual port/pin/package identity and ownership, unknown; unavailable package pins and alternate-function conflicts must be resolved.'),
 ('gpio_device_source','text',None,None,None,None,'Required actual datasheet/pinout/revision/clock/threshold/drive/interrupt capabilities, unknown.'),
 ('gpio_wiring_source','text',None,None,None,None,'Required actual peer wiring/voltage domains/load/pull resistors/isolation/contention and physical limits, unknown.'),
 ('gpio_phase','select',None,['OPERATING','RESET'],None,None,'Actual operating versus reset state. Reset defaults do not overwrite programmed application outputs.'),
 ('gpio_direction','select',None,['DIGITAL_INPUT','DIGITAL_OUTPUT','ALTERNATE','ANALOG_HIGH_Z'],None,None,'Actual pin mode, unknown. Qualified non-exception STM8TL reset proposes input only; alternate functions use a separate explicit technology.'),
 ('gpio_reset_exception','boolean',None,None,None,None,'Actual pin/package exception to reset configuration from datasheet, unknown; e.g. PA_CR1 reset differs. Never assume all reset pins float.'),
 ('gpio_pull','select',None,['NONE','UP','DOWN','DEVICE_SPECIFIC'],None,None,'Actual controller internal pull, unknown; reviewed STM8TL digital input supports NONE/UP, not universal pull-down.'),
 ('gpio_drive','select',None,['PUSH_PULL','PSEUDO_OPEN_DRAIN','TRUE_OPEN_DRAIN','DEVICE_SPECIFIC'],None,None,'Actual output driver/pad kind. True open-drain is pin-specific, not inferred from register option.'),
 ('gpio_active_low','boolean',None,None,None,None,'Actual application polarity, unknown; electrical HIGH/LOW and functional active state are separate.'),
 ('gpio_level','select',None,['LOW','HIGH','HIGH_Z'],None,None,'Actual electrical drive/read state, unknown; floating input is not automatically logicLOW or safe actuation.'),
 ('gpio_input_mode','select',None,['POLLED','INTERRUPT'],None,None,'Actual input sampling/event mechanism, unknown. Output update does not require a slave address or input polling bound.'),
 ('gpio_event','select',None,['RISING','FALLING','BOTH_EDGES','HIGH_LEVEL','LOW_LEVEL','DEVICE_SPECIFIC'],None,None,'Actual selected interrupt sensitivity and controller support, unknown; no mandatory rising edge.'),
 ('gpio_debounce_enabled','boolean',None,None,None,None,'Actual hardware/software debounce enabled, unknown; no universal debounce0ms or10ms.'),
 ('gpio_vdd_v','number','V',None,0,None,'Actual operating GPIO supply/domain voltage, unknown; datasheet governs min/max and pin tolerance.3.3/5/24V are not universal GPIO defaults.'),
 ('gpio_vil_max_v','number','V',None,None,None,'Actual receiving maximum low-input voltage at matched supply/temperature/logic mode, unknown.'),
 ('gpio_vih_min_v','number','V',None,None,None,'Actual receiving minimum high-input voltage at matched supply/temperature/logic mode, unknown.'),
 ('gpio_vol_max_v','number','V',None,None,None,'Actual driving worst-case low voltage at the actual sink load, unknown; must meet receiving VIL.'),
 ('gpio_voh_min_v','number','V',None,None,None,'Actual driving worst-case high voltage at the actual source load, unknown; must meet receiving VIH.'),
 ('gpio_sink_bound_ma','number','mA',None,0,None,'Actual safe per-pin sink-current bound for specified voltage, unknown; absolute maximum is not an operating default.'),
 ('gpio_source_bound_ma','number','mA',None,0,None,'Actual safe per-pin source-current bound for specified voltage, unknown; not universal20mA.'),
 ('gpio_sink_load_ma','number','mA',None,0,None,'Actual sink load, unknown; must fit per-pin limit and separately verified package/port aggregate.'),
 ('gpio_source_load_ma','number','mA',None,0,None,'Actual source load, unknown; must fit pin and actual port/package aggregate.'),
 ('gpio_pull_source','text',None,None,None,None,'Actual external pull-up/down resistance/load/rise/fall/rail and leakage evidence, unknown; open-drain high state needs explicit pull network.'),
 ('gpio_pull_ohms','number','Ohm',None,0,None,'Actual external resistor value, unknown; no universal4.7k resistor. An explicitly present resistor must be positive.'),
 ('gpio_load_pf','number','pF',None,0,None,'Actual pad+wiring+peer load capacitance, unknown; no universal I2C400pF limit or timing default for GPIO.'),
 ('gpio_rise_bound_ns','number','ns',None,0,None,'Actual pin transition upper bound at actual load/slew/drive conditions, unknown; nominal MCU clock does not prove this.'),
 ('gpio_fall_bound_ns','number','ns',None,0,None,'Actual falling transition upper bound, unknown, separate from source/target software processing.'),
 ('gpio_transition_source','text',None,None,None,None,'Actual register-write/configuration sequence and intermediate-state/glitch/interrupt masking evidence, unknown; required for deliberate mode transitions.'),
]
removed={
 'payload_bytes':'GPIO digital pin has no intrinsic1-byte frame; any software encoding/remote IO packet belongs to a separately selected transport.',
 'target_bus_load_percent':'GPIO pin has no packet bus utilization target60%.',
 'peak_factor':'No intrinsic GPIO packet-load peak multiplier1.15.',
 'burst_factor':'No intrinsic GPIO packet-burst multiplier1.5.',
 'burst_window_ms':'No intrinsic100ms packet-burst analysis window for a local pin.',
 'warning_threshold':'No universal GPIO packet-load warning60%.',
 'critical_threshold':'No universal GPIO packet-load critical75%.',
 'overload_threshold':'No universal GPIO packet-load overload90%.',
 'queue_size':'No GPIO packet queue256; software sampling/update queue is actual device/application evidence.',
 'queue_policy':'No intrinsic GPIO FIFO scheduling proof.',
 'qos_priority':'No GPIO priority3 network class.',
 'reserved_bandwidth_percent':'No intrinsic GPIO reserved network bandwidth.',
 'packet_loss_probability':'Local GPIO pin has no packet-loss process; actual missed samples/edges differ.',
 'frame_loss_probability':'No intrinsic GPIO lost-frame process.',
 'bit_error_rate':'No intrinsic framed-link bit-error-rate default0; electrical noise/threshold faults need actual model.',
 'corruption_probability':'No intrinsic GPIO packet corruption probability0.',
 'duplicate_probability':'No intrinsic GPIO duplicated packet probability0; contact bounce is separate actual evidence.',
 'reordering_probability':'No intrinsic GPIO reordered packets.',
 'retransmission_enabled':'No intrinsic GPIO packet retransmission switch.',
 'retransmission_rate':'No GPIO retransmission probability0.',
 'retry_limit':'No universal GPIO retry budget0.',
 'retransmission_delay_ms':'No intrinsic GPIO packet retry delay0.',
 'sync_method':'GPIO sample scheduling does not imply NTP/PTP or protocol synchronization.',
 'gateway_delay_ms':'Local GPIO has no intrinsic gateway forwarding delay0.2ms.',
 'gateway_queue_delay_ms':'No intrinsic GPIO gateway packet queue delay0.',
 'protocol_conversion_delay_ms':'Pin sampling/driving is not automatically a gateway protocol conversion.',
 'gateway_maximum_throughput':'No GPIO gateway100Mbit/s capacity.',
 'gateway_input_buffer':'No intrinsic GPIO gateway256-frame input buffer.',
 'gateway_output_buffer':'No intrinsic GPIO gateway256-frame output buffer.',
 'gateway_maximum_routes':'No GPIO gateway10000-route table.',
 'gateway_maximum_messages_s':'No GPIO gateway100000-message/s rate.',
}
native={key:meaning for key,_,_,_,_,_,meaning in declarations}
native.update({
 'local_timing_evidence.sample_bound_ms':'Actual finite>=0 input-polling bound in ms including capture/software schedule, unknown; required only for actual DIGITAL_INPUT POLLED when confirmed, no100ms default.',
 'local_timing_evidence.debounce_bound_ms':'Actual finite>=0 debounce completion bound, unknown; required only when actual GPIO debounce enabled, not compulsory for every output.',
 'local_timing_evidence.edge_detection_bound_ms':'Actual finite>=0 input interrupt event/edge detection bound in ms including masking/CPU load, unknown; required only for actual input INTERRUPT.',
 'local_timing_evidence.update_bound_ms':'Actual finite>=0 output update-to-valid-pin bound in ms at actual load/slew/driver/schedule, unknown; required only for actual DIGITAL_OUTPUT. Input polling cannot substitute for it.'})
spec={'technology':'gpio','native':native,'removed':removed,
 'sources':[SOURCE,'https://www.st.com/resource/en/application_note/an2710-safe-gpio-port-configuration-in-str7xx-devices-stmicroelectronics.pdf',
            'https://www.microchip.com/en-us/products/microcontrollers/8-bit-mcus/peripherals/system-flexibility/io'],
 'revisions':[REVISION,'Actual electrical/functional bounds require matching datasheet/measurement; no universal GPIO operating standard'],
 'scope':'Each original GPIO form parameter, all new actual pin/electrical/role fields and each local timing field reviewed individually. No packet-bus defaults; source-qualified reset exceptions, input/output roles and electrical peer compatibility separate from functional timing.',
 'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters + physical_profiles','passed':0},
 'not_certified':['Actual package pin/mux/threshold/current/aggregate-port/pull/load/glitch/low-power hardware and measurements remain installation facts, not reset proposals',
 'Actual task/interrupt/sample/debounce/update schedule and functional acceptance; GPIO has no packet transport capacity, NOT_APPLICABLE remains',
 'GPIO electrical transient/noise/metastability/contention/EMC/full transfer function and safety acceptance; alternate UART/PWM/ADC/etc require independent explicit technology paths']}
(Path(__file__).parent/'gpio-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
