"""Individual CANopen CC parameter decisions from CiA and implementation authors."""
import json
from pathlib import Path

folder=Path(__file__).resolve().parent
can=json.loads((folder/'can-review-decisions.json').read_text(encoding='utf-8'))
native=dict(can['native'])
native.update({
 'bitrate':'CANopen CC predefined rates10k/20k/50k/125k/250k/500k/800k/1M. Lowest defined10k proposal, not universalactualhardware support: CiA says eachdevice supportsatleastone listedrate. NotgenericCAN default orCANopenFD data phase.',
 'sample_point_percent':'CiA recommendation closestachievable87.5% proposal. Installedclock/segments mustreproduceactualsamplepoint, which maydiffer andis preserved. Not ahardexact87.5% acceptance threshold.',
 'payload_bytes':'Actual per-frameCAN CC Data field0..8 unknown. PDO cancarryup to8 applicationbytes;SDO framecontainsprotocolmetadata, expedited<=4 objectbytes andsegmented<=7 persegment. TotalSDO objectlength is distinctandmayexceed8.',
 'can_bus_length_m':'Actualmainline lengthunknown; CiA predefinedhigh-speed bit-timing table suppliesrate-specificmaximum5000/2500/1000/500/250/100/50/25m at10k..1M. Actualtopology/power/PHY/oscillator muststillbeverified.',
 'can_stub_length_m':'Actualmaximumunterminatedstubunknown; CiAtablegives275/137.5/55/22/11/5.5/2.5/1.5m for10k..1M. NoCANgeneric40m topologyfallback.',
 'co_accumulated_stub_length_m':'Actualsumofunterminatedstubsunknown; distinctfromlongeststub. CiA maxima1375/687.5/275/110/55/27.5/12.5/7.5m for10k..1M underdeclaredHSbaseline.',
 'co_baseline':'RegisteredCANopenCC/CiA301baselineproposal. CANopenFD/CiA1301 isanother technology path, notimplicit64byteframesor2Mdata.',
 'co_node_id':'Actualconfigured7bitNode-ID1..127unknown. ZeroNMTtargetmeansbroadcast, notaninstallednode;unconfiguredLSSidentityrequiresseparatesetupandnoarbitrarynode1default.',
 'co_service':'ActualPDO/SDO/NMT/SYNC/TIME/EMCY/HEARTBEAT/BOOTUP serviceunknown. Determinesframepayload/transportbehavior; notindustry-baseddefaultPDOforallcommunication.',
 'co_nmt_state':'Observedinitializing/preoperational/operational/stoppedunknown. NoautomaticOPERATIONAL orreadydefault;staticfielddoesnotimplementstateexecution.',
 'co_nmt_command':'Actualwirecommand1start/2stop/128preoperational/129resetnode/130resetcommunicationunknown. LibraryNO_COMMAND0isinternalabsence, notanemittedNMTcommand.',
 'co_nmt_target':'Actualtarget0..127unknown. Zeroisbroadcastandnotlocalnodeidentity. Noautomaticsendtowholenetwork.',
 'co_pdo_transmission_type':'Actual0acyclicSYNC,1..240cyclicnthSYNC,254manufacturer-specificevent/255profilespecificeventunknown.241..251reservedinvalid;252/253legacyRTRvalidonlywithexplicitactualdevicesupport. CANopenNode/BeckhoffdonotexecutelegacyRTR; no255universaldefault.',
 'co_pdo_inhibit_100us':'ActualTPDOinhibittimerUNSIGNED16 in100usunits0..65535unknown;zero disablesfilter. NotNISminimumcycle_ms orhostdelay. Device/revision applicabilitystillrequired.',
 'co_pdo_event_timer_ms':'ActualPDOeventtimermillisecondsUNSIGNED160..65535unknown;zerodisablescyclicevent. RPDOmonitoringwatchdog differsfromTPDOsendtimer; nohardcoded1/100/1000msdefault.',
 'co_pdo_sync_start':'ActualTPDOsynccounterstart0..240unknown;zeroignorescounter. Knownpositivecounteroverflowlimitsstartanddisabledcounterrequires0. Actualsynchronousschedule notprovenbyfieldalone.',
 'co_pdo_mapped_bits':'Actualsumofmappedobjectbitlengths0..64unknown; mustfitknownPDOframebytes. No8mapped-entryuniversalcap copiedfromCANopenNodebytegranularity; actualindex/subindex/encodings needmappingevidence.',
 'co_pdo_mapping':'Actualstatic/variable/dynamicmappingcapabilityunknown. CiAvariablechangesinpreoperational,dynamicmaychangeoperational;NISdoesnotperformODmappingprocedureorconfirmcapability.',
 'co_pdo_valid':'ActualCOB-IDbit31validitydecodedbooleanunknown. Noassumedtrue. Dynamicmapproceduremustdisablecommunication/mappingbeforechanges;notimplementedbythisscalar.',
 'co_rtr_allowed':'ActualPDOremote-requestpermissionunknown. Knownfalserejectslegacy252/253. CiAnolongerrecommendsRTRservices;noautomaticfalseconfirmationordeletionofexistinglegacyassignments.',
 'co_od_index':'Actualobjectdictionary16bitindex0..65535unknown. Numericalrangealone doesnotproveobjectexistsoraccess/datatype.',
 'co_od_subindex':'Actualobjectdictionary8bitsubindex0..255unknown;notmessagepriorityoraddress. ActualODentrytype/access/source required.',
 'co_sdo_variant':'Actualexpedited/segmented/blockunknown. Expedited<=4objectbytes; normalsegmentscarry<=7objectbytes plusprotocol;blockackupto127segments. NISdoesnotexecutecompleteSDOtransactionstate.',
 'co_sdo_application_bytes':'Actualtotalobjectlengthunknownnonnegativeinteger. Distinctfromper-frame8bytes, nouniversal1500/2048/65535logicalcap;expeditedknownvariant<=4.',
 'co_sdo_block_segments':'Actualblocksize1..127segmentsunknown fromCiAprotocol. Notretrycountorfragmentdata bytes. Explicitblockflow/ack behaviorstillrequired.',
 'co_sdo_response_bound_ms':'Actualdevice/datameasurementresponseboundunknownnonnegativefinite milliseconds. NoCANarbitration-onlyboundorvendor1000msdefaultsuppliedasproof.',
 'co_sync_can_id':'PredefinedSYNCidentifier0x80(128)proposalfromofficialCANopenNodeidentifierlist. Actualremappingpreserved;selectexplicitSYNCIDEfordifferentformat. NotPDOID0x180+nodeID.',
 'co_sync_frame_format':'PredefinedSYNC11-bitformatproposal, extendedCANsupportedbyCANopenCCbutactualdevicemaynotimplementit. SelectedBASElimitsidentifier2047;noautomaticallyextendedfromindustry.',
 'co_sync_producer':'ActualSYNCproducercapability/stateunknownboolean. Atmostoneactualproducerconfigurationneedstopologyreview;nodepresenceisnotsufficient.',
 'co_sync_period_us':'ActualOD1006UNSIGNED32communicationperiodmicroseconds0..4294967295unknown. Zero disablesperiodicSYNC; notNISgenericcycle100ms. Noactualproductioninferredfromproposal.',
 'co_sync_window_us':'ActualOD1007UNSIGNED32synchronouswindowmicrosecondsunknown. Zero disableswindowcheck; whenpositiveperiodknownwindowmustfit. Actualqueues/arbitration/jitter requiredforproof.',
 'co_sync_counter_overflow':'BaselineoptionalSYNCcounterdisabled0proposal; otherwise2..240.1reservedinvalid. Known0=>zeroSYNCData,knownpositive=>onebytecounter. Doesnotautofillactualpayload.',
 'co_error_control':'CiArecommendedHEARTBEATbaselineproposal;legacyNODE_GUARDINGremainsseparateexplicitchoice. Itisnotaproposed100msperiodorconfirmedavailability.',
 'co_heartbeat_producer_ms':'ActualOD1017UNSIGNED16producerperiod0..65535msunknown. Zero disables; positivevalue andactualobservedNMTstate neededforavailabilitymonitoring. Novendorperioddefault.',
 'co_heartbeat_consumer_ms':'ActualOD1016low16bittimeout0..65535msunknown,foridentifiedproducer. Zero disablesmonitor; startsafterfirstheartbeat(notbootup). Noassumed1.5xproduceruniversalratio.'
})
spec={'technology':'canopen','native':native,'removed':can['removed'],
 'sources':['https://www.can-cia.org/can-knowledge/canopen-lower-layers',
            'https://www.can-cia.org/can-knowledge/pdo-protocol',
            'https://www.can-cia.org/can-knowledge/sdo-protocol',
            'https://www.can-cia.org/can-knowledge/error-control-protocols',
            'https://canopennode.github.io/CANopenNode/group__CO__SYNC.html',
            'https://canopennode.github.io/CANopenNode/group__CO__NMT__Heartbeat.html',
            'https://canopennode.github.io/CANopenNode/group__CO__HBconsumer.html',
            'https://canopennode.github.io/CANopenNode/group__CO__Default__CAN__ID__t.html',
            'https://canopennode.github.io/CANopenNode/group__CO__TIME.html',
            'https://canopennode.github.io/CANopenNode/group__CO__Emergency.html',
            'https://raw.githubusercontent.com/CANopenNode/CANopenNode/master/301/CO_SYNC.c',
            'https://raw.githubusercontent.com/CANopenNode/CANopenNode/master/301/CO_HBconsumer.c',
            'https://github.com/CANopenNode/CANopenDemo/blob/master/tutorial/PDO.md',
            'https://infosys.beckhoff.com/content/1033/cx805x_hw/2037701515.html',*can['sources']],
 'revisions':['CiA CANopen CC/CiA301 official knowledgepagesaccessed2026-10-01;notclaimingreadlicensedfullCiA301edition',
              'CANopenNode authors source/docsaccessed2026-10-01,generatedDoxygen1.11;implementation-specificlimitsnotuniversal',
              'BeckhoffofficialPDOtypes legacy252/253tableaccessed2026-10-01'],
 'scope':'EveryregisteredCANopenCCparameterwithreviewedexplicitCANlowerlayer, ownbitrate/topologytable andnativePDO/SDO/SYNC/NMT/heartbeattypes/defaults/dependencies. IsolatedSQLretainspreviouslyconfirmedvaluesandrejectsinconsistentedits.',
 'validation':{'isolated_sql':True,'suite':'full_parameter_audit + standard_defaults + profile_semantics + capacity_can_schedule + parameter_review + required_parameters','passed':0},
 'not_certified':['CompleteCANopen serviceexecution andcapacity/schedulemodel remainsMODEL_MISSING',
                  'ActualEDS/objectdictionary/mappedentries/NodeID/COBIDs/uniquenessandsupportedrates',
                  'AutomaticPDOdefaultidentifierassignmentoractualSDOsegmentation/blocktiming',
                  'ActualSYNCproducer/counter/state/heartbeatmonitoringandsafetyacceptance',
                  'CANopenFD/CiA1301/CANopensafety/CiA304 andoptionaldeviceprofiles',
                  'ActuallegacyRTRsupportorconformance tothecompleteCiA301licensedstandard']}
(folder/'canopen-review-decisions.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
