import type { IndustrySensorTemplate, IndustryTemplateProfile } from "./types.ts";

const sensors: IndustrySensorTemplate[] = [
  ["MotorCurrentSensor", "Motorstrom", "EtherCAT", "A", -200, 200, 0.1, 2],
  ["AxisPositionSensor", "Achslage", "EtherCAT", "mm", -10000, 10000, 0.001, 1],
  ["AxisVelocitySensor", "Achsengeschwindigkeit", "EtherCAT", "mm/s", -5000, 5000, 0.01, 1],
  ["LinePressureSensor", "Leitungsdruck", "ProfiNET", "bar", 0, 16, 0.01, 10],
  ["FlowRateSensor", "Durchfluss", "ProfiNET", "l/min", 0, 1000, 0.1, 20],
  ["TankLevelSensor", "Tankfuellstand", "ModbusTCP", "%", 0, 100, 0.1, 100],
  ["ProcessTemperatureSensor", "Prozesstemperatur", "ProfiNET", "degC", -40, 250, 0.1, 50],
  ["VibrationSensor", "Schwinggeschwindigkeit", "ProfiNET", "mm/s", 0, 100, 0.01, 20],
  ["SafetyDoorSensor", "SchutztuerStatus", "EtherCAT", "code", 0, 1, 1, 5],
  ["LightBarrierSensor", "LichtschrankeStatus", "EtherCAT", "code", 0, 1, 1, 2],
  ["PartCounterSensor", "Teilezaehler", "ProfiNET", "count", 0, 1000000, 1, 100],
  ["EnergyMeterSensor", "Energieverbrauch", "ModbusTCP", "kWh", 0, 100000, 0.1, 1000],
].map(([hardwareName, signalName, interfaceType, unit, minValue, maxValue, factor, cycleMs]) => ({
  cycleMs: Number(cycleMs),
  factor: Number(factor),
  hardwareName: String(hardwareName),
  interfaceType: String(interfaceType),
  maxValue: Number(maxValue),
  minValue: Number(minValue),
  signalName: String(signalName),
  unit: String(unit),
}));

export const industrialAutomationTemplateProfile: IndustryTemplateProfile = {
  gatewayName: "AnlagenGateway",
  id: "industrial_automation",
  label: "Industrial Automation",
  sensorTemplates: sensors,
  systemVariants: [
    "SPSLeitsystem",
    "Maschinensteuerung",
    "MotionControl",
    "Roboterzelle",
    "Foerdertechnik",
    "Prozessregelung",
    "Sicherheitssteuerung",
    "HMIStation",
    "Antriebsregelung",
    "Ventilinsel",
    "IOStation",
    "Pruefstand",
    "Druckluftversorgung",
    "Temperiergeraet",
    "Verpackungsmodul",
    "Dosiertechnik",
    "Qualitaetspruefung",
    "Produktionszelle",
    "Energieverteilung",
    "ConditionMonitoring",
  ],
};
