"""WebSocket framing over an explicit negotiated transport, not an Ethernet frame."""
from backend.nis.communication.services.native_review_support import declaration, fields as build_fields, WIRE_KEYS, ETHERNET_KEYS
BASE='https://www.rfc-editor.org/rfc/rfc6455.html'
DEFLATE='https://www.rfc-editor.org/rfc/rfc7692.html'
H2='https://www.rfc-editor.org/rfc/rfc8441.html'
H3='https://www.rfc-editor.org/rfc/rfc9220.html'
SOURCES={BASE:'RFC6455 Dec2011 sections3-5/7-10; base framing, clientmask, minimal63bitlength, fragmentation, handshake version13, closecode and implementationlimits.',DEFLATE:'RFC7692 Dec2015 sections6-7; permessage-deflate negotiated direction-specificcontext/window limits and RSV1firstdataframe only.',H2:'RFC8441 Sep2018 sections3-5; explicit ENABLE_CONNECT_PROTOCOL and extendedCONNECT, noHTTP1Upgrade/Key/Accept.',H3:'RFC9220 June2022 sections3-4; HTTP3 independentsetting08 and singleQUICstream usingextendedCONNECT.'}
DECLARATIONS=[]
def d(k,t,m,src=BASE,**kw):DECLARATIONS.append(declaration('ws_',k,t,m,src,SOURCES[src],**kw))
for k,m,o,s in [('transport','Actual handshake and underlying negotiated stream, independent physical link.',['HTTP1_TCP','HTTP2_STREAM','HTTP3_QUIC_STREAM','REGISTERED_ACTUAL'],BASE),('scheme','Actual URI security scheme.',['ws','wss'],BASE),('direction','Actual frame sender; all client frames masked, serverframes unmasked.',['CLIENT_TO_SERVER','SERVER_TO_CLIENT'],BASE),('method','Actual opening handshake request.',['GET','CONNECT'],BASE),('extension','Actual negotiated extensions; compression never implicit.',['NONE','PERMESSAGE_DEFLATE','REGISTERED_ACTUAL'],DEFLATE),('fragment','Actual dataframe role in message; controls may interleave.',['SINGLE','FIRST','CONTINUATION','LAST'],BASE),('outcome','Actual independent consumingfunction result.',['ACCEPTED','FRAME_ONLY','PONG_ONLY','CLOSED','ERROR','UNKNOWN'],BASE)]:d(k,'select',m,s,options=o)
for k,m,lo,hi,s in [('version','Handshake protocolversion, not HTTPversion.',0,255,BASE),('port','Actual endpointport; URI default conditional only.',1,65535,BASE),('http_status','Actual opening response101 or successful extendedCONNECT2xx.',100,599,BASE),('opcode','Actual4bitopcode; continuation0/text1/binary2/close8/ping9/pong10.',0,15,BASE),('rsv','Actual3reservedbits; RSV1 is numeric4 and negotiated compressedfirstdataonly.',0,7,BASE),('length_code','Actual7bitlength discriminator requiring shortestencoding.',0,127,BASE),('frame_payload_bytes','Actual extension plusapplication bytes,63bits upperbound; independent operationalbuffer.',0,9223372036854775807,BASE),('extension_bytes','Actual negotiated extension data length.',0,9223372036854775807,BASE),('application_bytes','Actual currentframe applicationwire bytes; compressed differslogicalmessage.',0,9223372036854775807,BASE),('extended_length_bytes','Actual0/2/8byte network-orderlength field.',0,8,BASE),('mask_bytes','Actual4byte maskingkey present iffmaskbitset.',0,4,BASE),('header_bytes','Actual2bytebase+extendedlength+maskkey, excludesHTTP/TLS/QUIC.',2,14,BASE),('wire_bytes','Actual completeWSframe header plus extension+application.',2,None,BASE),('message_bytes','Actual reassembled decodedmessage bytes, not oneframe or maximum65535.',0,None,BASE),('max_frame_bytes','Actual negotiated implementationmemory/policylimit; not protocoldefault.',0,None,BASE),('max_message_bytes','Actual decompressed/reassembled implementationbound.',0,None,BASE),('close_code','Actual transmitted2byte closecode; reserved not sent.',1000,4999,BASE),('close_reason_bytes','Actual validUTF8 close reason excludingcode2bytes.',0,123,BASE),('server_window_bits','Actual negotiated response serverwindow8..15.',8,15,DEFLATE),('client_window_bits','Actual negotiated response clientwindow8..15.',8,15,DEFLATE),('server_window_offer','Actual offeredserverwindow upperbound8..15.',8,15,DEFLATE),('client_window_offer','Actual offeredclientwindowhint; not universalserver responsebound.',8,15,DEFLATE),('server_window_bytes','Actual2^serverwindow memory size.',256,32768,DEFLATE),('client_window_bytes','Actual2^clientwindow memorysize.',256,32768,DEFLATE),('source_ms','Actual producing/codec/compressiondelay.',0,None,BASE),('transport_ms','Actual underlyingstream/masking/reassembly/retry bound.',0,None,BASE),('use_ms','Actual independent consumer executiondelay.',0,None,BASE),('e2e_ms','Actual source-to-usebound independentPong/TCPACK.',0,None,BASE),('deadline_ms','Independent applicationdeadline.',0,None,BASE),('age_ms','Actual consumedmessageage.',0,None,BASE),('freshness_ms','Independent allowabledataage.',0,None,BASE)]:d(k,'number',m,s,min=lo,max=hi,integer=not k.endswith('_ms'),unit='ms'if k.endswith('_ms')else None)
for k,m,s in [('mask','ActualMASKbit, not confidentiality.',BASE),('fin','Actualfinalfragmentbit; controls alwaysfinal.',BASE),('compressed','Actual negotiatedmessagecompression flag, notall frames.',DEFLATE),('client_window_offered','Actual extensionoffer includes client_max_window_bits evenwithoutvalue.',DEFLATE),('server_window_absent','Actual acceptedextension omits serverwindowparameter.',DEFLATE),('client_window_absent','Actual acceptedextension omitsclientwindowparameter.',DEFLATE),('server_no_context_takeover','Actual negotiatedresetservercompressioncontext permessage.',DEFLATE),('client_no_context_takeover','Actual negotiatedresetclientcompressioncontext permessage.',DEFLATE),('connect_enabled','Actualserver ENABLE_CONNECT_PROTOCOL=1 received.',H2),('upgrade_header','ActualHTTP1 Upgradeheader; forbiddenextendedCONNECT.',H2),('connection_header','ActualHTTP1 Connectionheader; forbiddenextendedCONNECT.',H2),('key_header','ActualSecWebSocketKey presence; not usedextendedCONNECT.',H2),('accept_header','ActualSecWebSocketAccept presence; not usedextendedCONNECT.',H2),('utf8_verified','Actual reconstructedtext/closeUTF8checked; fragmentedframe neednotindividuallyvalid.',BASE),('mask_entropy_verified','Actualfreshunpredictablemaskkeygenerator assessment.',BASE),('path_verified','Actualwholetransport/applicationpathevidence.',BASE),('data_accepted','Actualfreshconsumingfunction succeeds, notjustsocketOPEN.',BASE)]:d(k,'boolean',m,s)
for k,m,s in [('revision','ActualRFC/extensions/libraryedition.',BASE),('device_source','Actualpeer/runtime/bufferlimits.',BASE),('transport_source','ActualHTTP/TCP/TLS orQUICstream andpath parameters.',H3),('acceptance_source','Actual independentdeadline/age/errorcontract.',BASE),('registered_source','Actualregisteredextension/transport/closecodeedition.',BASE),('protocol','ActualextendedCONNECT :protocol token websocket.',H2),('path','ActualnonemptyURIpath / ifnone; nofragmentURI.',BASE),('authority','Actualhost/portauthority, required H2/H3.',H2),('http_scheme','Actualhttp forws/https forwss.',H2),('subprotocol','Actualsingle mutuallynegotiated applicationtoken, notcomma-list.',BASE),('extension_source','Actualoffered/acceptedextension anddirection/source.',DEFLATE),('mask_source','Actualfreshmaskkey entropy/source (no secretkey retained).',BASE),('utf8_source','Actual reassembled/decodedmessage orclosereason verification.',BASE),('observation_source','Actualcorrelatedproducer/frame/path/consumptiontrace.',BASE)]:d(k,'text',m,s)
REQUIRED=('revision','device_source','transport_source','acceptance_source')
REMOVED={k:'WebSocket has its own handshake/frame/extension/reassembled message and explicittransport; no EthernetMTU/CANrate/gateway blanketdefault.'for k in WIRE_KEYS+ETHERNET_KEYS}
def semantics():
 rules=[]
 def r(k,w=None,s=BASE,**kw):rules.append(dict(parameter='ws_'+k,when={'ws_'+a:b for a,b in(w or{}).items()},source=s,**kw))
 rules.extend(dict(parameter=k,when={},allowed=[],source=BASE)for k in REMOVED)
 r('registered_source',{'transport':'REGISTERED_ACTUAL'},required=True)
 r('version',allowed=[13]);r('mask',{'direction':'CLIENT_TO_SERVER'},allowed=[True]);r('mask',{'direction':'SERVER_TO_CLIENT'},allowed=[False])
 for k in('direction','mask','opcode','fin','rsv','length_code','extended_length_bytes','header_bytes'):r(k,when_present=['ws_frame_payload_bytes'],required=True)
 for code,lo,hi,extra in[(125,0,125,0),(126,126,65535,2),(127,65536,9223372036854775807,8)]:
  if code==125:
   r('length_code',when_ranges={'ws_frame_payload_bytes':[lo,hi]},equal_parameter='ws_frame_payload_bytes')
  else:r('length_code',when_ranges={'ws_frame_payload_bytes':[lo,hi]},allowed=[code])
  r('extended_length_bytes',when_ranges={'ws_frame_payload_bytes':[lo,hi]},allowed=[extra])
 for masked,n in[(True,4),(False,0)]:r('mask_bytes',{'mask':masked},allowed=[n]);r('header_bytes',{'mask':masked},equal_expression={'sum':[2,n,'ws_extended_length_bytes']})
 r('wire_bytes',equal_expression={'sum':['ws_header_bytes','ws_frame_payload_bytes']})
 r('frame_payload_bytes',equal_expression={'sum':['ws_extension_bytes','ws_application_bytes']},maximum_parameter='ws_max_frame_bytes')
 r('message_bytes',maximum_parameter='ws_max_message_bytes')
 for op in(8,9,10):
  r('fin',{'opcode':op},allowed=[True]);r('frame_payload_bytes',{'opcode':op},maximum=125);r('rsv',{'opcode':op},allowed=[0]);r('compressed',{'opcode':op},allowed=[False])
 r('opcode',{'extension':'NONE'},allowed=[0,1,2,8,9,10]);r('rsv',{'extension':'NONE'},allowed=[0]);r('compressed',{'extension':'NONE'},allowed=[False]);r('extension_bytes',{'extension':'NONE'},allowed=[0])
 for frag,fin,ops in [('SINGLE',True,[1,2]),('FIRST',False,[1,2]),('CONTINUATION',False,[0]),('LAST',True,[0])]:r('fin',{'fragment':frag},allowed=[fin]);r('opcode',{'fragment':frag},allowed=ops)
 r('close_code',forbidden=[1004,1005,1006,1015]);r('frame_payload_bytes',{'opcode':8},forbidden=[1])
 r('frame_payload_bytes',{'opcode':8},when_present=['ws_close_code','ws_close_reason_bytes'],equal_expression={'sum':[2,'ws_close_reason_bytes']})
 for k in('mask_source',):r(k,{'mask_entropy_verified':True},required=True)
 r('utf8_source',{'utf8_verified':True},required=True)
 r('extension_source',{'extension':'PERMESSAGE_DEFLATE'},required=True,s=DEFLATE);r('extension_source',{'extension':'REGISTERED_ACTUAL'},required=True)
 for frag in('CONTINUATION','LAST'):r('rsv',{'extension':'PERMESSAGE_DEFLATE','fragment':frag},allowed=[0],s=DEFLATE)
 for frag in('SINGLE','FIRST'):
  for comp,rv in[(True,4),(False,0)]:r('rsv',{'extension':'PERMESSAGE_DEFLATE','fragment':frag,'compressed':comp},allowed=[rv],s=DEFLATE)
 r('server_window_bits',maximum_parameter='ws_server_window_offer',s=DEFLATE)
 r('client_window_offered',when_present=['ws_client_window_bits'],required=True,allowed=[True],s=DEFLATE)
 for side in('server','client'):r(side+'_window_bytes',equal_expression={'power':[2,'ws_'+side+'_window_bits']},s=DEFLATE)
 r('method',{'transport':'HTTP1_TCP'},allowed=['GET']);r('http_status',{'transport':'HTTP1_TCP'},allowed=[101])
 for k in('upgrade_header','connection_header','key_header','accept_header'):r(k,{'transport':'HTTP1_TCP'},allowed=[True])
 for transport,s in [('HTTP2_STREAM',H2),('HTTP3_QUIC_STREAM',H3)]:
  w={'transport':transport};r('method',w,allowed=['CONNECT'],s=s);r('http_status',w,minimum=200,maximum=299,s=s)
  for k,val in [('connect_enabled',True),('protocol','websocket')]:r(k,w,required=True,allowed=[val],s=s)
  for k in('path','authority','http_scheme'):r(k,w,required=True,s=s)
  for k in('upgrade_header','connection_header','key_header','accept_header'):r(k,w,allowed=[False],s=s)
 for scheme,h in [('ws','http'),('wss','https')]:r('http_scheme',{'scheme':scheme},allowed=[h],s=H2)
 r('e2e_ms',equal_expression={'sum':['ws_source_ms','ws_transport_ms','ws_use_ms']},maximum_parameter='ws_deadline_ms');r('age_ms',maximum_parameter='ws_freshness_ms')
 for k in('source_ms','transport_ms','use_ms'):r(k,when_present=['ws_e2e_ms'],required=True)
 for k in('e2e_ms','deadline_ms','age_ms','freshness_ms','observation_source'):r(k,{'data_accepted':True},required=True)
 r('path_verified',{'data_accepted':True},required=True,allowed=[True]);r('outcome',{'data_accepted':True},required=True,allowed=['ACCEPTED'])
 return dict(rate_model={'type':'EXPLICIT_WEBSOCKET_TRANSPORT','fields':[]},parameter_evidence_scope='EXPLICIT_LAYER',required_parameters=['ws_'+k for k in REQUIRED],native_parameter_prefixes=['ws_'],parameter_constraints=rules,medium_access_model='NEGOTIATED_STREAM_TRANSPORT',arbitration_model_id='ACTUAL_TRANSPORT_STREAM_SCHEDULING',mechanisms={'network':['MINIMAL_LENGTH_MASK_EXTENSION_FRAME','REASSEMBLED_MESSAGE_NOT_ETHERNET_PAYLOAD'],'timing':['ACTUAL_TRANSPORT_AND_APPLICATION_PATH']})
def fields():
 p={'ws_version':[dict(when={},value=13,source=BASE,source_revision=SOURCES[BASE])],'ws_path':[dict(when={},value='/',source=BASE,source_revision=SOURCES[BASE])]}
 for scheme,port in [('ws',80),('wss',443)]:p.setdefault('ws_port',[]).append(dict(when={'ws_scheme':scheme},value=port,source=BASE,source_revision=SOURCES[BASE]))
 for side in('server','client'):p['ws_'+side+'_window_bits']=[dict(when={'ws_extension':'PERMESSAGE_DEFLATE','ws_'+side+'_window_absent':True},value=15,source=DEFLATE,source_revision=SOURCES[DEFLATE])]
 return build_fields(DECLARATIONS,['ws_'+k for k in REQUIRED],p)
