"""WirelessHART: source-qualified radio, scheduled mesh and host acceptance."""
from backend.nis.communication.services.native_review_support import declaration, fields as build_fields, WIRE_KEYS
DATA='https://www.analog.com/media/en/technical-documentation/data-sheets/5800whmfa.pdf'
SOURCES={DATA:'LTC5800-WHM RevFA2015 selected pp3,5,16,23-26: radio250kbit/s, channels11..25,5MHz spacing,10ms scheduled operation, routing/retries, AES and separate host UART. Public primary web extracts retained; original PDF bytes unavailable locally. No full IEC62591 or commissioned network certification.'}
DECLARATIONS=[]
def d(k,t,m,**kw):DECLARATIONS.append(declaration('wh_',k,t,m,DATA,SOURCES[DATA],**kw))
d('radio','select','Actual qualified WirelessHART radio implementation; other radios require independent device evidence.',options=['LTC5800_WHM','REGISTERED_ACTUAL'])
d('outcome','select','Independent consuming function result, not MAC acknowledgment.',options=['ACCEPTED','RADIO_ACK_ONLY','ERROR','UNKNOWN'])
for k,m,lo,hi,u,integer in [('rate_bps','Actual radio data rate, separate host UART and application throughput.',1,None,'bit/s',False),('channel','Actual active RF channel selected by manager, not a static channel assumption.',0,255,None,True),('centre_mhz','Actual channel centre from selected radio.',0,None,'MHz',False),('slot_us','Actual scheduled link slot including guard, radio, security and ACK.',1,None,'us',False),('superframe_slots','Actual complete manager schedule period in slots.',1,None,'slot',True),('superframe_us','Actual schedule period; number of slots times slot duration.',1,None,'us',False),('slot_index','Actual scheduled slot index in its superframe.',0,None,None,True),('allocated_slots','Actual per-period transmission/reception allocation, not typical3.',0,None,'slot',True),('hops','Actual directed graph path hops and alternate paths.',1,None,None,True),('attempts','Actual scheduled attempts including initial transmission; not a delivery guarantee.',1,None,None,True),('header_bytes','Actual selected WirelessHART/DLL/network/transport headers.',0,None,'byte',True),('security_bytes','Actual security/MIC overhead, peer and revision qualified.',0,None,'byte',True),('fcs_bytes','Actual radio CRC bytes.',0,None,'byte',True),('psdu_bytes','Actual complete protected MAC frame excluding PHY prefix.',1,None,'byte',True),('peer_psdu_max','Actual peer and selected protocol maximum frame length, not application127.',1,None,'byte',True),('phy_bytes','Actual preamble/SFD/length-prefix bytes.',0,None,'byte',True),('air_us','Nominal serial radio airtime including PHY; not complete mesh response.',0,None,'us',False),('source_ms','Actual producer and host interface processing bound.',0,None,'ms',False),('mesh_ms','Actual scheduled graph/retry/queue/forwarding bound.',0,None,'ms',False),('use_ms','Actual consuming function processing bound.',0,None,'ms',False),('e2e_ms','Actual source-to-use total bound, independent ACK.',0,None,'ms',False),('deadline_ms','Independent application deadline.',0,None,'ms',False),('age_ms','Actual consumed data age.',0,None,'ms',False),('freshness_ms','Independent allowable data age.',0,None,'ms',False),('host_uart_baud','Actual separate API UART configuration; no radio rate substitution.',1,None,'baud',True)]:d(k,'number',m,min=lo,max=hi,unit=u,integer=integer)
for k,m in [('schedule_verified','Actual manager schedule, graph allocation and retry evidence.'),('security_verified','Actual commissioned credentials/session/counter/replay evidence.'),('data_accepted','Actual independent consuming function succeeds.')]:d(k,'boolean',m)
for k,m in [('revision','Actual device/protocol/API edition.'),('device_source','Actual peer capability/frame sizes and configuration.'),('schedule_source','Actual manager graph/superframe/channel and retry allocation.'),('security_source','Actual protected security commissioning evidence; no inline keys.'),('regulatory_source','Actual region/antenna/radio compliance evidence.'),('acceptance_source','Independent application deadline and freshness contract.'),('observation_source','Actual correlated radio/host/function observations.')]:d(k,'text',m)
REQUIRED=('revision','device_source','schedule_source','security_source','regulatory_source','acceptance_source')
REMOVED={k:'WirelessHART radio/manager schedule and host facts are native; no inherited CAN/gateway default.' for k in WIRE_KEYS}
def semantics():
 rules=[]
 def r(k,w=None,**kw):rules.append(dict(parameter='wh_'+k,when={'wh_'+a:b for a,b in(w or {}).items()},source=DATA,**kw))
 rules.extend(dict(parameter=k,when={},allowed=[],source=DATA)for k in REMOVED)
 r('rate_bps',{'radio':'LTC5800_WHM'},allowed=[250000]);r('channel',{'radio':'LTC5800_WHM'},minimum=11,maximum=25)
 r('centre_mhz',{'radio':'LTC5800_WHM'},equal_expression={'sum':[2405,{'product':[{'subtract':['wh_channel',11]},5]}]})
 r('slot_us',{'radio':'LTC5800_WHM'},allowed=[10000]);r('host_uart_baud',{'radio':'LTC5800_WHM'},allowed=[9600,115200])
 r('superframe_us',equal_expression={'product':['wh_superframe_slots','wh_slot_us']});r('slot_index',exclusive_maximum_expression='wh_superframe_slots');r('allocated_slots',maximum_parameter='wh_superframe_slots')
 r('psdu_bytes',equal_expression={'sum':['payload_bytes','wh_header_bytes','wh_security_bytes','wh_fcs_bytes']},maximum_parameter='wh_peer_psdu_max')
 r('air_us',equal_ratio={'numerator_sum':['wh_psdu_bytes','wh_phy_bytes'],'numerator_offset':0,'denominator_parameter':'wh_rate_bps','factor':8000000})
 r('e2e_ms',equal_expression={'sum':['wh_source_ms','wh_mesh_ms','wh_use_ms']},maximum_parameter='wh_deadline_ms');r('age_ms',maximum_parameter='wh_freshness_ms')
 for k in('source_ms','mesh_ms','use_ms'):r(k,when_present=['wh_e2e_ms'],required=True)
 for k in('e2e_ms','deadline_ms','age_ms','freshness_ms','observation_source'):r(k,{'data_accepted':True},required=True)
 for k in('schedule_verified','security_verified'):r(k,{'data_accepted':True},required=True,allowed=[True])
 r('outcome',{'data_accepted':True},required=True,allowed=['ACCEPTED'])
 return dict(rate_model={'type':'WIRELESSHART_QUALIFIED_RADIO_MESH','fields':[]},parameter_evidence_scope='EXPLICIT_LAYER',required_parameters=['wh_'+k for k in REQUIRED],native_parameter_prefixes=['wh_'],parameter_constraints=rules,medium_access_model='MANAGER_SCHEDULED_MESH',arbitration_model_id='SLOT_CHANNEL_GRAPH',mechanisms={'network':['SCHEDULED_CHANNEL_HOPPING_NOT_CSMACA_DEFAULT'],'timing':['ACTUAL_MANAGER_GRAPH_AND_HOST_PATH']})
def fields():
 return build_fields(DECLARATIONS,['wh_'+k for k in REQUIRED],{ 'wh_'+k:[dict(when={'wh_radio':'LTC5800_WHM'},value=v,source=DATA,source_revision=SOURCES[DATA])] for k,v in [('rate_bps',250000),('slot_us',10000)]})
