"""Zigbee: distinct selected PHY, layered payload and sleepy mesh delivery."""
from backend.nis.communication.services.native_review_support import declaration, fields as build_fields, WIRE_KEYS
API='https://docs.silabs.com/zigbee/8.2.1/zigbee-stack-api/message'
TI='https://www.ti.com/lit/pdf/swra396'
SOURCES={API:'OriginalSilabsEmberZNet8.2.1 sendingreceiving API read: maximumAPSpayload dependsactualsecurity/node descriptor; APSACK default50ms*MAX_HOPS+100ms, APIuint16 override; APS_RETRY3transmissions, forceddiscoveryfirstattemptconsumed, fragmentedsequence/indirectsleepytimeout, messagequeuednotdelivered. No allZigbee4/profilescodec certification.',TI:'OriginalTIAN114SWRA3962011 selected4/5.1/5.2: IEEE802154basePHY packet4bytepreamble+SFD1+PHR1+PSDU<=127,250kbit/s32us/byte; actualAPS/NWKsecurityheaders variable, CSMA/CA/ACK192..512us and11byteACK, exampleTIMACprocessing2.2ms andaveragebackoff1.12ms not universalbound or default; historicalregulatorylaw not currentauthorization.'}
DECLARATIONS=[]
def d(k,t,m,s=API,**kw):DECLARATIONS.append(declaration('zb_',k,t,m,s,SOURCES[s],**kw))
for k,m,o,s in [('phy','Actual qualified PHY edition, not all futureZigbeePHYsame250k.',['IEEE_2G4_2006','REGISTERED_ACTUAL'],TI),('stack','Actual stackimplementation/revision.',['EMBERZNET_8_2_1','REGISTERED_ACTUAL'],API),('delivery','Actual unicast/multicast/broadcast semantics.',['UNICAST','MULTICAST','BROADCAST'],API),('outcome','Actual independent consumingfunction result.',['ACCEPTED','APS_ACK_ONLY','QUEUED','ERROR','UNKNOWN'],API)]:d(k,'select',m,s,options=o)
for k,m,lo,hi,u,integer,s in [('rate_bps','Actual selectedPHY data rate, not meshapplicationthroughput.',1,None,'bit/s',False,TI),('psdu_bytes','ActualMACheader+NWK+APS+security+application+FCS.',0,None,'byte',True,TI),('mac_bytes','Actual selectedMACaddressing/headerbytes.',0,None,'byte',True,TI),('nwk_bytes','Actual selectedNWK/source-route/longaddressheaderbytes.',0,None,'byte',True,TI),('aps_bytes','Actual selected APSheaderbytes.',0,None,'byte',True,TI),('security_bytes','Actual auxiliaryheaders/tags selectedNWKandAPS security.',0,None,'byte',True,TI),('fcs_bytes','Actual MACFCSbytes.',0,None,'byte',True,TI),('phy_bytes','Actual completepreamble/SFD/PHRprefix.',0,None,'byte',True,TI),('peer_aps_max','Actual node-descriptor/security payload limit; no universal68/82/127.',0,255,'byte',True,API),('frame_application_bytes','Actual singlefragmentapplicationbytes; wholeapplication maylarger.',0,None,'byte',True,API),('air_us','Nominal oneframeairtime; excludesCCA/backoff/retries/host.',0,None,'us',False,TI),('max_hops','Actual commissioned SL_ZIGBEE_MAX_HOPSconfiguration.',1,None,None,True,API),('aps_ack_ms','Actualstackselected APSACKtimeout; overrideuint16 separatedeadline.',0,65535,'ms',True,API),('attempts','Actual APS_RETRY implementationtransmissionsincludingfirst.',1,None,None,True,API),('sequence','Actual8bit APSsequence unchangedsubsequentfragments.',0,255,None,True,API),('first_sequence','Actual firstfragmentsequencecorrelation.',0,255,None,True,API),('fragment_index','Actual fragmentindex;0firstsequenceassignment.',0,255,None,True,API),('indirect_ms','Actualsleepychildindirectretention/parenttimeout.',0,None,'ms',False,API),('source_ms','Actualapplication/encoding/securityprocessingbound.',0,None,'ms',False,API),('mesh_ms','Actualroute/CCA/backoff/fragment/retry/sleepyforwardpathbound.',0,None,'ms',False,API),('use_ms','Actual consumingfunctionprocessingbound.',0,None,'ms',False,API),('e2e_ms','Actual source-to-usebound independent MACorAPSACK.',0,None,'ms',False,API),('deadline_ms','Independent consumingfunctiondeadline.',0,None,'ms',False,API),('age_ms','Actual consumeddataage.',0,None,'ms',False,API),('freshness_ms','Independent allowabledataage.',0,None,'ms',False,API)]:d(k,'number',m,s,min=lo,max=hi,unit=u,integer=integer)
for k,m in [('aps_retry','Actual APSretryflag distinct MACretry.'),('forced_discovery','Actual first transmission consumedbyroute request.'),('ack_default','Actual unmodified sourceSDKtimeout versusexplicitoverride.'),('fragmented','Actual fragment/reassemblysupport enabled.'),('path_verified','Actualcomplete peers/routes/sleepybuffers/securityreassembly evidence.'),('data_accepted','Actual independent consumingfunction succeeds.')]:d(k,'boolean',m)
for k,m in [('revision','Actual protocol/device/stackedition.'),('device_source','Actual node-descriptor/security/fragment/buffercapability.'),('phy_source','Actualradio/frame/CCA/backoffconfigurationandcapability.'),('mesh_source','Actual routes/retries/sleepyparent/window/bufferpathbound.'),('security_source','Actual protectedcommissioning/key/counter/replayevidence, no inlinekey.'),('acceptance_source','Independent functiondeadline/freshness/errorcontract.'),('observation_source','Actual correlatedsource/radio/fragment/consumertrace.')]:d(k,'text',m)
d('destination_eui64','text','Actual8byte peeridentityashexadecimalstring;neverlossyJSnumber.',pattern='^[0-9A-Fa-f]{16}$')
REQUIRED=('revision','device_source','phy_source','mesh_source','security_source','acceptance_source')
REMOVED={k:'Zigbee explicitPHY/MAC/NWK/APS/sleepypeerparameters; no foreignCAN/gatewayrate defaults.' for k in WIRE_KEYS}
def semantics():
 rules=[]
 def r(k,w=None,s=API,**kw):rules.append(dict(parameter='zb_'+k,when={'zb_'+a:b for a,b in(w or {}).items()},source=s,**kw))
 rules.extend(dict(parameter=k,when={},allowed=[],source=TI)for k in REMOVED)
 r('rate_bps',{'phy':'IEEE_2G4_2006'},allowed=[250000],s=TI);r('psdu_bytes',{'phy':'IEEE_2G4_2006'},maximum=127,s=TI);r('phy_bytes',{'phy':'IEEE_2G4_2006'},allowed=[6],s=TI);r('fcs_bytes',{'phy':'IEEE_2G4_2006'},allowed=[2],s=TI)
 r('psdu_bytes',equal_expression={'sum':['zb_mac_bytes','zb_nwk_bytes','zb_aps_bytes','zb_security_bytes','zb_frame_application_bytes','zb_fcs_bytes']},s=TI)
 r('frame_application_bytes',maximum_parameter='zb_peer_aps_max');r('frame_application_bytes',{'fragmented':False},equal_parameter='payload_bytes')
 r('air_us',equal_ratio={'numerator_sum':['zb_psdu_bytes','zb_phy_bytes'],'denominator_parameter':'zb_rate_bps','factor':8000000},s=TI)
 r('aps_ack_ms',{'stack':'EMBERZNET_8_2_1','ack_default':True},equal_expression={'sum':[100,{'product':['zb_max_hops',50]}]})
 r('attempts',{'stack':'EMBERZNET_8_2_1','aps_retry':True},maximum=3);r('aps_retry',{'forced_discovery':True},required=True,allowed=[True])
 r('sequence',{'fragmented':True},when_positive=['zb_fragment_index'],equal_parameter='zb_first_sequence')
 r('e2e_ms',equal_expression={'sum':['zb_source_ms','zb_mesh_ms','zb_use_ms']},maximum_parameter='zb_deadline_ms');r('age_ms',maximum_parameter='zb_freshness_ms')
 for k in('source_ms','mesh_ms','use_ms'):r(k,when_present=['zb_e2e_ms'],required=True)
 for k in('e2e_ms','deadline_ms','age_ms','freshness_ms','observation_source'):r(k,{'data_accepted':True},required=True)
 r('path_verified',{'data_accepted':True},required=True,allowed=[True]);r('outcome',{'data_accepted':True},required=True,allowed=['ACCEPTED'])
 return dict(rate_model={'type':'ZIGBEE_ACTUAL_PHY_MESH','fields':[]},parameter_evidence_scope='EXPLICIT_LAYER',required_parameters=['zb_'+k for k in REQUIRED],native_parameter_prefixes=['zb_'],parameter_constraints=rules,medium_access_model='ACTUAL_CSMACA_AND_SLEEPY_MESH',arbitration_model_id='SELECTED_PHY_MAC_APS',mechanisms={'network':['MAC_PSDU_NOT_APS_PAYLOAD','APS_ACK_NOT_CONSUMERRESULT'],'timing':['ACTUAL_BACKOFF_ROUTE_RETRY_SLEEPY_HOST_PATH']})
def fields():return build_fields(DECLARATIONS,['zb_'+k for k in REQUIRED],{'zb_'+k:[dict(when={'zb_phy':'IEEE_2G4_2006'},value=v,source=TI,source_revision=SOURCES[TI])]for k,v in [('rate_bps',250000),('phy_bytes',6),('fcs_bytes',2)]})
