"""TSN tools require their own source-backed configuration, not an Ethernet rate.

Public IEEE management models and a pinned Linux mapping are reviewed here.
They do not constitute a complete wire/state-machine or hardware certificate.
"""
from backend.nis.communication.services.native_review_support import declaration, fields as build_fields, WIRE_KEYS, ETHERNET_KEYS
ROOT='https://www.ieee802.org/1/files/public/YANGs/'
SUMMARY='https://www.ieee802.org/1/files/public/docs2026/admin-tsn-summary-0326-v01.pdf'
SCHED=ROOT+'ieee802-dot1q-sched.yang';PREEMPT=ROOT+'ieee802-dot1q-preemption.yang';PSFP=ROOT+'ieee802-dot1q-psfp.yang';ATS=ROOT+'ieee802-dot1q-ats.yang';FRER=ROOT+'ieee802-dot1cb-frer.yang';GPTP=ROOT+'ieee802-dot1as-gptp.yang';TYPES=ROOT+'ieee802-types.yang';QTYPES=ROOT+'ieee802-dot1q-types%402023-10-22.yang';CNC=ROOT+'ieee802-dot1q-cnc-config.yang';CBSA=ROOT+'ieee802-dot1q-cbsa.yang'
TAPRIO='https://raw.githubusercontent.com/iproute2/iproute2/v6.17.0/man/man8/tc-taprio.8';CBS='https://raw.githubusercontent.com/iproute2/iproute2/v6.17.0/man/man8/tc-cbs.8';CQF='https://www.nxp.com/docs/en/user-guide/REALTIMEEDGEUG_Rev2.3.pdf'
SOURCES={SUMMARY:'IEEE TSN summary9March2026; separate toolsets/profiles. Tool registration does not mean every tool is executed/certified.',SCHED:'IEEE802.1Qcw YANG22October2023: scheduling perport gate list,8bitstates, rationalcycle, actual supported limits, admin vsoper.',PREEMPT:'IEEE802.1Qcw YANG26October2023: perpriorityExpressdefault, actualMAC hold/release advance andactive state, no universal64bytefragment guess.',PSFP:'IEEE802.1Qcw YANG26October2023: flowmeterCIR/EIR bits/s, CBS/EBS octets, mandatorycolor/coupling/yellowdrop, streamgates.',ATS:'IEEE802.1Qcz YANG3July2023: committedrate bits/s butburst bits, schedulergroup/reference/residence andperport timing.',FRER:'IEEE802.1CB YANG8December2021: independent generation/identification/recovery, vector/historymin2 vsmatch, reset/no-sequence/latenterror requirements.',GPTP:'IEEE802.1AS YANG10December2025: actualAScapability, logintervalsource, receiptcounts, scaled neighbor ratio, one-step/clock properties; no universalfixed synchronizationerror.',TYPES:'IEEE common publicYANG: rationaluint32 denominator≥1, PTP48bitseconds/nanoseconds<1e9.',QTYPES:'IEEE802.1Q types22October2023: basegateentries index/operation/uint32ns interval; no assumed consecutiveindexes.',CNC:'IEEE802.1Q CNC publicYANG31January2024: domain/CUC/stream/talker/listener/status. compute RPCstart is not actual successfulreservation.',CBSA:'IEEE802.1Qdx YANG7August2024: CBS pertrafficclass admin/oper idle slope bits/s, adminignored ifSRPactive, default0 means noreservation.',TAPRIO:'iproute2 pinnedv6.17.0 TAPRIO manpage: simplifiedIEEE2018mapping,0/1/2 flags,PHC vsclockid, queueMaxSDU0inheritMTU, S/H/R,GCLns andactualoffload.',CBS:'iproute2 pinnedv6.17.0 CBS manpage: kbit/s mapping, actualwholewireoverhead, send=idle−port, high/lowcredit AnnexL simplemodel; not arbitrarymulticlassnetworkbound.',CQF:'NXP RealTimeEdgeUG Rev2.3 28July2022 section7.4 printed99: implementation-specificCQF equalcycle/gatetime andintegercycle multiple. Example10000/2000ns is notnormative default.'}
DECLARATIONS=[]
def d(k,t,meaning,source=SCHED,**kw):DECLARATIONS.append(declaration('tn_',k,t,meaning,source,SOURCES[source],**kw))
for k,meaning,opts,src in [
 ('review_profile','Actual supported management baseline or independent variant.',['IEEE_PUBLIC_MODELS','REGISTERED_ACTUAL'],SUMMARY),('proposal_mode','Source proposals versus commissioned actual configuration.',['SOURCE_BASELINE','ACTUAL_CONFIG'],SUMMARY),
 ('mapping','Actual IEEE management or pinnedLinux implementation semantics.',['IEEE_YANG','LINUX_IPROUTE2_6_17','REGISTERED_ACTUAL'],TAPRIO),
 ('preemption_status','Actual current selected priority service; eachpriorityindependent.',['EXPRESS','PREEMPTABLE'],PREEMPT),('hold_request','Actual MAC hold/release state, initializationrelease not observeddefault.',['HOLD','RELEASE'],PREEMPT),
 ('color_mode','Actual bandwidth profile ignores or considers inputcolor.',['COLOR_BLIND','COLOR_AWARE'],PSFP),('coupling','Actual uncoupled0 orcoupled1 meter.',['ZERO','ONE'],PSFP),('cbs_model','Actual selected simpleAnnexLcreditformula versus independentlyqualifiedshapercomposition.',['SIMPLE_ANNEX_L','REGISTERED_ACTUAL'],CBS),
 ('recovery_algorithm','Actual FRER vector or match recovery; vendor requires own codec.',['VECTOR','MATCH','REGISTERED_ACTUAL'],FRER),('cqf_profile','Actual selected CQF implementation scope.',['NXP_RTE_2_3','REGISTERED_ACTUAL'],CQF),
 ('stream_status','Actual reservation/computation status;STARTED notsuccessfulREADY.',['STARTED','READY','FAILED','UNKNOWN'],CNC),('outcome','Actual correlated consumer result.',['ACCEPTED','STALE','ERROR','UNKNOWN'],SUMMARY),
]:d(k,'select',meaning,source=src,options=opts)
NUMBERS=[
 ('link_bps','Actual bound perhop physical link rate; no TSNuniversal1Gbit/s.',1,None,'bit/s',True,SUMMARY),
 ('traffic_class','Actual IEEE priority/queueclass0..7, Linuxextended0..15 onlyseparatelymapped.',0,15,None,True,QTYPES),('queue_max_sdu','Actual perclassL2maxSDU;0 inherits underlyingMACmax, not zerocapacity.',0,4294967295,'byte',True,SCHED),('mac_max_sdu','Actual boundMAC supportedmaxSDU, not a fixedTSN1500cap.',1,None,'byte',True,SCHED),
 ('admin_gate_states','Actual admininitialgates bit7..0 class7..0, sourceproposal255 allopen.',0,255,None,True,SCHED),('oper_gate_states','Actual observed runninggates independent ofadmin.',0,255,None,True,SCHED),
 ('cycle_numerator','Actual admincycle rational numeratorseconds uint32.',0,4294967295,None,True,TYPES),('cycle_denominator','Actual cycle rationaldenominator≥1.',1,4294967295,None,True,TYPES),('cycle_ns','Actual source-resolved cycle innanoseconds, distinctstreamperiod.',0,None,'ns',False,SCHED),
 ('supported_cycle_ns','Actual port supported cyclemaximum, not invented1ms.',0,None,'ns',False,SCHED),('cycle_extension_ns','Actual maximumpermitted extension on reconfiguration, not everycycleguard.',0,4294967295,'ns',True,SCHED),
 ('base_seconds','Actual PTPtimescale48bitseconds; no frozenUnixdefault.',0,281474976710655,'s',True,TYPES),('base_nanoseconds','Actual fractionalPTPtime<1e9ns.',0,999999999,'ns',True,TYPES),
 ('tick_tenths_ns','Actual portclock granularityunit0.1ns, not whole ns.',0,4294967295,'0.1ns',True,SCHED),('tick_ns','Actual converted portclocktick, not synchronizedaccuracy.',0,None,'ns',False,SCHED),
 ('supported_list_max','Actual devicegate-table capacityentries.',0,4294967295,None,True,SCHED),('supported_interval_max_ns','Actual port maximumsingleGCLinterval.',0,4294967295,'ns',True,SCHED),('gcl_sum_ns','Actual aggregateintervals, Linuxsum=cycle,IEEEowncyclequalification.',0,None,'ns',True,SCHED),
 ('gate_open_ns','Actual aggregateapplicableclassservice window includingknownschedule.',0,None,'ns',False,SCHED),('guard_ns','Actual qualified interferingframe/preemption+clock guard envelope, notfixeddefault.',0,None,'ns',False,SCHED),('serialization_ns','Actual wholeframeoccupiedserialization bound.',0,None,'ns',False,SCHED),('clock_error_ns','Actual relativeclockoffset/drift bound alongpath.',0,None,'ns',False,GPTP),
 ('taprio_flags','Actual Linux0software/1txtimeassist/2offload;3invalid.',0,3,None,True,TAPRIO),('num_tc','Actual Linuxtrafficclasses≤16, differentfromIEEE8bitgatetable.',1,16,None,True,TAPRIO),('txtime_delay_ns','Actual maximumtaprio-toNIC delay, mustexceedETFdelta.',0,4294967295,'ns',True,TAPRIO),('etf_delta_ns','Actual ETF advance/wakeupbound.',0,None,'ns',True,TAPRIO),
 ('idle_bps','Actual perclass CBS reservedbitrate, adminignored ifSRPactive.',0,None,'bit/s',False,CBSA),('admin_idle_bps','Actual managementrequested CBS bits/s;0noreservation.',0,None,'bit/s',True,CBSA),('send_bps','Actual CBS sendcreditdepletion idle−port, normallynegative.',None,0,'bit/s',False,CBS),
 ('hi_credit_bytes','Actual simpleCBS highcredit bound frommaxinterference*idle/port.',0,None,'byte',False,CBS),('lo_credit_bytes','Actual simpleCBS lowcredit frommaxframe*send/port.',None,0,'byte',False,CBS),('max_interference_bytes','Actual totalinterferingburstwireoccupation, notpayloadonly.',0,None,'byte',True,CBS),('max_frame_bytes','Actual completepacketwireoccupation includingalllayers/IPG.',0,None,'byte',True,CBS),
 ('cir_bps','Actual PSFP committedinformation rate, uint64 wire/model value mustlossless.',0,None,'bit/s',True,PSFP),('eir_bps','Actual PSFP excessinformation rate.',0,None,'bit/s',True,PSFP),('cbs_octets','Actual PSFP committedburst inoctets, distinctATSburstbits.',0,4294967295,'byte',True,PSFP),('ebs_octets','Actual PSFP excessburst octets.',0,4294967295,'byte',True,PSFP),
 ('interval_octet_max','Actual optional streamgate bytebudget; omittedmeansnolim,0zero notwildcard.',0,4294967295,'byte',True,PSFP),('stream_sdu_max','Actual filtermaximumSDU, independentqueueMaxSDU.',0,4294967295,'byte',True,PSFP),
 ('hold_advance_ns','Actual underlyingMAC property; no standarddefault.',0,4294967295,'ns',True,PREEMPT),('release_advance_ns','Actual underlyingMAC property; no standarddefault.',0,4294967295,'ns',True,PREEMPT),('fragment_block_ns','Actual maximumresidualpreemptablefragment blocking, not fixed64octets.',0,None,'ns',False,PREEMPT),
 ('ats_cir_bps','Actual ATS committedinformation rate inbits/s.',0,None,'bit/s',True,ATS),('ats_burst_bits','Actual ATS committedburst bits, notPSFPoctets.',0,4294967295,'bit',True,ATS),('ats_group_id','Actual existing scheduler-groupreference, notgenerateddefault.',0,4294967295,None,True,ATS),('ats_residence_ns','Actual scheduler group maxresidence time.',0,4294967295,'ns',True,ATS),('ats_processing_min_ns','Actual portpairminimumprocessing.',0,4294967295,'ns',True,ATS),('ats_processing_max_ns','Actual portpairmaximumprocessing.',0,4294967295,'ns',True,ATS),('ats_clock_variation_ns','Actual portpairclockvariationmax.',0,4294967295,'ns',True,ATS),('ats_rate_deviation_ppm','Actual portpairclockratedeviationmax.',0,4294967295,'ppm',True,ATS),('ats_recognition_ns','Actual arrivalrecognitionmaxdelay.',0,4294967295,'ns',True,ATS),
 ('cqf_gate_ns','Actual NXPconfiguration gateopen duration, not globalCQFdefault.',1,None,'ns',True,CQF),('cqf_cycle_ns','Actual NXPconfigurationcycle multipleofgate.',1,None,'ns',True,CQF),
 ('frer_history','Actual vectorhistorybits min2, matchalgorithmdoesnotuseit.',0,4294967295,'bit',True,FRER),('frer_history_max','Actual implementationmaximumhistory.',2,4294967295,'bit',True,FRER),('frer_reset_ms','Actual recoverytimeout, no invented400ms.',0,4294967295,'ms',True,FRER),('frer_paths','Actual configuredreplication/latenterrorpathcount uint16.',0,65535,None,True,FRER),('frer_difference','Actual latenterror signedcounterdifference threshold.',-2147483648,2147483647,None,True,FRER),('frer_period_ms','Actual latenterrortest period, proposal2000ms.',0,4294967295,'ms',True,FRER),('frer_reset_period_ms','Actual latenterrorreset period, proposal30000ms.',0,4294967295,'ms',True,FRER),('sequence_space','Actual encoding-dependentRecovSeqSpace, not always16bitRtag.',1,4294967295,None,True,FRER),('invalid_sequence','Actual read-onlyvaluecannotbeencoded,≥sequence_space.',0,4294967295,None,True,FRER),
 ('neighbor_ratio_scaled','Actual fractional(rateRatio−1)*2^41 signedint32.',-2147483648,2147483647,None,True,GPTP),('neighbor_ratio','Actual convertedneighborrate ratio, notscaledintegerasdirectratio.',0,None,None,False,GPTP),('sync_interval_s','Actual current2^logSync seconds, nosetuniversal125ms.',0,None,'s',False,GPTP),('sync_receipt_count','Actual allowedmissingsyncintervals beforetimeout.',0,255,None,True,GPTP),('allowed_lost_responses','Actual allowedPdelaylostresponses.',0,255,None,True,GPTP),('allowed_faults','Actual allowedfaults beforeAScapabilitylost.',0,255,None,True,GPTP),
 ('source_ms','Actual producer/encode/queue envelope.',0,None,'ms',False,SUMMARY),('transport_ms','Actual allhopPHY/queue/shaping/replication/acceptance envelope.',0,None,'ms',False,SUMMARY),('consumer_ms','Actual decode/use envelope.',0,None,'ms',False,SUMMARY),('e2e_ms','Actual wholeproducer+transport+consumer bound.',0,None,'ms',False,SUMMARY),('deadline_ms','Actual independentfunctional deadline.',0,None,'ms',False,SUMMARY),('age_ms','Actual source-to-use correlatedage.',0,None,'ms',False,SUMMARY),('freshness_ms','Actual independentacceptableage.',0,None,'ms',False,SUMMARY),
]
for k,meaning,lo,hi,unit,integer,src in NUMBERS:
 if k in('admin_idle_bps','cir_bps','eir_bps','ats_cir_bps'):hi=18446744073709551615
 d(k,'number',meaning,source=src,min=lo,max=hi,unit=unit,integer=integer)
for kind in('sync','announce','pdelay','gptp_cap'):
 for prefix in('initial','current','mgt'):d(prefix+'_log_'+kind,'number','Actual '+prefix+' log2 '+kind+' interval inseconds; signedint8, edition/state-message sentinelsemantics independentlyqualified.',source=GPTP,min=-128,max=127,integer=True)
 d('use_mgt_'+kind,'boolean','Actual managementintervalsource versus Signaling/state-machine for '+kind+'.',source=GPTP)
for k,meaning,src in [
 ('gate_enabled','Actual schedulingactive; publicYANGdefaultfalse.',SCHED),('config_change','Actual adminconfiguration change trigger, notoperconfirmation.',SCHED),('config_pending','Actual operationalupdatepending state.',SCHED),
 ('cbs_enabled','Actual selectedCBSmechanism, not everyTSNqueue.',CBSA),('srp_active','Actual SRPreservationcontrolsoper-idleslope; adminnoeffect.',CBSA),('psfp_enabled','Actual perstreamfilter/policingselected.',PSFP),('meter_enabled','Actual flowmeter bound tostreamfilter.',PSFP),('drop_on_yellow','Actual yellowdrop versusmarkdropeligible.',PSFP),('mark_red_enable','Actual markallred mechanismenabled.',PSFP),('mark_red','Actual current allred state, notdefaultassumedrunning.',PSFP),
 ('preemption_enabled','Actual express/preemptable services selected anddevicecapabilityqualified.',PREEMPT),('preemption_active','Actual MACpreemptionoperationallyactive.',PREEMPT),('ats_enabled','Actual streamfilterATSschedulerassociationenabled.',ATS),('cqf_enabled','Actual selectedCQFpath.',CQF),('frer_enabled','Actual bound replication/recoverypath.',FRER),('frer_individual','Actual IndividualRecovery excludeslatenterrordetection.',FRER),('frer_latent','Actual latenterrorfunction instantiated.',FRER),('take_no_sequence','Actual untaggedpacketacceptpolicy.',FRER),('frer_reset','Actual resetrequest readfalse, writeTrue triggersreset.',FRER),
 ('sync_required','Actual selectedmechanismrequirescommon timescale; ATSalonecanasynchronous.',SUMMARY),('as_capable','Actual linkandpeer802.1ASinteroperability determined, notclockaccuracyproof.',GPTP),('sync_locked','Actual operationalclocklocked.',GPTP),('path_verified','Actual allhopfeatures/clock/guards/resourcesconfiguredandverified.',SUMMARY),('data_accepted','Actual functionacceptedfreshcorrelateddata.',SUMMARY),
]:d(k,'boolean',meaning,source=src)
for k,meaning,src in [
 ('revision','Actual selectededitions/toolset/device/buildrevision.',SUMMARY),('configuration_source','Actual commissionedTSNprofile/toolset andperhopconfiguration.',SUMMARY),('phy_source','Actual boundlinkduplex/rate/packet/MTU/PHYrealization.',SUMMARY),('schedule_source','Actual correlatedallhopGCL/shaper/queue/guard/load bound.',SCHED),('acceptance_source','Actual functionaldeadline/freshness contract.',SUMMARY),('registered_source','Actual independentlyqualifiededition/tool extension.',SUMMARY),('observation_source','Actual runningconfiguration andsource-to-use packet/consumertrace.',SUMMARY),
 ('gcl_json','Actual normalizedgateentries index/operation S,H,R/mask/interval_ns, notexecutableYANGwrite.',SCHED),('clockid','Actual Linuxsoftwareclock source;mustabsentfullhardwareoffload.',TAPRIO),('phc_source','Actual NIC PHC binding/offset/discipline source.',TAPRIO),('queue_mapping_source','Actual priority/class/contiguousnonoverlapping hardwarequeues.',TAPRIO),
 ('preemption_source','Actual bothMACs/PHYandhold/release/residualfragment qualification.',PREEMPT),('psfp_source','Actual streamidentity/gate/meter/SDU/color/rates/policyevidence.',PSFP),('ats_source','Actual registeredgroup/portpair/residence/eligibilityscheduler evidence.',ATS),('cqf_source','Actual CQFbuffer/phasing/clock/allhopdeviceimplementation.',CQF),('frer_source','Actual distinctpaths/streamidentity/sequence/codec/history/reset/recovery evidence.',FRER),('gptp_source','Actual gPTPdomain/clock/PTPtimescale/sync/peer-delay/asCapable qualification.',GPTP),
 ('cbs_source','Actual shaper/guard/priority composition qualification and selectedcreditmodel.',CBS),('domain_id','Actual configurationdomain independent ofgPTPdomainnumber.',CNC),('cuc_id','Actual identifiedusernetworkcontroller.',CNC),('stream_id','Actual boundedstreamidentity andtalker/listener association.',CNC),('reservation_source','Actual completedCNC/computation/resource installation, RPCstartedinsufficient.',CNC),
]:d(k,'text',meaning,source=src)
REQUIRED=('review_profile','mapping','revision','configuration_source','phy_source','schedule_source','acceptance_source')
REMOVED={k:'TSN selects separatemechanisms andactual lowerlayer links, not CANretry/gateway or inheritedgenericEthernetparameters/default1Gbps.'for k in(*WIRE_KEYS,*ETHERNET_KEYS)}
def semantics():
 rules=[]
 def r(k,w=None,src=SCHED,**kw):rules.append(dict(parameter='tn_'+k,when={'tn_review_profile':'IEEE_PUBLIC_MODELS',**{'tn_'+a:b for a,b in(w or{}).items()}},source=src,**kw))
 rules.append(dict(parameter='tn_registered_source',when={'tn_review_profile':'REGISTERED_ACTUAL'},required=True,source=SUMMARY))
 rules.extend(dict(parameter=k,when={},allowed=[],source=SUMMARY)for k in REMOVED)
 r('cycle_ns',equal_ratio={'numerator_parameter':'tn_cycle_numerator','denominator_parameter':'tn_cycle_denominator','factor':1000000000},maximum_parameter='tn_supported_cycle_ns')
 r('tick_ns',equal_expression={'product':['tn_tick_tenths_ns',.1]})
 for mapping,mask_max in [('IEEE_YANG',255),('LINUX_IPROUTE2_6_17',65535)]:r('gcl_json',{'mapping':mapping},json_gate_schedule=dict(mask_max=mask_max,commands=['S','H','R'],max_entries_parameter='tn_supported_list_max',max_interval_parameter='tn_supported_interval_max_ns',sum_parameter='tn_gcl_sum_ns'))
 r('traffic_class',{'mapping':'IEEE_YANG'},maximum=7)
 r('gcl_sum_ns',{'mapping':'LINUX_IPROUTE2_6_17'},equal_parameter='tn_cycle_ns',src=TAPRIO)
 for k in('gcl_json','cycle_ns','supported_cycle_ns','supported_list_max','supported_interval_max_ns','base_seconds','base_nanoseconds'):r(k,{'gate_enabled':True},required=True)
 for k in('cycle_numerator','cycle_denominator'):r(k,when_present=['tn_cycle_ns'],required=True)
 r('queue_max_sdu',when_greater_than={'tn_queue_max_sdu':0},maximum_parameter='tn_mac_max_sdu')
 r('taprio_flags',allowed=[0,1,2],src=TAPRIO)
 r('clockid',{'mapping':'LINUX_IPROUTE2_6_17','taprio_flags':2},allowed=[],src=TAPRIO);r('phc_source',{'mapping':'LINUX_IPROUTE2_6_17','taprio_flags':2},required=True,src=TAPRIO)
 r('txtime_delay_ns',{'mapping':'LINUX_IPROUTE2_6_17','taprio_flags':1},exclusive_minimum_expression='tn_etf_delta_ns',src=TAPRIO)
 r('send_bps',{'cbs_enabled':True,'cbs_model':'SIMPLE_ANNEX_L'},equal_expression={'subtract':['tn_idle_bps','tn_link_bps']},src=CBS)
 r('idle_bps',{'cbs_enabled':True},maximum_parameter='tn_link_bps',src=CBS)
 r('idle_bps',{'cbs_enabled':True,'srp_active':False},equal_parameter='tn_admin_idle_bps',src=CBSA)
 r('hi_credit_bytes',{'cbs_enabled':True,'cbs_model':'SIMPLE_ANNEX_L'},equal_ratio={'numerator_product':['tn_max_interference_bytes','tn_idle_bps'],'numerator_offset':1,'denominator_parameter':'tn_link_bps'},src=CBS)
 r('lo_credit_bytes',{'cbs_enabled':True,'cbs_model':'SIMPLE_ANNEX_L'},equal_ratio={'numerator_product':['tn_max_frame_bytes','tn_send_bps'],'numerator_offset':1,'denominator_parameter':'tn_link_bps'},src=CBS)
 for k in('cbs_model','cbs_source','link_bps','idle_bps'):r(k,{'cbs_enabled':True},required=True,src=CBS)
 for k in('send_bps','hi_credit_bytes','lo_credit_bytes','max_interference_bytes','max_frame_bytes'):r(k,{'cbs_enabled':True,'cbs_model':'SIMPLE_ANNEX_L'},required=True,src=CBS)
 for k in('psfp_source','stream_sdu_max'):r(k,{'psfp_enabled':True},required=True,src=PSFP)
 for k in('cir_bps','eir_bps','cbs_octets','ebs_octets','color_mode','coupling','drop_on_yellow'):r(k,{'meter_enabled':True},required=True,src=PSFP)
 for k in('preemption_source','hold_advance_ns','release_advance_ns','fragment_block_ns','preemption_active'):r(k,{'preemption_enabled':True},required=True,src=PREEMPT)
 r('guard_ns',{'preemption_enabled':True},minimum_expression={'sum':['tn_fragment_block_ns','tn_clock_error_ns']},src=PREEMPT)
 r('guard_ns',{'preemption_enabled':False},minimum_expression={'sum':['tn_serialization_ns','tn_clock_error_ns']})
 r('ats_processing_min_ns',maximum_parameter='tn_ats_processing_max_ns',src=ATS)
 for k in('ats_source','ats_cir_bps','ats_burst_bits','ats_group_id','ats_residence_ns','ats_processing_max_ns','ats_clock_variation_ns','ats_rate_deviation_ppm','ats_recognition_ns'):r(k,{'ats_enabled':True},required=True,src=ATS)
 for k in('cqf_profile','cqf_source'):r(k,{'cqf_enabled':True},required=True,src=CQF)
 r('cqf_cycle_ns',{'cqf_profile':'NXP_RTE_2_3'},equal_expression={'subtract':['tn_cqf_cycle_ns',{'integer_remainder':['tn_cqf_cycle_ns','tn_cqf_gate_ns']}]},src=CQF)
 r('frer_history',{'recovery_algorithm':'VECTOR'},minimum=2,maximum_parameter='tn_frer_history_max',src=FRER)
 r('frer_latent',{'frer_individual':True},allowed=[False],src=FRER)
 r('invalid_sequence',minimum_parameter='tn_sequence_space',src=FRER)
 for k in('frer_source','recovery_algorithm','frer_reset_ms','sequence_space'):r(k,{'frer_enabled':True},required=True,src=FRER)
 for k in('frer_paths','frer_difference','frer_period_ms','frer_reset_period_ms'):r(k,{'frer_latent':True},required=True,src=FRER)
 r('neighbor_ratio',equal_expression={'sum':[1,{'product':['tn_neighbor_ratio_scaled',2**-41]}]},src=GPTP)
 for kind in('sync','announce','pdelay','gptp_cap'):r('current_log_'+kind,{'use_mgt_'+kind:True},equal_parameter='tn_mgt_log_'+kind,src=GPTP)
 r('sync_interval_s',equal_expression={'power':[2,'tn_current_log_sync']},src=GPTP)
 for k in('gptp_source','clock_error_ns','as_capable','sync_locked'):r(k,{'sync_required':True},required=True,src=GPTP)
 for k in('as_capable','sync_locked'):r(k,{'sync_required':True,'data_accepted':True},allowed=[True],src=GPTP)
 r('gate_open_ns',{'gate_enabled':True},minimum_expression={'sum':['tn_serialization_ns','tn_guard_ns']})
 r('e2e_ms',equal_expression={'sum':['tn_source_ms','tn_transport_ms','tn_consumer_ms']},maximum_parameter='tn_deadline_ms',src=SUMMARY);r('age_ms',maximum_parameter='tn_freshness_ms',src=SUMMARY)
 for k in('source_ms','transport_ms','consumer_ms'):r(k,when_present=['tn_e2e_ms'],required=True,src=SUMMARY)
 for k in('observation_source','e2e_ms','deadline_ms','age_ms','freshness_ms','stream_id','reservation_source'):r(k,{'data_accepted':True},required=True,src=SUMMARY)
 for k,v in [('path_verified',True),('stream_status','READY'),('config_pending',False),('outcome','ACCEPTED')]:r(k,{'data_accepted':True},required=True,allowed=[v],src=SUMMARY)
 return dict(rate_model={'type':'EXPLICIT_TSN_TOOLSET_AND_PHY','fields':[]},parameter_evidence_scope='EXPLICIT_LAYER',required_parameters=['tn_'+k for k in REQUIRED],native_parameter_prefixes=['tn_'],parameter_constraints=rules,medium_access_model='ACTUAL_TAS_CBS_PSFP_ATS_CQF_FRER_COMPOSITION',arbitration_model_id='ACTUAL_PORT_FEATURES_SCHEDULE_AND_CLOCK',mechanisms={'network':['SELECTED_TSN_TOOLS_NOT_ALL_AUTOMATICALLY_ACTIVE'],'timing':['ACTUAL_ALLHOP_CLOCK_GUARD_RESOURCE_ENVELOPE','CONSUMER_ACCEPTANCE_SEPARATE']})
def fields():
 baseline={'tn_review_profile':'IEEE_PUBLIC_MODELS','tn_proposal_mode':'SOURCE_BASELINE'}
 proposals={}
 for k,v,src,w in [('gate_enabled',False,SCHED,{}),('admin_gate_states',255,SCHED,{}),('queue_max_sdu',0,SCHED,{}),('preemption_status','EXPRESS',PREEMPT,{}),('admin_idle_bps',0,CBSA,{}),('mark_red_enable',False,PSFP,{}),('mark_red',False,PSFP,{}),('ats_enabled',False,ATS,{}),('frer_history',2,FRER,{'tn_recovery_algorithm':'VECTOR'}),('take_no_sequence',False,FRER,{}),('frer_reset',False,FRER,{}),('frer_period_ms',2000,FRER,{'tn_frer_latent':True}),('frer_reset_period_ms',30000,FRER,{'tn_frer_latent':True})]:
  proposals.setdefault('tn_'+k,[]).append(dict(when={**baseline,**w},value=v,source=src,source_revision=SOURCES[src]))
 out=build_fields(DECLARATIONS,['tn_'+k for k in REQUIRED],proposals)
 for f in out:
  if f['key']not in {'tn_'+k for k in REQUIRED}|{'tn_proposal_mode','tn_registered_source'}:f['schema_when']={'tn_review_profile':'IEEE_PUBLIC_MODELS'}
 return out
