FROM sha256:7342994da211ca290f849bccbeb0a2262bc69eda2da358a2fea730d4d7e6b1bc
LABEL networkis.development=true
COPY . /app
RUN python /app/scripts/write-build-info.py
RUN cd /app/frontend && node /usr/local/lib/node_modules/npm/bin/npm-cli.js run build
