"""XCP source-qualified application and negotiated lower transport parameters."""
from backend.nis.communication.services.native_review_support import declaration, fields as build_fields, WIRE_KEYS, ETHERNET_KEYS
AUTO='https://www.autosar.org/fileadmin/standards/R25-11/CP/AUTOSAR_CP_SWS_XCP.pdf'
ASAM='https://www.asam.net/standards/detail/mcd-1-xcp/'
SOURCES={AUTO:'OriginalAUTOSARCPR25-11XCP82p selected7.1-7.4/10.2.1/10.2.8: nativeCAN/FlexRay/TCP/UDPbindings, noPHYrate, MAX_CTO8..255/MAX_DTO8..65535no default, DAQ/ODT/event bounds, timeunit and0noncyclic, ODTconsistency/DAQdefault. Configuration scope not full ASAMcodec or commissionedA2L.',ASAM:'OriginalASAMMCD1XCP1.5.0Nov2017overview read: busindependent measurement/calibration, actualA2L/addresses/units, CAN/FlexRay/EthernetTCPUDP/SCI/SPI/USBdistinct transports. Full member protocol specification not claimed.'}
DECLARATIONS=[]
def d(k,t,m,s=AUTO,**kw):DECLARATIONS.append(declaration('xc_',k,t,m,s,SOURCES[s],**kw))
for k,m,opts,s in [('edition','Actual qualified normative/device implementation edition.',['AUTOSAR_R25_11','ASAM1_5_REGISTERED','REGISTERED_ACTUAL'],ASAM),('transport','Actual commissioned lower transport; never default CAN or Ethernet.',['CAN','CAN_FD_REGISTERED','FLEXRAY','UDP_IP','TCP_IP','SCI','SPI','USB','REGISTERED_ACTUAL'],ASAM),('packet_kind','Actual CTO commandresponse versus synchronous DTOdata.',['CTO','DTO'],AUTO),('daq_config','Actual static or dynamicDAQownership.',['STATIC','DYNAMIC'],AUTO),('consistency','Actual independent consistency scope.',['ODT','DAQ','EVENT'],AUTO),('event_type','Actual event channel DAQ/STIMcapability.',['DAQ','STIM','DAQ_STIM'],AUTO),('outcome','Actual independent consumingfunction result.',['ACCEPTED','PACKET_ONLY','ERROR','UNKNOWN'],ASAM)]:d(k,'select',m,s,options=opts)
UNITS={'1PS':.000000001,'10PS':.00000001,'100PS':.0000001,'1NS':.000001,'10NS':.00001,'100NS':.0001,'1US':.001,'10US':.01,'100US':.1,'1MS':1,'10MS':10,'100MS':100,'1S':1000}
d('event_unit','select','Actual event time unit ignored when event_cycle0, not inherited CANcycle.',options=list(UNITS))
for k,m,lo,hi,u,integer in [('max_cto','Actual announced/configured MAX_CTO; no standardchosen8 hardware capability.',8,255,'byte',True),('max_dto','Actual announced/configured MAX_DTO; not application65535payload.',8,65535,'byte',True),('min_daq','Actual predefined readonlyDAQlistcount.',0,255,None,True),('odt_count','Actual dynamicDAQODTcount.',0,252,None,True),('odt_entries','Actual dynamicDAQ ODTentrycount.',0,255,None,True),('odt_entry_daq_bytes','Actual DAQentrysize.',0,255,'byte',True),('odt_entry_stim_bytes','Actual STIMentrysize.',0,255,'byte',True),('max_event_channels','Actual configured eventchannelcount.',0,65535,None,True),('event_number','Actual symbolic eventchannelnumber.',0,65534,None,True),('event_priority','Actual eventpriority.',0,255,None,True),('event_max_daq','Actual eventDAQlistallocation.',0,255,None,True),('event_cycle','Actualsamplingcycleinselectedunit;0notcyclic.',0,255,None,True),('event_ms','Nominalsamplingperiod; not source-to-use deadline.',0,None,'ms',False),('packet_bytes','Actual complete CTO/DTOprotocolpacket includingPID/DAQ/timestamp/fill.',0,None,'byte',True),('protocol_overhead_bytes','Actual selected PID/DAQ/timestamp/filloverhead.',0,None,'byte',True),('lower_packet_max','Actual lowertransportpacketbudget accountingitsheaders/alignment.',1,None,'byte',True),('can_tx_id','Actual transmit CANidentifier.',0,536870911,None,True),('can_rx_id','Actual distinct receive CANidentifier.',0,536870911,None,True),('port','Actual commissionedTCP/UDPport; no inventedserviceport.',1,65535,None,True),('connections','Actual slave activeconnectioncount.',0,None,None,True),('source_ms','Actual measuredsample/event/A2Lprocessing bound.',0,None,'ms',False),('transport_ms','Actual selectedbus/framing/queues/retries bound.',0,None,'ms',False),('use_ms','Actual decoded/calibrationconsumer bound.',0,None,'ms',False),('e2e_ms','Actual source-to-use total independentlyqualified.',0,None,'ms',False),('deadline_ms','Independent consumingfunctiondeadline.',0,None,'ms',False),('age_ms','Actual consumeddataage.',0,None,'ms',False),('freshness_ms','Independent allowableage.',0,None,'ms',False)]:d(k,'number',m,min=lo,max=hi,unit=u,integer=integer)
for k,m in [('path_verified','Actual A2L/event/buffer/lowertransportpath qualified.'),('data_accepted','Actual independent consumingfunction succeeds.')]:d(k,'boolean',m)
for k,m in [('revision','Actual protocol/deviceedition.'),('a2l_source','Actual A2L memoryaddresses/encodings/units/event/DAQlist evidence.'),('device_source','Actual negotiatedMAX_CTO/MAX_DTO/capabilities/buffers.'),('transport_source','Actual separatelyqualified selectedlowerbus/binding andpacketbudget.'),('acceptance_source','Independent functiondeadline/freshness/errorcontract.'),('ip','Actual commissioned peer IPv4orIPv6address.'),('observation_source','Actual correlated producer/packet/lowertransport/functiontrace.')]:d(k,'text',m)
REQUIRED=('revision','a2l_source','device_source','transport_source','acceptance_source')
REMOVED={k:'XCP is busindependent; actuallower transport negotiatedseparately, no inheritedCAN/Ethernet/gateway default.' for k in (*WIRE_KEYS,*ETHERNET_KEYS)}
def semantics():
 rules=[]
 def r(k,w=None,**kw):rules.append(dict(parameter='xc_'+k,when={'xc_'+a:b for a,b in(w or {}).items()},source=AUTO,**kw))
 rules.extend(dict(parameter=k,when={},allowed=[],source=ASAM)for k in REMOVED)
 r('packet_bytes',{'packet_kind':'CTO'},maximum_parameter='xc_max_cto');r('packet_bytes',{'packet_kind':'DTO'},maximum_parameter='xc_max_dto');r('packet_bytes',equal_expression={'sum':['payload_bytes','xc_protocol_overhead_bytes']},maximum_parameter='xc_lower_packet_max')
 r('can_tx_id',{'transport':'CAN'},not_equal_parameter='xc_can_rx_id')
 for transport in('UDP_IP','TCP_IP'):r('connections',{'edition':'AUTOSAR_R25_11','transport':transport},maximum=1)
 for k in('odt_count','odt_entries'):r(k,{'daq_config':'STATIC'},allowed=[])
 for unit,factor in UNITS.items():r('event_ms',{'event_unit':unit},when_positive=['xc_event_cycle'],equal_expression={'product':['xc_event_cycle',factor]})
 r('event_ms',{'event_cycle':0},allowed=[0])
 r('e2e_ms',equal_expression={'sum':['xc_source_ms','xc_transport_ms','xc_use_ms']},maximum_parameter='xc_deadline_ms');r('age_ms',maximum_parameter='xc_freshness_ms')
 for k in('source_ms','transport_ms','use_ms'):r(k,when_present=['xc_e2e_ms'],required=True)
 for k in('e2e_ms','deadline_ms','age_ms','freshness_ms','observation_source'):r(k,{'data_accepted':True},required=True)
 r('path_verified',{'data_accepted':True},required=True,allowed=[True]);r('outcome',{'data_accepted':True},required=True,allowed=['ACCEPTED'])
 return dict(rate_model={'type':'XCP_ACTUAL_LOWER_TRANSPORT','fields':[]},parameter_evidence_scope='EXPLICIT_LAYER',required_parameters=['xc_'+k for k in REQUIRED],native_parameter_prefixes=['xc_'],parameter_constraints=rules,medium_access_model='SELECTED_LOWER_TRANSPORT',arbitration_model_id='SELECTED_LOWER_BINDING',mechanisms={'network':['XCP_BUS_INDEPENDENT_A2L_NEGOTIATED_CAPABILITIES'],'timing':['ACTUAL_EVENT_BUFFER_AND_LOWER_TRANSPORT']})
def fields():return build_fields(DECLARATIONS,['xc_'+k for k in REQUIRED],{'xc_'+k:[dict(when={'xc_edition':'AUTOSAR_R25_11'},value=v,source=AUTO,source_revision=SOURCES[AUTO])]for k,v in [('consistency','ODT'),('event_type','DAQ')]})
