FROM networkis:candidate-b0ffeb6e54a3
LABEL networkis.development=true
COPY . /app
ARG NIS_BUILD_COMMIT_ID
RUN NIS_BUILD_COMMIT_ID="$NIS_BUILD_COMMIT_ID" python /app/scripts/write-build-info.py
RUN cd /app/frontend && node /usr/local/lib/node_modules/npm/bin/npm-cli.js run build
